### ISSUE TITLE
bs binaries paths are determined wrong in monorepos

### ISSUE THREAD

**Issue by alexfedoseev** [rescript-lang/rescript-vscode#10]
https://github.com/rescript-lang/rescript-vscode/blob/ba96a2fe1c603e73703bce7c25244d2508dcc334/server/src/server.ts#L291

E.g. this wouldn't work for monorepos that use yarn workspaces, b/c binaries are hoisted above the bsconfig's node_modules.

**Comment by gaku-sei** [comment]
Second this, it doesn't work in monorepos 😞 

A solution in the short term could be to have a "bsb path"/"bsc path" settings maybe? It's something that could be useful anyway 😄

**Comment by dan003400** [comment]
We as well use yarn workspaces and have lost formatting.

**Comment by BlueHotDog** [comment]
Came here to open the same issue.
Any solution would help as we're really excited to get started using it. looks much more stable, fast. fun. you got me all excited!

**Comment by gaku-sei** [comment]
@BlueHotDog you can already get the extension working with monorepos if you use this branch: https://github.com/rescript-lang/rescript-vscode/pull/16 it works fine so far 😄

**Comment by dchambers** [comment]
I worked around this for the time being by adding this `package.json` config to the sub-project where I'm going to be using ReScript:

```
"workspaces": {
  "nohoist": ["bs-platform"]
},
```

and then running:

```
yarn --force
```

Alternatively you can do this globally by modifying the `workspaces` definition in your root `package.json` from something like this:

```
"workspaces": ["libs/*"],
```

to this:

```
"workspaces": {
  "packages": ["libs/*"],
  "nohoist": ["**/bs-platform"]
},
```

**Comment by BlueHotDog** [comment]
We rather wait until this extension stabilizes. this issue is open for 4 months, with open Prs trying to fix this. can any maintain please help here?

**Comment by dan003400** [comment]
Hey guys, check this out if you are using yarn workspaces, I have a PR in that has a current release flag that you can try for vim plug.

https://github.com/rescript-lang/vim-rescript/pull/19

**Comment by IwanKaramazow** [comment]
We've fixed this and it's released =D 
See [forum](https://forum.rescript-lang.org/t/ann-rescript-vscode-1-0-4-and-vim-rescript-1-2-0-relased/877)  or the [release](https://github.com/rescript-lang/rescript-vscode/releases/tag/1.0.4)
