### ISSUE TITLE
Doesn't work with ReScript@9.1.0

### ISSUE THREAD

**Issue by gaku-sei** [rescript-lang/rescript-vscode#104]
I tried to replace `bs-platform` by `rescript` (that works very well actually 😄 ), but got this issue:

<img width="580" alt="Capture d’écran 2021-04-14 à 16 42 14" src="https://user-images.githubusercontent.com/3982371/114672687-600f1100-9d40-11eb-861c-2dc6e81f35c8.png">

(For now I will keep both rescript and bs-platform installed).

**Comment by opusmagnum** [comment]
I have the same problem with rescript@9.1.1. It seems to come from here -- https://github.com/rescript-lang/rescript-vscode/blob/aa1712bda1ccf6eb0ed74637830f0091d3d9511d/server/src/constants.ts#L8

**Comment by chenglou** [comment]
Made a small new release. Thanks
