### ISSUE TITLE
Plans on improving poor syntax highlighting?

### ISSUE THREAD

**Issue by carljohnesan** [rescript-lang/rescript-vscode#105]
I've read some pull request why syntax highlighting is like that, but can't you just take reason grammar or something?
Just look at these two screenshots:

Rescript:
![rescript](https://user-images.githubusercontent.com/47556468/114830802-4b308d00-9dd5-11eb-9c70-48e5bd01c81b.png)

---
Reason:
![reason](https://user-images.githubusercontent.com/47556468/114830829-5388c800-9dd5-11eb-921c-fbb8711573e7.png)

See? It feels like half of code is just uncolored, variable names, record type fields etc.
Is it that hard to take reason grammar and tweak it for rescript slightly different syntax?
I would very like to stick to rescript. But the way things are now makes me feel like I should wait a year or two, not to demoralize.

**Comment by chenglou** [comment]
Hello. I guess you've seen [this](https://github.com/rescript-lang/rescript-vscode#recommendation). Additionally, the Reason grammar isn't the same, and is pretty unmaintainable and has some pathological regex problems.

I'll close this as there are other more specific issues on this subject we can consider.

**Comment by carljohnesan** [comment]
I've saw recommendation. And? Dark+ theme, one dark, etc it's all the same! JSX uncolored, types uncolored, variables uncolored, record field names uncolored, nearly everything uncolored except keywords and some other stuff.

Please just answer a question do you plan to improve syntax highlighting?
If not I'll try to get used to work without syntax highlighting at all. ascetically.
Just answer please.

**Comment by chenglou** [comment]
We plan to improve it but only if it doesn't affect correctness.

**Comment by carljohnesan** [comment]
Thank you
