### ISSUE TITLE
Feature Request: A Button or Command to open corresponding .bs.js file in split pane (and track changes to current .res file)

### ISSUE THREAD

**Issue by huntwj** [rescript-lang/rescript-vscode#107]
The documentation for ReScript is constantly telling me to keep the generated JS open in another pane. It would be great if this extension maintained that pane for me so as I swap between .res files, the corresponding .bs.js file is always on the right.

**Comment by zth** [comment]
Closing this as a variant of this feature was implemented in https://github.com/rescript-lang/rescript-vscode/pull/294
