### ISSUE TITLE
GoTo definition navigates to .resi 

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [rescript-lang/rescript-vscode#108]
GoTo definition navigates to the corresponding .resi interface file. I had to go to the .res file and search again.

It would be useful if the GoTo definition navigates to the .res file.

**Comment by cristianoc** [comment]
It's like that by design. You can jump from the `.resi` to the `.res` if you really want to see the implementation. Normally as a user of the API you'd mostly want to see the interface. I guess...

**Comment by a-c-sreedhar-reddy** [comment]
I am wondering why would I like to look at the resi when I can get the type by hovering?

**Comment by cristianoc** [comment]
This is definitely a grey area in the design space. E.g. I think I've seen solutions where both are given.
Happy to revisit if we have more feedback from a bunch of people.

**Comment by chenglou** [comment]
So there's a possible distinction of "go to definition" vs "go to implementation" in TS:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/1909539/116172366-7feaf100-a6bf-11eb-9fde-a37be3ac082e.png">
Not exactly the same, but yeah
