### ISSUE TITLE
Formatting is not working when prettier is set as the default formatter

### ISSUE THREAD

**Issue by mellson** [rescript-lang/rescript-vscode#109]
When you set Prettier as the default formatter for all files in VSCode with the setting: `"editor.defaultFormatter": "esbenp.prettier-vscode"` formatting does not work in ReScript files.

I need to remove the default option and add Prettier per file type in order to make it work as expected.

**Comment by chenglou** [comment]
Dunno, but I'll let other chime in if this is not the expected behavior. We aren't doing anything weird with the formatter settings

**Comment by mellson** [comment]
I found that the easiest way for me to fix this is by specifying the rescript formatter for rescript and prettier as the default for everything else. This seems to work great, so closing with this comment.

Example extract of my settings:
```
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[rescript]": {
    "editor.defaultFormatter": "chenglou92.rescript-vscode"
  },
```

**Comment by kswope** [comment]
This should be front page of the docs, as it is with the prettier docs

https://github.com/prettier/prettier-vscode#default-formatter

**Comment by cristianoc** [comment]
Looks like following prettier docs is the root cause of mid configuration.

**Comment by kswope** [comment]
Yea the example *values* don't make a lot of sense, but the fact you can override the default is not easily found.



This is set from the GUI settings, which is what most people will click, and it will cover css, html, javascript, typescript, etc, so most people are probably be very satisified with that checkbox

```
  "editor.defaultFormatter": "esbenp.prettier-vscode",
```

But I've never seen an default override in the GUI settings, and I have no idea why a plugin can't override the default, so maybe just putting just this in the docs

```
you probably need to override the default formatter like this:

  "[rescript]": {
    "editor.defaultFormatter": "chenglou92.rescript-vscode"
  },
```

It might seem like a small thing, but when you are giving a new language a try, not even being able to get the formatting working is a little off putting.

**Comment by cristianoc** [comment]
Makes perfect sense. Would you draft a PR for the readme?

**Comment by cristianoc** [comment]
@kswope

**Comment by kswope** [comment]
Waiting on some feedback from my rant at https://github.com/microsoft/vscode/issues/126187

**Comment by zth** [comment]
@kswope is this issue still relevant?

**Comment by kswope** [comment]
please close

As a compromise they added a helpful dialog box that asks for a formatter and saves it so users are less inclined to just set prettier as the default formatter for everything and break formatting for every lang that prettier doesn't support.

**Comment by zth** [comment]
Thanks for the info!
