### ISSUE TITLE
Error parsing docs for `Js.re.exec_` in stdlib

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-vscode#118]
Should I file this on bucklescript?
<img width="999" alt="Screen Shot 2020-11-19 at 14 45 58" src="https://user-images.githubusercontent.com/4534692/99733695-668dab00-2a76-11eb-9a3c-b33a64906285.png">

**Comment by cristianoc** [comment]
We'll just remove special odoc parsing.
