### ISSUE TITLE
Feature request: support autocomplete

### ISSUE THREAD

**Issue by allforabit** [rescript-lang/rescript-vscode#12]
I'm not sure if it's a problem with my setup or something that hasn't been implemented yet but it would be great to have some sort of autocomplete. I don't see it on the feature list so I'm assuming it's not there yet. I'm only starting to look at rescript so it's very possible that I've missed something too. Thanks very much!

**Comment by boyswan** [comment]
Is there any news on this?

**Comment by ryyppy** [comment]
Autocomplete will be the last feature that will be added.

**Current priority list:**
1.  Type on Hover
2. Jump to definition (with corrected position when jumping to a JSX component)
3. Error messages as you type
4. Autocomplete

Core functionality for 1) and 2) is actually implemented and working (but not wired up to the LSP / VSCode setup yet).

**Comment by ryyppy** [comment]
Update:

1, 2, 3 and 4 have been successfully implemented (see [latest blog post](https://rescript-lang.org/blog/editor-support-custom-operators-and-more)).

We are currently cleaning up our work, and also prepare precompiled native executables for our editor-integration (the part that does all the magic behind the scenes). Final release will be announced on our [forum](https://forum.rescript-lang.org).

Please bear in mind that we greatly reduced the complexity of our tooling by removing a lot of bulk and functionality from the original RLS to make sure that the tooling is fast and reliable (no outdated caches, no memory leaks). So be aware that the initial release will have **less** features and might feel a little minimalistic. We will add back features gradually after the initial release, based on feedback.

**Comment by alexfedoseev** [comment]
@ryyppy I have a question regarding `#3`. I thought error reporting was implemented on format/save since it reads the data from compiler log but you said it will be reported "as you type"?

**Comment by IwanKaramazow** [comment]
The current implementation is "when saved". It's not yet "as you type" in this iteration.

**Comment by ryyppy** [comment]
Sorry my bad, updated my comment

**Comment by amiralies** [comment]
Maybe we can close this?
