### ISSUE TITLE
Expand more referenced records in hover when it makes sense?

### ISSUE THREAD

**Issue by zth** [rescript-lang/rescript-vscode#121]
This is just an idea, but something I find myself struggling with in both ReScript and in TS is whenever a record that's important for something I hover is not expanded, but just referenced by its name. Here's an example:

![image](https://user-images.githubusercontent.com/1457626/115149518-cb205680-a064-11eb-8b54-6ea6adb9c9e6.png)

This shows hovering a variable that contains a function. That function is wrapped in React's callback mechanism, and the _first level_ of the record is expanded (`React.callback`). But, in this (and quite a few other scenarios), it'd be really helpful if one additional level of records could be expanded. In this particular case, this would mean that `Confirm.confirmItem` would be expanded. 

To be clear of what I mean, this is what I'd like to see:

```rescript
React.callback<Confirm.confirmItem, unit>

type callback<'input, 'output> = 'input => 'output
type Confirm.confirmItem = {
  text: string,
  callback: unit => unit
}
```

I realize this might be difficult because where do you stop, how many levels deep do you go, and where do you draw the line given the fact that there could be a large number of records referenced in a single hover. But, maybe there's a common ground for cases that are quite common, like the one I describe?

**Comment by cristianoc** [comment]
Let's close it for now -- there are quite a few other issues coming up these days that are uncontroversial.
