### ISSUE TITLE
Feature request: Support autocomplete of JSX props via Ctrl + Space

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/rescript-vscode#147]
Because as there is no trigger character for it now you can only type the first character to get completion, so you need to know at least something about the possible props.

**Comment by chenglou** [comment]
What does your partially edited code look like? ctrl-space is already supported by the editor itself to trigger autocompletion

**Comment by cknitt** [comment]
Example:

If I type the first letter of a valid prop name, I get this, which is great:

<img width="541" alt="Bildschirmfoto 2021-04-26 um 16 38 18" src="https://user-images.githubusercontent.com/591384/116101073-d2231680-a6ad-11eb-9ce5-e9b1215ee5ed.png">

If I do not know the valid prop names and would like to see a list of them, I type Ctrl-Space and get

<img width="530" alt="Bildschirmfoto 2021-04-26 um 16 40 17" src="https://user-images.githubusercontent.com/591384/116101416-16aeb200-a6ae-11eb-85a5-937a94cffa18.png">

which is not what I would have expected.

Compare with what I get in TypeScript when I press Ctrl-Space in the same situation (different project and different component, but you can see that I get the list of props on top):

<img width="898" alt="Bildschirmfoto 2021-04-26 um 16 41 57" src="https://user-images.githubusercontent.com/591384/116101684-537aa900-a6ae-11eb-8ad0-5c5e8368db1f.png">
