### ISSUE TITLE
Autocomplete suggestion on -> doesn't appear for record field

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-vscode#157]
I have a record that has a field that is an array, and when I type `record.arr->` I don't get any type suggestions.
The autocomplete dropdown appears for when I type `record.` and when I have an array directly like `arr->`.

This seems to repro for a new record type and instance of it.
<img width="337" alt="Screen Shot 2021-04-26 at 18 33 28" src="https://user-images.githubusercontent.com/4534692/116171585-e707a600-a6bd-11eb-89f9-a870562f8ff9.png">

**Comment by cristianoc** [comment]
Intended. There's no such magic yet.
But one day...

**Comment by cristianoc** [comment]
Autocomplete works by parsing backwards from the cursor and understand what to autocomplete from the context.
Currently for `->` the assumption is that the lhs is a simple ID, or certain literals such as `"hello"`.

For this, one would need to parse, `a.f`, find the type of `a`, figure out it's a record, find the type of `a.f` from it, use the resulting type to populate autocomplete.
