### ISSUE TITLE
A case where Go to Definition does not work

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#165]
Given

```rescript
module A = {
  let makeX = () => (1, 2)

  let (x, _) = makeX()
  let (y, _) = (1, 2)
}

let x = A.x
let y = A.y
```

Go to Definition works for y, but not for x:

<img width="254" alt="Bildschirmfoto 2021-04-27 um 09 26 42" src="https://user-images.githubusercontent.com/591384/116202276-aef27880-a73a-11eb-878b-4b61013d940f.png">

**Comment by cristianoc** [comment]
@cknitt thanks for the report!
Turns out, tuple patterns are not handled at the moment.

**Comment by cristianoc** [comment]
Done
