### ISSUE TITLE
Autocompletion suggests props that were already assigned

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#175]
(Beta2)

When I press Ctrl-Space here:

```rescript
module X = {
  @react.component
  let make = (~a: string, ~b: int) => React.string(a ++ string_of_int(b))
}

<X a="hello" b=42 
```

I get this:

<img width="671" alt="Bildschirmfoto 2021-04-27 um 18 18 35" src="https://user-images.githubusercontent.com/591384/116276630-fd2c6980-a784-11eb-951e-7b8c6e95c2a3.png">

i.e. `a` and `b` are in the list even though they already have values assigned.

(In TypeScript, only props that were not assigned any values yet are shown in the list.)

**Comment by cknitt** [comment]
The same applies for named arguments:

<img width="290" alt="Bildschirmfoto 2021-04-27 um 18 55 59" src="https://user-images.githubusercontent.com/591384/116281690-3e734800-a78a-11eb-8028-2c0274c49dcf.png">

**Comment by cristianoc** [comment]
Indeed

**Comment by cristianoc** [comment]
Labeled args are a bit more complex, maybe later.

**Comment by cknitt** [comment]
@cristianoc Thanks for the quick fixes! Shall I open a separate issue for the labeled args?

**Comment by cristianoc** [comment]
Sure go ahead with that.
