### ISSUE TITLE
Outline stale

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/rescript-vscode#176]
`documentSymbol` event is sent to us upon file refresh and keystroke, but not on save. So our outline view is always one step behind when we change a binding or module. Not sure what to do

**Comment by amiralies** [comment]
This is known issue for vscode, I'm not sure if we can do better our side aside from compiling on edit which is not ideal.
see this https://github.com/microsoft/vscode/issues/108722.
I think people would use this feature mostly when they are reading the code so I think it's fine to ship this as it is.

**Comment by zth** [comment]
This has been fixed recently by @cristianoc and I think we can close this?
