### ISSUE TITLE
Hover over React component declaration in .resi file shows incorrect type information

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#177]
(Beta2)

In the .resi, the result type is wrong (should be `React.element`).
Also `~key` and `unit` are shown for .resi, but not for .res. 

A.res:
```rescript
@react.component
let make = (~a) => React.string(a)
```

<img width="276" alt="Bildschirmfoto 2021-04-27 um 18 46 13" src="https://user-images.githubusercontent.com/591384/116280346-da9c4f80-a788-11eb-851b-9bc7beea6dff.png">

A.resi:
```rescript
@react.component
let make: (~a: string) => React.element
```

<img width="434" alt="Bildschirmfoto 2021-04-27 um 18 43 18" src="https://user-images.githubusercontent.com/591384/116279926-7083aa80-a788-11eb-96d9-3c9d747dd814.png">

**Comment by cristianoc** [comment]
Labeling all these with jsx meaning: not going to address them separately from changes to the ppx for JSX.
