### ISSUE TITLE
Incorrect type when hovering over a React element that uses a module alias

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#180]
(Beta2)

Given

```rescript
module A = {
  @react.component
  let make = (~children: React.element) => children
}

module A1 = A

let _ = <A> <div /> <div /> </A>

let _ = <A1> <div /> <div /> </A1>
```

hover shows the following:

<img width="419" alt="Bildschirmfoto 2021-04-27 um 19 23 42" src="https://user-images.githubusercontent.com/591384/116285091-1554b680-a78e-11eb-8000-d7fd16af85d9.png">

<img width="283" alt="Bildschirmfoto 2021-04-27 um 19 23 54" src="https://user-images.githubusercontent.com/591384/116285118-1dacf180-a78e-11eb-9a6c-8ce9109dd64c.png">

(and Go to Definition does not work for `A1`)

**Comment by cristianoc** [comment]
Labeling all these with jsx meaning: not going to address them separately from changes to the ppx for JSX.

**Comment by cristianoc** [comment]
Looks like this is already fixed in master: https://github.com/rescript-lang/rescript-vscode/pull/241
