### ISSUE TITLE
Hover shows type string for DOM elements

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#181]
Example:

<img width="141" alt="Bildschirmfoto 2021-04-27 um 19 28 27" src="https://user-images.githubusercontent.com/591384/116285890-e723a680-a78e-11eb-974f-028ef8c67dbc.png">

**Comment by cristianoc** [comment]
Labeling all these with jsx meaning: not going to address them separately from changes to the ppx for JSX.

**Comment by cristianoc** [comment]
I believe this is fixed in master.
