### ISSUE TITLE
Jump to def doesn't work inside JSX fragment 

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-vscode#182]
Here's the code I have, and cmd+click on SectionHeader, the tool jumps to React.re on line 3.

```rescript
<>
      <SectionHeader>
            {ReasonReact.string(heading)}
      </SectionHeader>
</>
```

**Comment by cristianoc** [comment]
This is in a series of issues related to JSX ppx that we should solve from first principles.
Currently:
1) the ppx generates several symbols at the same location.
2) the editor tries to heuristically figure out what's going on: which of the symbols at that same location it should deal with.

There are several issues posted these days in this repo, that have the same root.
Planning to investigate this starting from the react ppx level first.
++ @rickyvetter

**Comment by cristianoc** [comment]
These probably related:
https://github.com/rescript-lang/rescript-vscode/issues/181
https://github.com/rescript-lang/rescript-vscode/issues/180
https://github.com/rescript-lang/rescript-vscode/issues/177

**Comment by bsansouci** [comment]
I just opened #183 which is probably related as well

**Comment by cristianoc** [comment]
Labeling all these with `jsx` meaning: not going to address them separately from changes to the ppx for JSX.
