### ISSUE TITLE
Error for variable not found is at the wrong location for JSX props punning

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-vscode#183]
I have a component and am passing props of the same name as the variable, like
```rescript
open Common

@react.component
let make = () => {
    <MyComponent article />
}
```

and the variable `article` is not declared, so I get an error, but the line number seems to be 0 because the error shows up at the top of the file, underlining `open`.

**Comment by cristianoc** [comment]
What's a complete self-contained example? (Failed to repro)

**Comment by cristianoc** [comment]
Feel free to reopen with a repro.
