### ISSUE TITLE
Hover/go to definition for function parameter types in a .resi file

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#204]
Given

A.resi:
```rescript
let f: Js.Json.t => unit
```

A.res:
```rescript
let f: Js.Json.t => unit = ignore
```

for Js.Json.t, hover and go to definition work in the .res file, but not in the .resi file.

**Comment by cristianoc** [comment]
Here we're talking about `Js.Json.t `, not `f` which works.
Indeed signatures are only partially supported at the moment.
