### ISSUE TITLE
 Show refrences shows wrong refrences for record labels

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/rescript-vscode#211]
given this code :
```rescript
type t = {x: int}
let a = {x: 2}
let b = {x: 3}
let foo = a.x

```

when i run action on `a`'s `x` (on second line)  i get following refrences:
![image](https://user-images.githubusercontent.com/13261088/116696777-95ba2800-a9d7-11eb-9b4e-a9c3e934ff6f.png)
refrence on `b`'s `x` shouldn't be shown

**Comment by cristianoc** [comment]
All the occurrences refer to label `x` in the type declaration of t`.
