### ISSUE TITLE
self-cycle not reported through the tool

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-vscode#212]
When a module references itself, nothing shows up until you get a notification in vscode that the server has crashed.
Looking at my terminal, I saw the error message `FAILED: MyAwesomeModule has a self cycle`

**Comment by cristianoc** [comment]
That's intriguing. Example?

**Comment by cristianoc** [comment]
To be re-opened with an example.

**Comment by bsansouci** [comment]
Example! Add a file `A.res` in your codebase, in it put:
```rescript
let a = 10

Js.log(a)
```

Everything typechecks and builds, now change it to
```rescript
let a = 10

Js.log(A.a)
```
The server crashes and you get a popup that says "Wanna start the server", you do it 5 times and then it says it crashed 5 times. It never reports that the error is that there's a cycle, but that error gets reported if you manually run bsb.

**Comment by cristianoc** [comment]
Same as this:
https://github.com/rescript-lang/rescript-vscode/issues/220

Though there's the comment about crashing, too.

**Comment by cristianoc** [comment]
I suspect it fails when parsing this:

```
#Start(1620252447923)
FAILED: A has a self cycle
#Done(1620252448018)
```

**Comment by cristianoc** [comment]
++ @chenglou

**Comment by cristianoc** [comment]
Can repro the crashing too.

**Comment by cristianoc** [comment]
Just revisited this. For context: self-cycle error goes to `compiler.log`, but cycle of size 2 or more the log is empty. Cannot be solved in the editor without a compiler fix.
