### ISSUE TITLE
JSX autocomplete breaks after certain prop types

### ISSUE THREAD

**Issue by zth** [rescript-lang/rescript-vscode#213]
Autocomplete for JSX stops working for me after I've added a prop with a string literal. So, this:

```
<MyComponent someProp=someVar anotherProp="Text here"
```
Completion works fine after someProp, but breaks after anotherProp. 

I think it happened with other things than string literals too, but I'm not at my computer right now. I'll amend this issue with info about later if it still happens.

**Comment by cristianoc** [comment]
True, only works with `{"Text here"}` at the moment. Can be relaxed.

**Comment by cristianoc** [comment]
Works for me. Do you have the complete example?

**Comment by zth** [comment]
@cristianoc let me try and put up a proper reproduction as soon as I'm by the computer again.

**Comment by zth** [comment]
@cristianoc turns out it wasn't strings at all, I was just fooled by the complexity of the component I had when I found it. Instead, it seems to be variants with payloads and _without_ wrapping {}. So, this:
```
@react.component
open Component

let make = () => <> <Component style=First("Text")  /> </>
```

Wrapping with `{}` makes autocomplete work again (`<Component style={First("Text")} />`), and variants without payloads does not break regardless of if they're wrapped or not. Reproduction here:
https://github.com/zth/rescript-editor-tooling-playground/blob/master/src/OtherComp.res

**Comment by cristianoc** [comment]
Thanks yes that's expected. Can be extended to support that too.

**Comment by zth** [comment]
Out of curiosity, why is it expected?

**Comment by cristianoc** [comment]
Because that case is not covered yet.

**Comment by zth** [comment]
Ah, right.

**Comment by cristianoc** [comment]
Done in https://github.com/rescript-lang/rescript-vscode/pull/214

**Comment by zth** [comment]
Thanks, impressive turn-around @cristianoc!
