### ISSUE TITLE
GLIBC_2.29' not found (Debian 10 Buster)

### ISSUE THREAD

**Issue by ixzzd** [rescript-lang/rescript-vscode#216]
Hello! At first I would like to thanks all contributors for the work done on this project!
Recently I faced the GLIBC mismatch issue with rescript-vscode v1.1.0+ and Debian 10 Buster (current stable)

> /home/username/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/username/.vscode-server/extensions/chenglou92.rescript-vscode-1.1.1/server/analysis_binaries/linux/rescript-editor-analysis.exe)

The latest available libc-bin version for the current stable Debian release is 2.28 https://packages.debian.org/stable/libc-bin

Is there any chance if rescript-vscode continues support the current Debian stable release?
Probably dependending on GLIBC v 2.28 for a while? Are there any blockers?

**Comment by cristianoc** [comment]
It depends on what's available via GitHub actions.

**Comment by cristianoc** [comment]
++ @chenglou

**Comment by cristianoc** [comment]
Also I'm not sure we use all the static linking flags at the moment.

**Comment by ixzzd** [comment]
Probably related breaking changes were mentioned in 1.1.1 changelog:

> Very old linux versions are no longer supported.
https://github.com/rescript-lang/rescript-vscode/blob/master/CHANGELOG.md#111

**Comment by cristianoc** [comment]
Building on an older machine is required here.
Would building on  `ubuntu-18.04` in CI help here?

**Comment by cristianoc** [comment]
@ixzzd in case it helps, can you try with the CI artifact here: https://github.com/rescript-lang/rescript-vscode/pull/218

**Comment by ixzzd** [comment]
@cristianoc  probably it would help, but build is falling on "Use Ocaml" step
I can't download artifacts ;(

**Comment by cristianoc** [comment]
Yes, for some reason CI build fails once the compiler version changes.

**Comment by cristianoc** [comment]
@ixzzd want to try now? CI is green.

**Comment by ixzzd** [comment]
@cristianoc I rechecked it, `rescript-editor-analysis.exe` build with `ubuntu-18.04` works fine in with libc 2.28 :tada: Thank you! Will this binary be included in the next extension version?

**Comment by cristianoc** [comment]
> Will this binary be included in the next extension version?
I think so -- the changes to CI seem benign in general.

**Comment by cristianoc** [comment]
In master now.

**Comment by cristianoc** [comment]
@ixzzd new release is out

**Comment by ixzzd** [comment]
`1.1.2` works fine with Debian 10, thank you @cristianoc!
