### ISSUE TITLE
Enable command for creating interface files once a new release of the compiler has shipped.

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/rescript-vscode#235]
Issue to track the discussion at the end of https://github.com/rescript-lang/rescript-vscode/pull/90.

**Comment by cristianoc** [comment]
++ @fhammerschmidt

**Comment by fhammerschmidt** [comment]
Thank you very much!

**Comment by fhammerschmidt** [comment]
I think you can close this one?

**Comment by zth** [comment]
Closing since this has shipped now.
