### ISSUE TITLE
Type diagnostics on hover are wrong

### ISSUE THREAD

**Issue by eWert-Online** [rescript-lang/rescript-vscode#24]
It seems like the type diagnostics on hover are assuming my mouse to be on top of a completely different expression.

In the following screenshot I am hovering over the `addEventListener` but the type diagnostics say that i am hovering over `Belt.Option`. (Which is 5 rows above and to the right of where I am actually hovering).

![hover](https://user-images.githubusercontent.com/7459510/100382459-b4c52000-301b-11eb-9288-5c24f9b540b8.png)

**Comment by amiralies** [comment]
Can you send a snippet or a repository so I can reproduce this?

**Comment by eWert-Online** [comment]
I checked on a different pc and it seems to be working there.
I will close this for now and investigate a bit more, if i can consistently reproduce this.
