### ISSUE TITLE
Rename silently fails for renaming a module that's a file name

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/rescript-vscode#240]
cc @amiralies

This should either work, or we should put up an error message. Whichever one's safer and simpler.

**Comment by amiralies** [comment]
`WorkspaceEdit`supports file renames, I think we should use that if that's trivial. I'll take a look proabably this week.

**Comment by amiralies** [comment]
first we need to fix references for file/top-level modules.
https://github.com/rescript-lang/rescript-vscode/blob/98ec36bc0d52dfbaa9ae1d4e32b3e1df7bf29691/analysis/src/References.ml#L467-L468

**Comment by cristianoc** [comment]
@amiralies 
In examples, references to file-level modules seem to work.
Is there an example showing cases where they don't work?

**Comment by cristianoc** [comment]
This is what a reference to a file looks like:
```
{"uri": "Foo.res", "range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}}
```
Perhaps the reference should have a different format?

**Comment by amiralies** [comment]
Trying to get references to a file level module results in an empty array for me.

**Comment by cristianoc** [comment]
What does the example look like?

**Comment by amiralies** [comment]
Main.res :
```rescript
let x = AnotherModule.b

```

AnotherModule.res:
```rescript
let b = 3

```

cmd: 

```sh
rescript-editor-analysis.exe references src/Main.res 0 15
```

**Comment by amiralies** [comment]
perhaps you are running definition command?

**Comment by cristianoc** [comment]
Thanks you're right.
Added that as an example, to start taking a look:
https://github.com/rescript-lang/rescript-vscode/pull/248

**Comment by cristianoc** [comment]
@amiralies in the PR https://github.com/rescript-lang/rescript-vscode/pull/248/files, it finds:
```
[{"uri": "References.res", "range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}}]
```

which is something, but it would try to go rename at position (0,0).
Any idea of what format should represent the entire file?

**Comment by cristianoc** [comment]
I guess there isn't really a way to reference an entire file, as that's a peculiarity of ocaml's module system.
And perhaps the best option is to issue an error message.

**Comment by amiralies** [comment]
aside from reference to the file-module itself we should find references in other files to that file, if that's not possible I think it's okay for now to show error message.

**Comment by cristianoc** [comment]
> aside from reference to the file-module itself we should find references in other files to that file, if that's not possible I think it's okay for now to show error message.

I think the best one can hope for is: in the presence of `File.res`. Given a use `File.foo`, when finding all references to `File`, try to find all the other references.

**Comment by cristianoc** [comment]
Done in the updated https://github.com/rescript-lang/rescript-vscode/pull/248.

**Comment by cristianoc** [comment]
So if there are several references to the same file, the instances are renamed (but the file is not).
