### ISSUE TITLE
Renaming tool removes ~ from named argument

### ISSUE THREAD

**Issue by bsansouci** [rescript-lang/rescript-vscode#244]
First, thank you for shipping this useful feature! 
I tried it on a named argument and it did the renaming but remove the `~` from the argument name.

**Comment by cristianoc** [comment]
Confirmed.
This seems viscose's doing, but the question is how to prevent it.

**Comment by cristianoc** [comment]
Looks like the location range includes the whole `~x`, which is then replaced.
If it contained `x` only, it would not.
