### ISSUE TITLE
Formatting bug

### ISSUE THREAD

**Issue by FostersData** [rescript-lang/rescript-vscode#249]
Hey, I'm encountering a formatting bug where the formatter inserts new blank lines on every save.

I had the same repo open in WSL through VS Code and it didn't do this, so looks like it only affects Windows directly.

Repro: clone down https://github.com/ryyppy/rescript-nextjs-template and format `Index.res` - inserts new blank lines on every save.

**Comment by amiralies** [comment]
I think this is fixed on latest `rescript` relaese, can you give a try?

**Comment by cristianoc** [comment]
Closing optimistically. Feel free to reopen if still there I the latest release.
