### ISSUE TITLE
Signature help on function applications

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/rescript-vscode#252]
https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp

**Comment by cristianoc** [comment]
What's the idea -- different than hover?

**Comment by amiralies** [comment]
It automatically opens when typing function applications (via `(` for example) and also users can config a hotkey to open the signature help while writing.
Another feature i see in ts extension is it highlights current parameter you're applying in signature help box.

**Comment by amiralies** [comment]
https://user-images.githubusercontent.com/13261088/119499113-9f873f00-bd7b-11eb-9750-483fd7eaf893.mp4

This is an exmaple from ts extension

**Comment by cristianoc** [comment]
How's that triggered in the example? By `(` ?
And any ideas of how the mechanism is different from normal auto-completion?

**Comment by cristianoc** [comment]
This feature is quite compelling.

**Comment by cristianoc** [comment]
This looks roughly like:
- `(` triggers signature help
- `,` re-triggers (for the n+1-th argument)

Needs a list of labels (the function parameters), and an index (of the current argument).

So:
```rescript
let add = (x,y) => x+y
```

then
`foo(3,`

would need to give:
- `[int, int]` (the list of parameters, perhaps named with conventional names, perhaps one can retrieve "x" and "y" from the ast)
- 1 (index of the second parameter)

**Comment by cristianoc** [comment]
As usual some care is required about context:
`foo(3, (2,` should not trigger anything as it's about an inner tuple, not an argument to `foo`.

**Comment by cristianoc** [comment]
For perf reasons, context scanning should happen *before* doing any other work that scans project structure etc. As context scanning is pure string parsing.

**Comment by cristianoc** [comment]
In fact, the same perf comment apply to completion: https://github.com/rescript-lang/rescript-vscode/pull/255

**Comment by oblitum** [comment]
The server publishes the characters that trigger this in _Server Capability_ `SignatureHelpOptions.triggerCharacters`.

**Comment by oblitum** [comment]
This is must have, most servers provide this. Just having bare function names completed is a bit lacking. Also, a good chunk of servers also provide snippet expansion on top, meaning, not only is signatureHelp available, you can also expand the function call with all arguments filled with placeholders you can jump to.

**Comment by zth** [comment]
Unless @cristianoc disagrees, this sounds like a good first issue for a contributor with some OCaml skills. Essentially, we should have all we need in the analysis bin now that we've integrated the full parser.
