### ISSUE TITLE
Exhaustive pattern matching for variants and poly variants.

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/rescript-vscode#253]
https://user-images.githubusercontent.com/13261088/119528876-d0c13880-bd96-11eb-8315-4b7f89b8a30a.mp4

Example from scala. I'm not sure how this should be done. scala has advantage of `match` keyworkd coming after target expression so can decide to show that snippet based on that. can we do this with opening brace?
for example 
```rescript
type user = Owner | Admin | User

let isSuperUser = (user: user) => switch user { // show snippet

```

**Comment by cristianoc** [comment]
We have some templates in the extension.
@chenglou would templates give that ^ behaviour?

**Comment by amiralies** [comment]
I don't think if those snippets now about type extensions. it should be done in analysis binary

**Comment by cristianoc** [comment]
For poly variants, see suggestions in https://github.com/rescript-lang/rescript-vscode/issues/283.
