### ISSUE TITLE
Rescript Formatter Doesn't Retain Trailing Comments

### ISSUE THREAD

**Issue by Mastermind497** [rescript-lang/rescript-vscode#257]
Typically, when formatting any array or tuple over multiple lines with comments trailing each line, the formatter doesn't merge the lines together. However, in the case of ReScript's formatter, the lines are merged together and so are the comments. The recording below compares the behavior of ReScript's formatter and JavaScript's Formatter to demonstrate what I mean. 

https://user-images.githubusercontent.com/39387439/119755274-bd35d080-be6f-11eb-8560-4a3f7e617400.mp4

**Comment by cristianoc** [comment]
This observation belongs to the syntax repository.
