### ISSUE TITLE
Better file renaming experience

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/rescript-vscode#258]
aside from #254 which adds support for renaming files on usage side, there are other options to improve file renaming experience.

- vscode/lsp supports a notification on file renaming. (client sends a `file-renamed` event to server) we can ask user to rename the module usages or rename usages directly.

- add a command (like the one we have for creating interface) to rename a module.

**Comment by cristianoc** [comment]
@amiralies do you think the current excellent functionality for renaming is lacking?
Even if one were to add a specific commend to rename a module, user would need to first imagine that such a command exists, and then discover it. Not sure about the overall value.

**Comment by amiralies** [comment]
Yeah i'm not sure about that too.
but currently there's no way to rename a module semantically from the module (file) itself.

The notification way may be more useful.
Scenario:
- User renames the file
- a popup asks the user if he wants to rename references to that file

but i'm not sure if it's possible to implement since the compiler tries to compile renamed module immediatly.
