### ISSUE TITLE
Feature request: autocomplete/annotations for annotations(e.g @bs.module etc)

### ISSUE THREAD

**Issue by BlueHotDog** [rescript-lang/rescript-vscode#26]
One of the hardest thing in ReScript is finding the right magic of annotations. i find myself always looking at other libs and examples. just because there's no logic to it and very little organization(it's all under bs namespace).
One thing that might REALLY help is allowing us to just type 
@bs. and have a list of all supported annotations with a helping text as to how to use them, when, and alternatives.

I think this is super important, i know for myself i would be able to write better bindings if some love was invested in this area, and good bindings are sorely missing in the rescript ecosystem.

Awesome v1 release!!! super pumped at the new direction ReScript is going!

**Comment by alexfedoseev** [comment]
`@bs` prefix is not a thing anymore, it’s kept for backward compat iirc

**Comment by BlueHotDog** [comment]
Right, my comments still stand though, no? how can the editor support building better bindings

**Comment by chenglou** [comment]
Might take some time. In the meantime, we've released a few snippets autocomplete support for `@bs.module` and such.
