### ISSUE TITLE
Is it possible to restart after a crash?

### ISSUE THREAD

**Issue by vasco3** [rescript-lang/rescript-vscode#266]
I've had situations when the extension crashes and I would like to be able to restart it without having to restart the whole VSCode. Is this currently possible?

**Comment by amiralies** [comment]
What do you mean by crash?
It shouldn't happen, if it's happening that's a bug.

(for more detail all the heavy lifting is done by one time process calls to another binary so i expect the server to do not die at all.)

**Comment by cristianoc** [comment]
@vasco it would be great to provide a repro for the crash.

**Comment by vasco3** [comment]
I don't remember what were the precise steps to repro. I was just coding in a .res file, made a bunch of changes with mistakes and when I saved the file the vscode extension through a warning that there was a compilation error, so I kept trying to fix it using my best guesses and after the third tried it crashed.

It has happened to me a couple of times since I upgraded to the latest v1.1.2

**Comment by cristianoc** [comment]
Feel free to reopen with a repro.

**Comment by cristianoc** [comment]
Meanwhile, I'll strengthen a couple of parts blindingly, but might be completely unrelated to what you have experienced.

If it happens again, it would be great to try to reproduce it and open a new issue.
