### ISSUE TITLE
Support for type definition

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/rescript-vscode#267]
it's like go to definition but for goes to type definition.
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_typeDefinition

https://user-images.githubusercontent.com/13261088/120936913-c8b2b280-c71f-11eb-936f-f278f00c800f.mp4

This is an example from vim with ocaml.

**Comment by cristianoc** [comment]
How is it triggered?

**Comment by amiralies** [comment]
Right click > Go to type definition
I think vs code doesn't have default hotkey for it
