### ISSUE TITLE
Outline is not showing

### ISSUE THREAD

**Issue by vasco3** [rescript-lang/rescript-vscode#27]
The outline is not working when I focus on a `.res` file. 
<img width="283" alt="image" src="https://user-images.githubusercontent.com/804301/100477656-3a62d180-30e9-11eb-9248-2e31be5c5aaa.png">

it does work when I use a `.re`

Without this, it is hard to navigate long files.

**Edit**
Another benefit of the Outline is that you can search symbols with `Cmd-shift-o` 

in this screenshot shows the spotlight to search symbols, although in Rescript files is currently not working.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/804301/101673275-3f177600-3a57-11eb-9c45-0e802d445e51.png">

**Comment by ryyppy** [comment]
Can you provide a preview of how the Reason outline looked like? Should be fairly simple to add that back.

**Comment by vasco3** [comment]
@ryyppy 
here is a simple reason file with only one react component
<img width="163" alt="image" src="https://user-images.githubusercontent.com/804301/101508997-95fa4e00-3978-11eb-8145-0017cce3c2a8.png">

**Comment by ryyppy** [comment]
Right.

_Just making some notes on the implementation details:_

- This is based on the DocumentSymbolProvider on the client side
- Probably requires the [Document Symbols Request capability](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol)
- Not sure if there's any wiring logic needed on the client side, or if it works out of the box when registering the right capabilities
- Regarding the data, the `editor-support` binary can deliver all the json data of a given module (i think when the line / col range is omitted). Just a matter of mapping over the data and send it to the client

**Comment by amiralies** [comment]
I think editor-support binary's dump command doesn't give toplevel of a given module.
When range is omitted it returns all hover information (type hints), maybe we need another command.
sth like `rescript-editor-support toplevel Foo.res`.
I'm not sure though, I may be wrong.

**Comment by cristianoc** [comment]
Done here: https://github.com/rescript-lang/rescript-vscode/pull/149

**Comment by chenglou** [comment]
Sorry, reopening this due to #200. But we'll get it done well soon.

**Comment by vasco3** [comment]
@chenglou I'm wondering how is this going?

**Comment by amiralies** [comment]
@vasco3 Will be available on next release

**Comment by zth** [comment]
Closing in favor of https://github.com/rescript-lang/rescript-vscode/issues/176, which adds a bit more detail/context.
