### ISSUE TITLE
Go to implementation

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/rescript-vscode#274]
Probably my biggest nitpick right now is that in React development, 90% of the time I actually want to navigate to a certain implementation code-point, instead of the interface definition.

It's correct that goto-definition should always go to an interface file if existent, so it would probably make a lot of sense to add a goto-implementation command that jumps to the implementation location instead.

LSP Spec: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_implementation

Having both commands would help greatly navigating React codebases with heavy interface file usage.

**Comment by cristianoc** [comment]
Technically, there's no issue implementing the feature.
Also, notice: the implementation is two hops away today: jump to interface then jump to implementation.

The philosophical question though: if you're not reading the interface files, why have them in the first place?

**Comment by ryyppy** [comment]
> The philosophical question though: if you're not reading the interface files, why have them in the first place?

In a React app, mostly for two reasons:
1) Hide exports that are not supposed to be exported (e.g. to satisfy fast-refresh conventions)
2) For compilation performance

If ReScript would have proper semantics for private / public scope, I wouldn't be using interface files I think.

**Comment by cristianoc** [comment]
> > The philosophical question though: if you're not reading the interface files, why have them in the first place?
> 
> In a React app, mostly for two reasons:
> 
> 1. Hide exports that are not supposed to be exported (e.g. to satisfy fast-refresh conventions)
> 2. For compilation performance
> 
> If ReScript would have proper semantics for private / public scope that allow optimized build times, I wouldn't be using interface files I think.

That's what I thought. Shows indirectly a need for reaching the same effect with different mechanisms.

**Comment by amiralies** [comment]
As a side note, It might be good to document behavior of each of these requests in ReScript.

**Comment by fhammerschmidt** [comment]
I second that. Almost never I want to jump to the interface definition, because I can hover for the type anyway.
Most often I want to look up (or change) the implementation, so personally I would prefer to jump to the `.res` directly.

**Comment by cristianoc** [comment]
See https://github.com/rescript-lang/rescript-vscode/pull/278 where direct jump to implementation is tested.

**Comment by cristianoc** [comment]
This is the current flow being considered for the jump-to-definition behaviour:

```rescript
// Foo.res
let x = 10
//  ^ when clicked, jump to Foo.resi
```

```rescript
// Foo.resi
let x : int
//  ^ when clicked, jump to Foo.res
```

```rescript
// User.res
Foo.x
//  ^ when clicked, jump to Foo.res
```

**Comment by cristianoc** [comment]
In master.
