### ISSUE TITLE
add syntax for string interpolation

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/rescript-vscode#275]
something like https://github.com/rescript-lang/vim-rescript/pull/44

**Comment by cristianoc** [comment]
Is this about syntax highlighting?

**Comment by amiralies** [comment]
Yes

**Comment by zth** [comment]
@amiralies is this still relevant, or was this fixed by the recent changes to highlighting?

**Comment by amiralies** [comment]
I'm not sure, as I vscode is not my main editor.

I think these cases should be covered.
```rescript
let var = `hello ${name} how you doin?`

let var2 = j`hello ${name} how you doin?`

let var3 = j`hello $name how you doin?`

let varInvalid = `hello $name how you doin?`

let expr = `2 + 2 is ${Int.toString(2 + 2)}`
```

**Comment by zth** [comment]
Right. Well, at least on my theme, it's not fully highlighted:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/1457626/155838995-78ef39b4-4d57-4f94-a03b-840486cecf5b.png">

**Comment by amiralies** [comment]
This is current vim behavior.
![image](https://user-images.githubusercontent.com/13261088/155842001-6ddd41bb-dae9-4c4d-8bf5-983f84e7919f.png)
looks like var3 and expr case should be addressed, this might be tricky to implement in textmate grammars tho .

**Comment by zth** [comment]
This is very close to being fixed in the semantic highlighting PR:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/1457626/159173580-256b8a58-505b-4071-8f98-805123deafc9.png">

Will see if we can fix the `$name` case there too, so we can close this.
