### ISSUE TITLE
Autocomplete polyvariants

### ISSUE THREAD

**Issue by zth** [rescript-lang/rescript-vscode#283]
This would really be a killer feature that'd bring the experience closer to what TS offers.

Basically, what I'm looking for is something like:

```
switch somePolyVariant {
  | #<list here of possible polyvariants>
}
```

Would this type of feature be easy or hard to implement? I understand there's multiple layers to this, like polyvariants with payloads, polyvariants with escaped names, open polyvariants etc. But just the "basic" case of autocompleting possible members of the polyvariant when they're known would be a big help.

**Comment by cristianoc** [comment]
This would indeed be pretty valuable.

Requires:
1 Triggering autocomplete on `#`.
2 Finding whether the context is a switch statement, and if it is, find the expression switched over.
3 Find the type of the expression.
4 From the type, extract the list of variants, and populate the list.

The main relevant part is 2. The rest is very similar to other cases of autocomplete.

**Comment by cristianoc** [comment]
Notice because of type inference, the type of the expression switched over might not help.

The same feature would provide more consistent value, without gotchas, on ordinary variants.

**Comment by cristianoc** [comment]
This issue can be merged with https://github.com/rescript-lang/rescript-vscode/issues/253.

**Comment by cristianoc** [comment]
Merged into #253.

**Comment by zth** [comment]
I think this would also be valuable for assignments. Especially in GraphQL, where enums are usually modelled as polyvariants. So, kind of:

```
mutate(~variables={status: #<list of possible enum values>
```

But, that particular example is tightly bound to completion on record fields when constructing them too I guess, which is mentioned in this issue: https://github.com/rescript-lang/rescript-vscode/issues/120

**Comment by cristianoc** [comment]
Not sure it's related to record fields. The example is, but the general feature does not seem to be.
The general feature being: autocomplete (poly) variants based on type context. The context can be used to infer the expected type, and the expected type used to complete the variant.
In that sense, the switch example is also just a special case. Where the switch provides a type context.

When no type context exists, such as `let x = #`, perhaps one could try with any variant in scope. Though that might be noisy/slow. To be seen.

**Comment by zth** [comment]
Ahh right, got it! Since polyvariants map to strings and ints so nicely now, I think there are a ton of usage of polyvariants for interop etc where a regular variant might actually be more "correct", but a polyvariant is used because it's zero cost. So for all of those cases, this type of feature would be very helpful.
