### ISSUE TITLE
Feature request: convert region Reason to ReScript

### ISSUE THREAD

**Issue by kswope** [rescript-lang/rescript-vscode#284]
The [playground](https://rescript-lang.org/try) has a hidden feature that converts reason to rescript.  (the settings, toggle RE/RES).  Whatever is doing this, I'm assuming it could be incorporated into this plugin. 

Highlight a Region
Command Pallet -> Convert highlighted Reason to ReScript
Command Pallet -> Convert highlighted Rescript to Reason

I would find this VERY helpful as I'm learning rescript and often have to look at reason resources.  It could also be very useful for cut-n-paste programming

**Comment by zth** [comment]
Unfortunatel,y this is not something we're going to actively pursue given we're phasing out Reason syntax and have a very limited workforce working on the editor tooling.
