### ISSUE TITLE
Formatting deletes commented (jsx) code if comment makes the parent empty

### ISSUE THREAD

**Issue by wfendler** [rescript-lang/rescript-vscode#288]
I just noticed while commenting out some JSX that it would delete the comment when it left the parent element without any elements inside of it.

### To recreate:

Comment out all of the contents of an element
```
<div>
// <div />
</div>
```

Format the code and it will remove all of the commented code:
```
<div />
```

### VS Code:
Version: 1.59.0-insider (Universal)
Commit: b805d2e94937976bb17d0439f57fcd3a9d423c31
Date: 2021-07-20T05:12:13.059Z (1 wk ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0

(I'm not sure exactly what this extension is using for formatting, so apologies if this is the wrong repo! I'd be happy to report it in the formatting project if that's more appropriate.)

**Comment by cristianoc** [comment]
Thanks. Would you report it in the ReScript syntax repository?
There might be an issue there already.

**Comment by amiralies** [comment]
There's an open issue on syntax repo https://github.com/rescript-lang/syntax/issues/403
