### ISSUE TITLE
Show circular dependency errors don't show in VSCode

### ISSUE THREAD

**Issue by pixelpapercraft** [rescript-lang/rescript-vscode#289]
It looks like "dependency cycle" errors from the compiler don't show in VSCode.

It would be great to have these appear in the Problems tab, if possible.

**Comment by cristianoc** [comment]
There's an issue for this in the rescript-compiler repo: this is not picked up as the error message is not printed indented.

**Comment by pixelpapercraft** [comment]
Thanks @cristianoc, I'll close this issue then.

**Comment by cristianoc** [comment]
Related: https://github.com/rescript-lang/rescript-compiler/issues/5229
