### ISSUE TITLE
[neovim / native LSP] server quit when self cycle

### ISSUE THREAD

**Issue by kiuKisas** [rescript-lang/rescript-vscode#296]
For example:
```
// Awesome.res

type test = | Foo | Bar

let t = Awesome.Foo
```
We got this error:
```
FAILED: Awesome has a self cycle
```
Legit.

In neovim and native LSP, the server crash and quit.
It happen to me during refactoring code, I expected to see the error, not that the server crash and quit

**Comment by amiralies** [comment]
possible duplicate of #212

**Comment by cristianoc** [comment]
https://github.com/rescript-lang/rescript-vscode/pull/344
