### ISSUE TITLE
[neovim/ native LSP] add sypport for symbol (symbols-outilne.nvim)

### ISSUE THREAD

**Issue by kiuKisas** [rescript-lang/rescript-vscode#298]
https://github.com/simrat39/symbols-outline.nvim

**Comment by amiralies** [comment]
we actually got this feature but since there's a bug in vscode which results in stale output inside vscode's output pane it is disabled.
see #176 

if you build server from source you can enable it manually for your usage. take a look at #272 if you want to.

**Comment by kiuKisas** [comment]
Hum.. do we have other issue in neovim/LSP due to vscode incompatibility ? Maybe it worth releasing a "vim/neovim" version alongside the vscode one.

**Comment by amiralies** [comment]
Maybe we should do that. I use neovim too.
The goal of this project is to have a stable/reliable vscode extension. the fact that it uses lsp is implementation details.

**Comment by kiuKisas** [comment]
Yeay, ideally we should have one common repo and 2 distinct repos for each editors, to let them live on their own

**Comment by amiralies** [comment]
It works with native lsb document symbosl i'm not sure how is the exact behavior with the mentioned plugin.

**Comment by zth** [comment]
Got it. Well, since a lot of recent work has been done on the document symbol functionality, I'll close this one. Feel free to reopen or post a new issue if things still aren't working, and there's things we can do on the extension side to fix that.
