### ISSUE TITLE
poly variant duplication in tooltips?

### ISSUE THREAD

**Issue by somebody1234** [rescript-lang/rescript-vscode#302]
```res
module A = {
  type cond<'a> = [< #str(string) | #int(int)] as 'a
  type t<'a> = {
    a: option<int>,
    b: option<cond<'a>>
  }
  let fun = (a, b) => { a: a, b: b }
}

let init: A.t<[#int(int)]> = A.fun(Some(1), Some(#int(1)))
```

the type of `A.fun` shows as
```res
(
  option<int>,
  option<
    A.cond<
      [<
        | #str(string) & (string) & (string) & (string)
        | #int(int) & (int) & (int) & (int)
      ],
    >,
  >,
) => A.t<
  [<
    | #str(string) & (string) & (string) & (string)
    | #int(int) & (int) & (int) & (int)
  ],
>
```

the number of repetitions appears to be proportional to the number of parameters in the function

**Comment by zth** [comment]
I cannot reproduce this with a recent master extension version. @somebody1234 could you try and reproduce by installing a recent build from CI, and reopen if it still happens for you?

**Comment by somebody1234** [comment]
![image](https://user-images.githubusercontent.com/4046547/166947316-bc698da2-f6f1-4a43-b4c7-611aa04be862.png)
idk... ran via debug -> client + server. disabled the extension, i still get the same issue...
using default bsconfig.json from template

**Comment by somebody1234** [comment]
couldn't find artifacts from CI; this should be built using latest master.
also doesn't look like i can reopen, weirdly enough...

**Comment by somebody1234** [comment]
(@zth)

**Comment by zth** [comment]
@somebody1234 hey! Try this one https://github.com/rescript-lang/rescript-vscode/suites/6408092662/artifacts/233483614

...but I hovered the wrong thing, so I can actually reproduce now that I try again.

Unsure what the problem might be here, we'll probably need the expertise of @cristianoc to figure that out. I'm reopening the issue, but we have a lot going on right now so we'll unfortunately probably need to wait a bit with looking into this.
