### ISSUE TITLE
Be able to run the compiler after each modification

### ISSUE THREAD

**Issue by carere** [rescript-lang/rescript-vscode#303]
Hello, first of all, thx a lot for this amazing extension 😄

Actually, it seems that Vscode compile the rescript code after each save.
I would like to be able to modify this behavior, in order to tell vscode to compile after each modification, event if the current working file is not save.
Do you think, that it can be possible ?? Since the compilation time is blazingly fast 😃 

Best regards

**Comment by cristianoc** [comment]
You can turn on auto save in vscode.

**Comment by carere** [comment]
Thx for your advice 😄
For those who wants to be able, to **auto save** and **format** on save.
You should use the extension [Run on Save](https://marketplace.visualstudio.com/items?itemName=pucelle.run-on-save) (since vscode do not handle this combination actually)
I close this issue.
