### ISSUE TITLE
Regularly publish releases to Open VSX

### ISSUE THREAD

**Issue by dcalhoun** [rescript-lang/rescript-vscode#31]
Would the maintainers be open to regularly publishing releases to [Open VSX](https://open-vsx.org/) so that VSCode compatible editors [like Onivim2](https://github.com/onivim/oni2/issues/2779#issuecomment-735734573) may leverage the latest versions of this extension?

Thanks for the great extension!

**Comment by chenglou** [comment]
Hello! Not planned currently as the current publishing flow is already pretty tedious and we can't start supporting alternative editors outside of those we're already taking care of (and have to constantly dogfood to ensure quality). However, every release is published at https://github.com/rescript-lang/rescript-vscode/releases too, already. Sorry about that and hopefully this will do for now

**Comment by dcalhoun** [comment]
@chenglou Understandable. Thank you for the response. Yes, the ZIP file attached to each release is helpful.
