### ISSUE TITLE
Possible bug with type inference

### ISSUE THREAD

**Issue by mellson** [rescript-lang/rescript-vscode#310]
I asked [a question](https://forum.rescript-lang.org/t/trying-to-understand-type-inference-and-stumbling-on-this-formik-example/2593) at the ReScript forum. The answers suggested that there could be a bug in the extension, hence this issue.

I have created [a repo](https://github.com/mellson/rescript-type-inference-example) containing the example here. Please have a look in [FormTest.res](https://github.com/mellson/rescript-type-inference-example/blob/main/src/FormTest.res) to see the type inference I'm wondering about.

Can you confirm that it's a bug, or is it because I'm missing to open the other module or something else?

[Recreating the example in the ReScript playground](https://rescript-lang.org/try?code=LYewJgrgNgpgBAMRAJ2ASwNZwLxwN4BQccALgJ4AO8AZiuhgJIB2FEJAPAOQCGAfDvjRM0JNNygA1cRBgBnAFxweAGjggmAZQgAjdCUU8c-CMJIBfAkVKUadTAHk2rDj3648AN2lyD3C1fIqOFpUTAAJEBAMLj4BEPpmZxi3fniHJzZky2IAAVBIWAAKACI0jGKASisYAA8SGGQmcTgIWRhFMoio5IFi1pgkUPKCf1gSOCERMUlvWQFCYmKm4BhixWLi5StisDkAY2Q0ClF1NbgNrdGYcfUtXREBLygZOex+AClZADooEABzQpPF5VAhjYJ2LC4Qb0L79QoLCamaZSZ4+RFTcQol5bYi3HR6RR4+4kS4ggD0ZLgEQ8DSEfzUNOQcCBcjgfzQNLmK1IAAt4LUqHt6mBrFRVNo2HAeSBGXSGQ1wUMviy5gArVrjdmcuDcniWMEquIQ5WzAhAA) shows that the type is inferred.

Thanks for considering this.

**Comment by zth** [comment]
Closing this as a "duplicate" (well, not really) of https://github.com/rescript-lang/rescript-vscode/issues/310. Or rather, if I understand correctly, https://github.com/rescript-lang/rescript-vscode/issues/310 covers this as well. Feel free to reopen if I'm wrong.

**Comment by mellson** [comment]
> Closing this as a "duplicate" (well, not really) of https://github.com/rescript-lang/rescript-vscode/issues/310. Or rather, if I understand correctly, https://github.com/rescript-lang/rescript-vscode/issues/310 covers this as well. Feel free to reopen if I'm wrong.

Happy to hear this is resolved in another issue. But it looks like the reference is back to this issue, so not sure what the reference is.
