### ISSUE TITLE
JSX props autocomplete stops working after polymorphic variant is declared

### ISSUE THREAD

**Issue by Lomand** [rescript-lang/rescript-vscode#313]
Greetings,
Autocomplete works as expected if `Ctrl+Space` is pressed before a prop with polymorphic variant is declared,

![image](https://user-images.githubusercontent.com/8079999/142774391-e696afc1-e524-450a-a537-657251069d4c.png)

and breaks if `Ctrl+Space` is pressed after it.

![image](https://user-images.githubusercontent.com/8079999/142774403-930a8fc6-5332-4be8-a225-16c6588569a2.png)

Repo with example:
https://github.com/Lomand/rescript-broken-autocomplete-jsx
Just add `align=#Center` in the `Demo.res` to reproduce the issue.

**Comment by cristianoc** [comment]
@Lomand indeed that case is not covered by autocompletion currently, while `align={#Center}` is.

**Comment by Lomand** [comment]
Awesome, thanks a lot, Cristiano! 🙏
