### ISSUE TITLE
Hovering on JSX props does not show their type declaration

### ISSUE THREAD

**Issue by Lomand** [rescript-lang/rescript-vscode#314]
Hi,

Hovering on props does not work as expected, it does not show the type of the prop, but rather defenition of `React` module

![image](https://user-images.githubusercontent.com/8079999/142774434-937ebf9f-8360-4eae-ad6e-49949a6d92fa.png)

In this example the definition should be `option<[#Center | #Inherit | #Justify | #Left | #Right]>`.  Same thing with hover on the prop value:

![image](https://user-images.githubusercontent.com/8079999/142774457-15722ad2-5345-4168-a6a4-7b8b32d24a6b.png)

Hovering on component shows relevant type declaration just fine:

![image](https://user-images.githubusercontent.com/8079999/142774427-4e204028-920c-4d65-ae0d-c292d21d2f73.png)

Repo with example:
https://github.com/Lomand/rescript-broken-autocomplete-jsx

**Comment by cristianoc** [comment]
This is inherited from the fact that JSX under the hood is a labelled function call, which also has this behaviour:
```
let z = ahaa(~one=3, ~two=34)
```

There's no hovering on `one` and `two`.
The underlying issue is that the abstract syntax tree of the compiler internally does not keep positions for named arguments used in applications.

**Comment by zth** [comment]
Is this something that could potentially be fixed in ReScript at the AST level when ReScript moves away from having to conform to the OCaml AST?

**Comment by cristianoc** [comment]
Definitely a dedicated AST could help. It could also have direct JSX support instead of relying on an encoding.

**Comment by zth** [comment]
Oh, that's pretty neat!

**Comment by zth** [comment]
This might actually have a solution soon. cc @cristianoc

**Comment by cristianoc** [comment]
Indeed it's now pretty close. If you autocomplete the prop, completion gives you the type.

**Comment by cristianoc** [comment]
In fact this suggested an entirely new feature which leverages autocomplete to hover on unsaved code.
It just so happens that JSX props are not in the typed AST and can be treated just as if they were unsaved code.
