### ISSUE TITLE
Contribute schema for bsconfig.json

### ISSUE THREAD

**Issue by kfish610** [rescript-lang/rescript-vscode#32]
VS Code provides a [contribution point for json schemas](https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation). Using this would avoid the need for a `$schema` property in the bsconfig.json (which currently is a bit broken, since the schema doesn't allow for a `$schema` property.....). All that would be necessary is the addition of
```json
"jsonValidation": [
  {
    "fileMatch": ".jshintrc",
    "url": "https://json.schemastore.org/jshintrc"
  }
]
```
to the contributions.

**Comment by chenglou** [comment]
Thanks! Added. Though it only works on vscode.

It's kinda sad that `"$$schema"` isn't recognized while being a pseudo-standard. I think we're gonna keep that key for various starter templates so that other editors can read from it maybe. Can be removed manually easily anyway.
