### ISSUE TITLE
ocaml lsp error on opening the project in vscode.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [rescript-lang/rescript-vscode#320]
Hi,
The following error occurs on opening the codebase in vscode.
```
/Users/acsreedharreddy/.opam/4.06.1/lib/ocaml/compiler-libs/types.cmi
seems to be compiled with OCaml 4.06.
But this instance of Merlin handles OCaml 4.12.
```

Tried to get help from ocaml discord as well.
https://discord.com/channels/436568060288172042/436568060288172044/906816953748979733
```
They have .merlin file with fixed 4.06, I’d talk to maintainers
```
![image](https://user-images.githubusercontent.com/16081083/143511714-02d9e132-f477-4dc7-908b-2573482c957b.png)

**Comment by cristianoc** [comment]
Stale .merlin file. Fixed in master now.
