### ISSUE TITLE
Code completion behaviour differs for exported records

### ISSUE THREAD

**Issue by kevinbarabash** [rescript-lang/rescript-vscode#321]
Given the following record in point.res:
```
type point = {
    x : int,
    y : int,
}
let p = {x : 5, y : 10}
```
I see the following completions when typing `p.` in point.res:
<img width="476" alt="Screen Shot 2021-11-27 at 1 57 21 PM" src="https://user-images.githubusercontent.com/1044413/143718908-c22a5dcc-3b1c-4bf4-be59-02534cce74cd.png">

But when I got to use `p` in another file, it doesn't should any completions.  When I force the completions to show up it shows me a list of all identifiers VSCode knows about:
<img width="554" alt="Screen Shot 2021-11-27 at 1 59 30 PM" src="https://user-images.githubusercontent.com/1044413/143718938-b6c344ee-2366-4dfe-9369-ba73268a3f4b.png">

Opening `Point` has no effect on this behaviour.

**Comment by Lomand** [comment]
This issue is not exclusive to records, objects suffer from it too.

**Comment by kevinbarabash** [comment]
It looks like the server calls out to bsc.exe.  I'll try to see if I can repro the issue with bsc.exe itself.

**Comment by cristianoc** [comment]
Thanks for the report.
Indeed, currently `Point.p.` is transformed to `p.` by `determineCompletion` and the results are not found.
Some internal logic is missing to handle these cases.
