### ISSUE TITLE
Broken autocomplete of local variables if `@react.component` decorator is present

### ISSUE THREAD

**Issue by Lomand** [rescript-lang/rescript-vscode#323]
Concider the following example:

![image](https://user-images.githubusercontent.com/8079999/143776250-0f2cda2b-0fd2-4c41-99de-27f360e4fe1c.png)

If I'll try to autocomplete `myAmazingFunction`, everything will work just as expected (well, besides the fact that it would be prefferable to have local file variables on the top of the list, not the bottom, but I digress):

![image](https://user-images.githubusercontent.com/8079999/143776288-b14d06a7-50b7-4ffb-a932-d9592ad0687e.png)

However, autocomplete can be broken just by adding two new lines before the `@react.component` decorator 

![image](https://user-images.githubusercontent.com/8079999/143776311-4aed29ff-e28f-4353-8e19-5967dc193a82.png)

Or by creating another variable before the `@react.component` decorator:

![image](https://user-images.githubusercontent.com/8079999/143776324-692107c1-cc9a-43b4-b710-9b5a4a4def91.png)

If the  `@react.component` decorator is removed, autocomplete works with any amount of empty lines or variables:

![image](https://user-images.githubusercontent.com/8079999/143776340-353b19d6-2643-485c-94ba-26199b34c07c.png)

Repo with the example:

https://github.com/Lomand/rescript-broken-autocomplete-jsx/tree/master/src/decorator-breaks-autocomplete

**Comment by cristianoc** [comment]
Thank you @Lomand 
This should be fixed in https://github.com/rescript-lang/rescript-vscode/pull/327
