### ISSUE TITLE
Please allow to restart the server

### ISSUE THREAD

**Issue by SofianeDjellouli** [rescript-lang/rescript-vscode#328]
When the server crashes, I have to reload the window to restart it. Can it be possible to restart it from the command palet, like the TS server for instance?

**Comment by jmagaram** [comment]
Please see...

https://forum.rescript-lang.org/t/vs-code-extension-stops-working-anyone-else/2397

The extension seems SO VERY close to being really great. But it fails regularly - maybe once a day - for unknown reasons on my little project. It is really hard to get it going again. Some magic of build with watcher, clean, "kill" process, restart VS Code, etc. will eventually get it going again - don't necessarily need any changes to my code - but I can't figure out a reliable set of steps that will quickly get me up and running. The best option is to make the extension never fail. Second best would be some built-in diagnostics or something in the output window so I could tell you why it is failing and you could fix it. But until that day I'd really like an easy way to get it working again. A command palette command for "Restart ReScript Extension" or something similar would be useful. It would do the clean, fix stale files, whatever. Overall I just want to see some more reliability.

**Comment by Lomand** [comment]
Those random restarts are due to
```
>> Fatal error: Longident.flat
Fatal error: exception Misc.Fatal_error
```
This issue should go away once https://github.com/rescript-lang/syntax/pull/449 is merged.

**Comment by srikanthkyatham** [comment]
Hi @zth 

I would be happy help in this issue. Let me know how and where to proceed.

**Comment by zth** [comment]
@srikanthkyatham excellent! Some quick background:

The language server is created here: 
https://github.com/rescript-lang/rescript-vscode/blob/master/client/src/extension.ts#L102-L107
...and then started here: 
https://github.com/rescript-lang/rescript-vscode/blob/master/client/src/extension.ts#L217-L218

Notice that the result of `start` is pushed to `subscriptions` - that's important so VSCode can clean up appropriately as the extension is deactivated/activated.

Essentially, you'll need to:
1. Add and expose a new command that restarts the client. There are many examples of commands in the repo you can look at.
2. Ensure that the old client is properly shut down and cleaned up when restarting. A tip is to look for any dangling processes (`ps aux` or similar) that would indicate that the server is still running.

Feel free to open a WIP PR early if you'd like!

**Comment by cristianoc** [comment]
There's also some global state that presumably needs to be cleared. E.g. `stupidFileContentCache` and `projectsFiles` and `codeActionsFromDiagnostics`.

**Comment by zth** [comment]
@cristianoc I think that's handled automatically. I think starting and stopping the server via the client will kill the entire process, and all the state with it.

**Comment by jmagaram** [comment]
I was just in a situation where the extension stopped working. So I did a "rescript build -w" and see "Stale file detected :  C:\Users\justi\source\repos\shortcuts\.bsb.lock". The automatic transpilation did not restart. Eventually had to restart VS Code to get it working again. If you need any diagnostics when this happens let me know.

**Comment by srikanthkyatham** [comment]
Hi @zth 

I will start checking and create a WIP pr asap.

**Comment by zth** [comment]
Here's an inspirational commit from another extension: https://github.com/facebook/relay/commit/df2aec7278dfba9a0a0f241652408da63adbb56d

**Comment by zth** [comment]
Done in https://github.com/rescript-lang/rescript-vscode/pull/423
