### ISSUE TITLE
format on %raw would fill much blank lines

### ISSUE THREAD

**Issue by Mng12345** [rescript-lang/rescript-vscode#333]
vscode settings.json
```json
"[rescript]": {
    "editor.defaultFormatter": "chenglou92.rescript-vscode"
  },
```
when saving files which contains %raw embeded javascript, there would be much blank lines putted in the %raw block in vscode
before:
```rescript
let parsePageUrls: unit => array<string> = %raw(`
  function () {
    const divs = document.getElementsByClassName("title")
    const urls = []
    for (let i=0; i<divs.length; i++) {
      const url = divs[i].getElementsByTagName("a")[0].href
      urls.push(url)
      console.log("push url: ", url)
    }
    return urls
  }
`)
```
after save file:
```rescript
let parsePageUrls: unit => array<string> = %raw(` 

  function () {

    const divs = document.getElementsByClassName("title")

    const urls = []

    for (let i=0; i<divs.length; i++) { 

      const url = divs[i].getElementsByTagName("a")[0].href

      urls.push(url)

      console.log("push url: ", url)

    }

    return urls

  }

`)

```
The blank lines will become more when saving again.
```rescript
let parsePageUrls: unit => array<string> = %raw(` 



  function () {



    const divs = document.getElementsByClassName("title")



    const urls = []



    for (let i=0; i<divs.length; i++) { 



      const url = divs[i].getElementsByTagName("a")[0].href



      urls.push(url)



      console.log("push url: ", url)



    }



    return urls



  }



`)
```

**Comment by Mng12345** [comment]
Nobody here??

**Comment by amiralies** [comment]
Can not reproduce this.
Which OS do you use?

is this happening using cli too?
```shell
./node_modules/.bin/rescript format <file.res>
```

**Comment by Mng12345** [comment]
> Can not reproduce this. Which OS do you use?
> 
> is this happening using cli too?
> 
> ```shell
> ./node_modules/.bin/rescript format <file.res>
> ```

I am using windows10 x64, This is my settings.json in vscode
```json
"editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[rescript]": {
    "editor.defaultFormatter": "chenglou92.rescript-vscode1"
  },
```
The format result is normal when formatting by cli,

**Comment by amiralies** [comment]
is this possible to test with rescript extension in isolation ? or disable other formatter plugins like prettier.
and is this happening with normal formatting too (without format on save)

**Comment by Mng12345** [comment]
> is this possible to test with rescript extension in isolation ? or disable other formatter plugins like prettier. and is this happening with normal formatting too (without format on save)

Normal format(with command line) is ok, The blank lines is getting more whether or not to disable prettier plugin.

**Comment by a-c-sreedhar-reddy** [comment]
Hi @Mng12345 Can you try removing all the other extensions from your vscode and just installing the rescript-vscode extension.

**Comment by ryyppy** [comment]
@Mng12345 can you try switching to Unix line endings in your files? There's a setting in the VSCode footer (`LF` | `CLRF`)

![image](https://user-images.githubusercontent.com/1121889/150368604-2967fd69-7795-4d8c-9e7b-b1744f122886.png)

Might be an encoding issue

**Comment by ryyppy** [comment]
Okay cool! I think there were several discussions on how to solve that issue, but I think there was no proper way to do it. So I guess the recommendation is to switch to LF (something that should be done anyway in a multi-OS environment).

Will close this.
