### ISSUE TITLE
pipe autocomplete does not give suggestions

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [rescript-lang/rescript-vscode#335]
```rescript
module Test = {
  type t = {name: int}
  let add = (a: t) => a.name + 1
}
let a: Test.t = {name: 4}
// a->
```
auto-complete does not suggest `Test.add` in the above example.

When I replace 
```ml
 | {SharedTypes.item = Value typ} :: _ -> (
 ```
with 
```ml
|  _ :: {SharedTypes.item = Value typ} :: _ -> (
```
 [here](https://github.com/rescript-lang/rescript-vscode/blob/master/analysis/src/NewCompletions.ml#L1047)

This works, but i could not reason out why.

**Comment by cristianoc** [comment]
This is an interesting case.
While features such as jump to definition use the results of type checking (assuming the file is compiled), autocomplete cannot do that, but needs to understand the code being edited and make use of type checking results from the previous compilation.
In this case, there are two `a`'s: the labeled argument to `add`, and the value declared at the end. This could be resolved in general by checking the id associated to `a` by the type checker, except we don't have such information. So in this case, autocomplete just picks the wrong `a` (the labeled arg), and no autocomplete suggestions are given.

Without replicating the entire scope checking mechanism of the compiler, there's no way to get completely accurate results. But, it should be possible to come up with a decent heuristic that gets it right most of the times.
In this case, such a heuristic could be: pick the latest `a` above the current cursor position. This would also take care of the other issue https://github.com/rescript-lang/rescript-vscode/issues/336 which has analogous underlying cause.
