### ISSUE TITLE
Use rescript-vscode on reason .re files

### ISSUE THREAD

**Issue by leoparis89** [rescript-lang/rescript-vscode#337]
We have a project with .re files that don't migrate nicely to .res but compile with rescript.

Is there a way this plugin could apply to `.re` files since rescript compiles them ?
That way we wouldn't need to use reason-vscode and bsb 9 anymore.

Many thanks.

**Comment by amiralies** [comment]
This plugin/language server doesn't support reason files.
though it may work with a bit of hacking. I have an old branch which was working fine on reason files but didn't use that recently.
you can take a look https://github.com/amiralies/rescript-vscode/tree/reason-support

**Comment by amiralies** [comment]
I've updated that branch with latest changes. should be working fine but don't rely on that too much.
note that I updated the server may require a tiny bit of changes to work with rescript (i.e activation events ...)

**Comment by leoparis89** [comment]
> I've updated that branch with latest changes. should be working fine but don't rely on that too much. note that I updated the server may require a tiny bit of changes to work with rescript (i.e activation events ...)

Many thanks.

**Comment by amiralies** [comment]
> I've updated that branch with latest changes. should be working fine but don't rely on that too much. note that I updated the server, client may require a tiny bit of changes to work with rescript (i.e activation events ...)

**Comment by leoparis89** [comment]
> This plugin/language server doesn't support reason files. though it may work with a bit of hacking. I have an old branch which was working fine on reason files but didn't use that recently. you can take a look https://github.com/amiralies/rescript-vscode/tree/reason-support

Are there any plans for support ? IMO it would make sense since the rescript compiler works on .re files.

I'll be glad to look at what's missing on the client side on your branch.

**Comment by fhammerschmidt** [comment]
The reason it still supports Reason is to not break any existing users, but ReScript's goal clearly is to get rid of it.
If you want to compile .re files in the long term, please use the fork "[Melange](https://github.com/melange-re/melange)".

**Comment by zth** [comment]
Supporting `.re` files in addition to `.res` would be quite cumbersome unfortunately. While the compiler works on both, the extension has its own analysis tooling that does not work on `.re` syntax, and that would be non-trivial to adjust to support `.re`.

Closing this as no action will be taken on this.
