### ISSUE TITLE
Odoc parser does not render comments properly

### ISSUE THREAD

**Issue by Lomand** [rescript-lang/rescript-vscode#338]
In the current state of affairs only the first line of the comment is treated as such, the rest is rendered as is
![image](https://user-images.githubusercontent.com/8079999/149793211-bcd4ed23-077d-450d-9917-7f484de3bbb6.png)
All grammar is ignored, even in the first line.

Compare this to working odoc parser in `ocaml-platform`
![image](https://user-images.githubusercontent.com/8079999/149793230-6dd9cde8-5c29-455e-aeb6-5861f8561056.png)

Demo:
https://github.com/Lomand/rescript-broken-autocomplete-jsx/blob/master/src/Demo.res

**Comment by cristianoc** [comment]
Odoc comments are not supported. Doc comments are getting gradually converted to markdown:
https://github.com/rescript-lang/rescript-compiler/blob/2f0201f471df94dc4650966132c011b97ff09a1f/jscomp/others/belt_List.mli#L241

**Comment by Lomand** [comment]
Ok, looks like anyone who wants to generate docs from the source code is out of luck. Such a shame

**Comment by ryyppy** [comment]
Yeah the docgen stuff I wrote extracts all the markdown comments into a JSON file that can actually be processed outside of OCaml tooling... a huge issue we originally had with odoc back then.

One thing that's still missing though is semantic `/**/` parsing, so we currently rely on `@ocaml.doc` as our comment marker still.

**Comment by amiralies** [comment]
I think parsing `/** */` should be easy if we agree on its syntax.
i.e
`/** {content} */` -> multiline comment and annotate with `ocaml.doc` (or whatever).
`/* {content} */` -> multiline comment

**Comment by zth** [comment]
Closing this as I believe this either isn't an issue anymore, or is going to be fixed whenever core modules are converted to res + markdown.
