### ISSUE TITLE
ocaml-lsp has dropped support for .merlin files

### ISSUE THREAD

**Issue by b0o** [rescript-lang/rescript-vscode#339]
This issue is related to the development of the rescript-vscode `/analysis` sub-project, not the end use of this plugin.

Vendored modules are not being picked up by the latest version of [ocamllsp](https://github.com/ocaml/ocaml-lsp), leading the LSP to display "Unbound module" errors e.g. where the `Json` module is used in `FindFiles.ml`.

From [this changelog entry](https://github.com/ocaml/ocaml-lsp/blob/master/CHANGES.md#breaking-change) for ocamllsp:

> Breaking Change: ocamllsp drops support for .merlin files, and as a consequence no longer depends on dot-merlin-reader. (#523)

Downgrading to ocamllsp version 1.8.3 works around this issue, but it would be nice to have support for the latest version of ocamllsp.

**Comment by cristianoc** [comment]
Thanks @b0o.
This should take care of it: https://github.com/rescript-lang/rescript-vscode/pull/340

**Comment by jboillot** [comment]
Hello,
It may be interesting for future readers to add that [ocamllsp](https://github.com/ocaml/ocaml-lsp) has added an option `--fallback-read-dot-merlin` if you're not using [dune](https://github.com/ocaml/dune/).
This way you don't have to downgrade.

**Comment by cristianoc** [comment]
The project has been using dune for a while now.
