### ISSUE TITLE
Errors don't change on editing the file

### ISSUE THREAD

**Issue by phenax** [rescript-lang/rescript-vscode#34]
Errors only show up when loading vscode for the first time. Consequent editing of the file doesn't seem to update the diagnostic info.

### On opening vscode
![part-2020_12_01_16_47_55](https://user-images.githubusercontent.com/11407672/100734251-5f12be00-33f5-11eb-90fc-bebf858604f7.jpg)

### On fixing the issue (expecting it to show the next error which is unused params)
![part-2020_12_01_16_48_12](https://user-images.githubusercontent.com/11407672/100734245-5de19100-33f5-11eb-8870-5c8f0e8eebd3.jpg)

**Comment by alexfedoseev** [comment]
Do you have running `bsb -w` process?

**Comment by phenax** [comment]
Yes. `bsb` from my node_modules is running

**Comment by phenax** [comment]
I had the same problem with `vim-rescript` (which uses `rescript-vscode` internally). In both those cases I get a prompt to start build after which I see a `bsb` process running in the background.

Version: `1.0.0`

**Comment by chenglou** [comment]
Hello! Which bs-platform version?

**Comment by phenax** [comment]
bs-platform: `8.3.3`

**Comment by chenglou** [comment]
Can you show me your `lib/bs/.compiler.log`?

**Comment by phenax** [comment]
`lib/bs/.compiler.log`
```
#Start(1607195542405)
#Done(1607195542441)
```

**Comment by chenglou** [comment]
Thanks. And I'm assuming you can repro this deterministically?

**Comment by phenax** [comment]
I creates a blank (bs-platform + gentype) project with 1 rescript file and the plugin worked. But then I created a new angular project with `ng new testproj` and the issue showed up again. It seems to be running into issues with angular or maybe typescript dependencies.

**Comment by chenglou** [comment]
Not sure what you mean; our plugin doesn't work on angular files?

**Comment by phenax** [comment]
I meant rescript file inside an angular project

**Comment by phenax** [comment]
I've pushed a fresh angular project with one rescript file [`src/File.res`](https://github.com/phenax/bug-repro-rescript-vscode/blob/master/src/File.res) that I could reproduce the issue with. The repo is at [phenax/bug-repro-rescript-vscode](https://github.com/phenax/bug-repro-rescript-vscode)

---

### Screenshots from vscode

**Valid error**
![part-2020_12_06_14_38_17](https://user-images.githubusercontent.com/11407672/101276244-783eb480-37d1-11eb-93b4-63f053b54ba1.jpg)

**After fixing the issue**
![part-2020_12_06_14_38_34](https://user-images.githubusercontent.com/11407672/101276243-770d8780-37d1-11eb-9b4e-478d49b76757.jpg)

---

### Screenshots from nvim (`rescript-lang/vim-rescript` with coc)

**Valid error**
![part-2020_12_06_14_36_39](https://user-images.githubusercontent.com/11407672/101276235-61985d80-37d1-11eb-9841-8924b06059bf.jpg)

**After fixing the issue**
![part-2020_12_06_14_36_58](https://user-images.githubusercontent.com/11407672/101276234-60673080-37d1-11eb-91f1-2fa91594acc4.jpg)

**Comment by marcoemrich** [comment]
I have the same issue with plain Rescript (created with --theme node). Compiler log does show the error but VSCode does not.

![image](https://user-images.githubusercontent.com/447570/101585774-bfe75b00-39e0-11eb-9e6c-38681c005dd8.png)

**Comment by woeps** [comment]
@marcoemrich did you save the file?
I think I read somewhere the language server only works on saved files.

**Comment by marcoemrich** [comment]
Yes - I use "save on focus lost", but also did save manually

**Comment by marcoemrich** [comment]
and have configured "format on save" - this was in the readme

**Comment by marcoemrich** [comment]
interestingly - the formatting part works!

**Comment by zprayz** [comment]
I can confirm that the initial error shows up in the Problem tab if the file has errors when you open it but not subsequent errors. Nor does the initial error clear out when you fix the problem. The lib/bs/.compiler.log is correct at every step--it's just not being reflected via the rescripts-vscode extension. Everything works correctly if I just use bsb -w in a terminal window.

**Comment by IwanKaramazow** [comment]
@phenax I just pulled your project locally and can't reproduce:
1. git clone your example project
2. npm install
3. `bsb -make-world -w` in one terminal
4. `ng serve` in another terminal

The errors in VSCode seem to update? Did you follow any other steps?

**Comment by phenax** [comment]
@IwanKaramazow. Pretty much the same steps except for the last one. I cloned the repo, ran `npm install` then opened the project directly. It prompted me to start the build which I clicked on.

**Comment by IwanKaramazow** [comment]
Ok, what OS are you using? Did you open the project in the root of the folder?

**Comment by IwanKaramazow** [comment]
@phenax thanks, just as a debug point running `bsb -w` in the terminal before you open vscode gives the same thing?

**Comment by phenax** [comment]
Yes. It behaves the same way.

**Comment by IwanKaramazow** [comment]
@phenax We released a new version (1.0.4) that contains a fix. Can you confirm that this solves your issue?

**Comment by mbergal** [comment]
I am not sure if this is the same problem, but Problems window get out-of-sync with compiler from time to time. VS Code restart helps.

Here what Problems window shows for me:

![image](https://user-images.githubusercontent.com/167835/108911624-1da53f80-75ed-11eb-9b07-5017316fa80a.png)

This is what terminal output is:

![image](https://user-images.githubusercontent.com/167835/108911713-3dd4fe80-75ed-11eb-8e65-05d465759c52.png)


and this is what compiler log is:

```
#Start(1614116066457)

  Warning number 21
  /home/misha/projects/productionmason/web/packages/shared/tests/Exn_Test.res:24:7-9
  
  22 ┆     }
  23 ┆   `)
  24 ┆   c()
  25 ┆   None
  26 ┆ } catch {
  
  this statement never returns (or has an unsound type.)
  

  We've found a bug for you!
  /home/misha/projects/productionmason/web/packages/shared/src/commands/OrderCommands.res:26:3
  
  24 ┆ let a = t.apolloClient.mutate(~mutation=module(OrderCommands_Graphql.C
       reateConversation), ())
  25 ┆ 
  26 ┆ a->AsyncResult.mapOk(x => {
  27 ┆   Ok(x.data.insert_conversations_one->Option.getExn->OrderCommands_Gra
       phql.Conversation.toDomain)
  28 ┆ })
  
  This has type:
    Js.Promise.t<
  Belt.Result.t<
    ApolloClient__Core_ApolloClient.FetchResult.t__ok<
      Schema.OrderCommands_Graphql.CreateConversation.t,
    >,
    ApolloClient__Core_ApolloClient.ApolloError.t,
  >,
>
      (defined as
      Js_promise.t<
  Belt.Result.t<
    ApolloClient__Core_ApolloClient.FetchResult.t__ok<
      Schema.OrderCommands_Graphql.CreateConversation.t,
    >,
    ApolloClient__Core_ApolloClient.ApolloError.t,
  >,
>)
  Somewhere wanted:
    CommonBase.AsyncResult.t<'a, [> #Exn(exn)] as 'b> (defined as
      Promise.t<CommonBase.AsyncResult.result<'a, 'b>>)
  
#Done(1614116066469)
```

**Comment by cristianoc** [comment]
This was a while ago. Please reopen if still valid.
