### ISSUE TITLE
Attribute autocompletion shows 4 "@bs" entries on top

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#347]
When I type "@", I get the following autocompletion

<img width="784" alt="Bildschirmfoto 2022-01-21 um 08 17 22" src="https://user-images.githubusercontent.com/591384/150483329-bf777c73-3fea-400e-8cd1-cf8b6591d6e1.png">

Can we get rid of the 4 `@bs` entries on top?

The remaining entries all make sense, but it would be nice if they had a help text. :-)

**Comment by cristianoc** [comment]
Looks like these are 2 separate mechanisms. The ones on top are templates. The following ones are coming from autocompletion.

**Comment by cknitt** [comment]
Ah, right, yes, these are snippets, they are just named weirdly.

Looks also weird in the "Insert Snippet" function:

<img width="139" alt="Bildschirmfoto 2022-01-21 um 08 42 11" src="https://user-images.githubusercontent.com/591384/150486537-6ead983d-1336-4527-b43a-b85d90cb8f1f.png">

**Comment by cknitt** [comment]
I guess the first two should be `@val` and the other two `@module` now that we don't have `@bs` anymore.

**Comment by cknitt** [comment]
For comparison, this is what the Insert Snippet menu looks like for TypeScript:

<img width="202" alt="Bildschirmfoto 2022-01-21 um 08 47 45" src="https://user-images.githubusercontent.com/591384/150487187-0756ebc8-4532-4591-b3a2-6bc5e6fe4cbf.png">

**Comment by fhammerschmidt** [comment]
I would remove them, as Cheng mentioned here: https://github.com/rescript-lang/rescript-vscode/issues/125
The other snippets could use a "description" field and the prefix should probably always be a one-line string instead of a string array.

**Comment by cristianoc** [comment]
Indeed, it's just about removing the `@bs` part, while they still show up with `external`.
