### ISSUE TITLE
Coloring Is Broken When Multiline String Is Present

### ISSUE THREAD

**Issue by FilipKittnar** [rescript-lang/rescript-vscode#348]
Hello,
the coloring of the code seems to be broken after a multiline string.

![image](https://user-images.githubusercontent.com/61822423/150489327-e7e10113-694e-4fab-94e4-30f970ffe52a.png)

**Comment by cristianoc** [comment]
Same as this issue? https://github.com/rescript-lang/rescript-vscode/issues/345

**Comment by FilipKittnar** [comment]
Yes, seems like the same thing, sorry.

**Comment by liby** [comment]
@cristianoc
![image](https://user-images.githubusercontent.com/38807139/150809330-ed54befe-288d-47cf-af7e-79241b9b73c1.png)

The latest version of the code doesn't look like `"end": "(?<!\\\\)`",`.

**Comment by cristianoc** [comment]
@liby it should be fixed in master, and will go in an upcoming bug fix release. Unless there's some additional issue being reported here.

**Comment by JasoonS** [comment]
Glad it is fixed @cristianoc  I see that was merged in 6 days ago and the latest release was also 6 days ago. Did it not make the release (I'm using v1.20 and seeing the described issue)

**Comment by FilipKittnar** [comment]
I can confirm it is fixed in version 1.2.1. We can close this.
