### ISSUE TITLE
Syntax Highlighting messes up with generic optional parameters

### ISSUE THREAD

**Issue by kfish610** [rescript-lang/rescript-vscode#35]
Taking an example from [the documentation](https://rescript-lang.org/docs/manual/latest/function#signatures-and-type-annotations), this snippet:
```res
let drawCircle: (~color: color, ~radius: int=?, unit) => unit =
  (~color: color, ~radius: option<int>=?, ()) => {
    setColor(color)
    switch radius {
    | None => startAt(1, 1)
    | Some(r_) => startAt(r_, r_)
    }
  }
```
highlights `>=` as an operator, rather than as a closing bracket for the generic and an equal sign. This happens in VS Code as well:
![image](https://user-images.githubusercontent.com/20480949/100787016-da5d7b00-33c7-11eb-9255-92571ce10111.png)
This is particularly problematic for those who use ligature fonts, as ligatures depend on proper coloring to break up things that *look* like ligatures but really aren't.
Is the tokenizer/grammar that colors this defined here, or in another repository?

**Comment by chenglou** [comment]
Submitted to VSCode as https://github.com/microsoft/vscode/issues/111945

**Comment by jmagaram** [comment]
I'm running into this problem too. Optional parameters look like either `>=` or another weird symbol - see image.

![image](https://user-images.githubusercontent.com/14130251/137644958-5174cbdd-5244-4fc8-9454-a319cbec8d36.png)
