### ISSUE TITLE
Plugin crashes on hover

### ISSUE THREAD

**Issue by Lomand** [rescript-lang/rescript-vscode#350]
[Repo with example](https://github.com/Lomand/rescript-broken-autocomplete-jsx/blob/master/src/LspCrash.res)
Hover over `Map.add` to crash the server with 

```
>> Fatal error: Longident.flat
Fatal error: exception Misc.Fatal_error
```

Seems this issue will be resolved once https://github.com/rescript-lang/syntax/pull/449 is merged.

**Comment by cristianoc** [comment]
@Lomand thanks for the report!
This has indeed the same cause as https://github.com/rescript-lang/syntax/pull/449, however it crashes in the extension's codebase, rather than while calling the formatter.

**Comment by Lomand** [comment]
Thanks a lot for the fix, Cristiano!
Really glad to hear that this issue could be resolved without relying on external repos. 🎉
