### ISSUE TITLE
Plugin not working on macOS Monterey

### ISSUE THREAD

**Issue by DCKT** [rescript-lang/rescript-vscode#353]
Hello there,

I've upgraded my macOS version to Monterey (12.1) and since then I haven't any intellisense from ReScript files. I only have the syntax coloration.
Am I the only one with this case ? Maybe I need to update some low level library ? 

I tried the Insiders version from scratch with 1.2.0 version and also the version from master but no clue 🤔 

Any help would be granted  😄  
Thanks !

**Comment by a-c-sreedhar-reddy** [comment]
> Am I the only one with this case ?

![image](https://user-images.githubusercontent.com/16081083/151220006-df6ce320-4c40-4100-8917-6ae47efa7a6e.png)
It works for me.

**Comment by fhammerschmidt** [comment]
I had the same problem after upgrading to 1.2.0. No autocomplete or hover info at all. Not sure what fixed it, but I also tried uninstalling and reinstalling and even packaging the VSIX myself (of the current master). 

Days later, I reinstalled the plugin again and it somehow resolved. @ryyppy suggested, that the analysis binary may not have been installed correctly.

**Comment by DCKT** [comment]
It came back with the `1.2.1` release 😄

**Comment by ryyppy** [comment]
> It came back with the 1.2.1 release 😄

I hope this means "it works"

**Comment by DCKT** [comment]
Yes it is 👍
