### ISSUE TITLE
Improve error message when reanalyze is not available

### ISSUE THREAD

**Issue by zth** [rescript-lang/rescript-vscode#355]
(I'm leaving this here as a reminder to myself to fix this)

Currently, when `reanalyze` isn't installed locally in the current project, and when we've never ran `reanalyze` before through `npx`, we show an error message. But that error message could be a lot better and clearer. Currently it just forwards the error message produced by npx.

**Comment by fhammerschmidt** [comment]
I guess this is obsolete now.
