### ISSUE TITLE
How to get type popup for object outside of the file which the object is defined?

### ISSUE THREAD

**Issue by Mng12345** [rescript-lang/rescript-vscode#360]
I am using rescript-vscode with version 1.2.1, i found that the type popup for object is functional in the file which the object is defined, but not in other file.

This is ok
![image](https://user-images.githubusercontent.com/21278900/152955149-8cffc2df-5492-4049-be73-804bb8a8c2d0.png)

This file can not get type popup
![image](https://user-images.githubusercontent.com/21278900/152955195-25163390-2435-43fb-ad04-1ca3d1e24331.png)

**Comment by cristianoc** [comment]
Unclear why this happens, to be investigated.

At a temp workaround, you can assign the value to a variable:
```let obj = Demo.object```
Then autocomplete on
```obj.[""]```
