### ISSUE TITLE
Highlighting of modules on current master is same color as values

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/rescript-vscode#375]
Yesterday I packaged the current master (at commit [287b4aa](https://github.com/rescript-lang/rescript-vscode/commit/287b4aa21127942bb1a29602cca8c338a77f68f2)) into a VSIX and tested it. 

Now it looks like this:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/18074327/160648960-c20222c6-2791-4817-b8fd-8342e7f5e705.png">

While the first iteration (not sure which commit, but it was the [VSIX from the forum post](https://github.com/zth/rescript-vscode-beta-vsix/raw/main/syntax-highlighting/rescript-vscode-1.2.2-syntax-highlighting.vsix)) looked like this:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/18074327/160649373-f79c9a04-9c71-4159-9399-eaf538922ac0.png">

VSCode version: 1.65.2
Theme: Dark+

**Comment by fhammerschmidt** [comment]
That may be the case, I only bumped the version and copied the binaries from [this action](https://github.com/rescript-lang/rescript-vscode/actions/runs/2027072304) to  `server/analysis_binaries` and did a `vsce package`.

**Comment by zth** [comment]
Yeah I see. That does look like it should work. But, you can test whether it's really broken or something just went wrong with packaging by building the analysis binary locally, and then running the extension in debug mode in VSCode. If things still don't work then, but hovers etc work, then something's broken for real.

**Comment by fhammerschmidt** [comment]
Fortunately, in Debug mode and built locally it works.

**Comment by zth** [comment]
Thanks for the elaborate testing, happy it worked out in the end! I guess no bug is always better 😅
