### ISSUE TITLE
Formatting error in a Yarn monorepo 

### ISSUE THREAD

**Issue by alenkis** [rescript-lang/rescript-vscode#376]
Hello! 👋 

I'm having an issue trying to format `.res` file:

```
Cannot find a nearby bsc.exe in rescript or bs-platform. It's needed for formatting.

Source: rescript-vscode (Extension)
```

I am working in one of the packages of a Yarn monorepo, and I have the following `bsconfig.json`:

```
{
  "name": "name",
  "sources": [
    {
      "dir": "source/rescript",
      "subdirs": true
    }
  ],
  "package-specs": [
    {
      "module": "es6",
      "in-source": true
    }
  ],
  "suffix": ".bs.js",
  "bs-dependencies": []
}
```

`package.json` has the following dev deps:

```
    "bs-platform": "^9.0.2",
    "rescript": "^9.1.4",
```

Am I missing some step in configuring ReScript to work inside an existing project? Any help is appreciated, thanks!!

**Comment by alenkis** [comment]
hey @fhammerschmidt !

> You have bs-platform and rescript in your dependencies. Do you know that those are the same packages, just with different version numbers? It should be safe to remove the old bs-platform.

That's a good point, I've actually started with `rescript` and only added `bs-platform` when trying to make this work. I've since removed `bs-platform` and there is no change.

> The extension recursively checks or it until it reaches it or the root of your filesystem.

This seems to be a problem because `yarn v2` caches and zips the dependencies. 
I tried using `npm` and the formatter was able to find `bsc.exe`.

Does `rescript-vscode` support usage with `yarn v2`?

**Comment by fhammerschmidt** [comment]
Not really, since it relies on the existence of a `node_modules` folder. 

You would need to add 
```yml 
nodeLinker: 'node-modules'
```
to your `.yarnrc.yml`, or (probably better) follow this yarn recipe: https://yarnpkg.com/getting-started/recipes/#hybrid-pnp--node_modules-mono-repo

**Comment by alenkis** [comment]
https://github.com/reason-seoul/yarn-plugin-rescript worked nicely, thanks @fhammerschmidt!
