### ISSUE TITLE
Keep regex-based highlighting where semantic highlighting is not available

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/rescript-vscode#380]
I don't understand why the grammar needed to be cleaned up. 

1. VSCode has a lot of places where code is displayed without semantic highlighting, like in the working tree view or in hover snippets.
2. Many themes just don't enable support for it [(default is disabled)](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-coloring-in-color-themes).
3. Sometimes you get a flash, which is pretty obvious with lots of module names which get painted from one color to the other. While we cannot prevent that, it would be less noticeable that way.
4. No bsconfig means no highlighting now. While formatting still works.

Obviously, it's not correct in many cases, but let's please find some middle ground here.
It would already help a ton just to put the module parts back in.

**Comment by zth** [comment]
Yes, we agree, this is a valid point. Let's tackle this in two ways:

1. Restore a subset of what was previously in the grammar, to clean up the "worst offenders". Ensure that anything colored by the grammar directly will get the same color as semantic highlighting would give it (so we avoid flashes where we can).
2. Implemented the `range` method for semantic highlighting, and see whether that helps coloring in hovers etc. Some background: we've currently only implemented the method for semantically highlighting a full file. But, there's an additional method, `range`, that allows for coloring independent chunks of code. We'll implement that and see whether that helps with some of the lack of coloring too.

@fhammerschmidt would you be interested in taking a stab at point 1? We can go back and forth, testing together, etc.

**Comment by fhammerschmidt** [comment]
Yeah, will try to submit a (draft) PR tonight.

I think the most important parts got lost in these two commits, so in the first iteration I will just restore the module/JSX parts:

- https://github.com/rescript-lang/rescript-vscode/commit/0e56b5e9f061ef06921e5fbde64590fecf77ec9b
- https://github.com/rescript-lang/rescript-vscode/commit/dd9c37566522df7ca137f82798c489518309c312

**Comment by zth** [comment]
Closing this as all relevant changes has landed in master. Thanks @fhammerschmidt !
