### ISSUE TITLE
Create interface file does not work with React.memo

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#382]
@cristianoc Thanks for your great work on getting the "Create interface file" feature to work for React components, too! 👍

I just tested it with the VSIX from the lastest master build and found that components memoized with `React.memo` do not work correctly yet.

For example,

```rescript
@react.component
let make = (~someValue as _: bool) => React.null

let make = React.memo(make)
```

results in

```rescript
let make: React.component<{"someValue": bool}>
```

instead of

```rescript
@react.component
let make: (~someValue: bool) => React.element
```

**Comment by cristianoc** [comment]
Thanks!
Done in master.
