### ISSUE TITLE
More continuous releases

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/rescript-vscode#387]
Ideally a release can happen on each master branch commit, I'm aware this can't happen for big changes like recent highlighting/code actions etc. but I think we can do releases more often than what we do atm.

For more context, I was always using the language server from master branch with neovim, doing rescript almost on daily basis and I had an stable experience.

**Comment by zth** [comment]
I'm personally also interested in at least a way to more easily use a bleeding edge/experimental version of the extension, so we can get more testing. But I'm unsure how to do this in practice.

**Comment by amiralies** [comment]
Maybe we can use https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions for this usecase

**Comment by fhammerschmidt** [comment]
Yup. have a look at the [rust-analyzer repo](https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/release.yaml#L108) for inspiration.

**Comment by zth** [comment]
Ohhh, that looks great, we should definitively do that! @cristianoc do you have opinions on this?

**Comment by fhammerschmidt** [comment]
Woops, i referenced the wrong line. I meant [this one](https://github.com/rust-lang/rust-analyzer/blob/master/.github/workflows/release.yaml#L255).

I would tackle this one, but first we would need to decide on when this (pre-)release action would trigger.

1. After successful master build
2. On push to a (pre-)release branch
3. Nightly/weekly
4. Other suggestions?

**Comment by zth** [comment]
I think 2 is a good option. We'll make sure to publish as often as it makes sense/is stable enough for testing. What do you think?

**Comment by fhammerschmidt** [comment]
So if we even automatically release via a `release` branch at some point, we would have both a `release` and `pre-release` branch beside the master branch?

**Comment by cknitt** [comment]
I fully agree with @fhammerschmidt: We should avoid manual steps for pre-releases, even if an automatic process slightly increases the chance that the user downloads a broken version. In practice, I have been working with the `master` builds for some time now, and did not run into any problems.

**Comment by zth** [comment]
Sounds good to me, I think master can be considered fairly stable. We also typically do quite extensive testing of feature branches, so it should remain fairly stable too.

@cristianoc @ryyppy what do you think?

**Comment by cristianoc** [comment]
Having a model which is completely automatic would be great.

**Comment by zth** [comment]
Is this something you @fhammerschmidt for example would be up for working on? Is it meaningful/possible to work on it without repo/publishing rights, etc?

**Comment by fhammerschmidt** [comment]
Just created #399 but somebody with more rights needs to finish it.

**Comment by aspeddro** [comment]
> Just created #399 but somebody with more rights needs to finish it.

Will this create a release with a pinned tag? like in rust_analyzer `nightly`?

**Comment by fhammerschmidt** [comment]
> Will this create a release with a pinned tag? like in rust_analyzer `nightly`?
That would mean that every merge to master will be its own tag?

But I guess having a pre-release also available from the GitHub releases page like rust-analyzer would be nice for people that don't use the marketplace.

Also we don't have a versioning scheme suitable for vscode pre releases yet. Rust analyzer pre releases are always a minor version higher than the last main ones, so they are always on top of the releases page and updates in VSCode don't move them back to the main release channel.

**Comment by aspeddro** [comment]
> That would mean that every merge to master will be its own tag?

Yes.

> But I guess having a pre-release also available from the GitHub releases page like rust-analyzer would be nice for people that don't use the marketplace.

I wanted to test the server in vim/neovim, having a pin tag allows you to automate this.

https://github.com/rescript-lang/rescript-vscode#use-with-other-editors

**Comment by aspeddro** [comment]
I created a step to create a nightly release when merged on master.

See https://github.com/aspeddro/rescript-vscode/releases

**Comment by fhammerschmidt** [comment]
Let's define the whole release and versioning process. Here is how I would imagine it on the example of the current version **1.2.1**. Pre-releases will always have an odd version minor (e.g. 1.**3**.2), normal releases an even one (e.g. 1.**2**.2). That way the pre-release will always be higher than the release so that VSCode does not install main releases for users that are on the pre-release channel.

```mermaid
flowchart TD
A(Current version - 1.2.1)
A-->B[pull request gets merged into master branch]
B-->C[build analysis binaries]

subgraph ci [ ]
subgraph textNode1 [ci.yml]
style textNode1 fill:none,stroke:none
end
C-->D[increment version package.json - 1.2.2]
D-->E[vsce package with bumped minor - 1.3.2]
D-->F[vsce prepublish with bumped minor - 1.3.2]
E-->G[add packaged version to releases page - Latest master]
end

F & G --> H{New release due?}
H -->|No| I[Done]
H -->|Yes| J[Update CHANGELOG.md - 1.2.2]
J --> K[push to protected release branch]
K --> L[build or download analysis binaries]

subgraph release [ ]
subgraph textNode2 [release.yml]
style textNode2 fill:none,stroke:none
end
L --> M[vsce package - 1.2.2]
L --> N[vsce publish - 1.2.2]
M --> O[add packaged version to releases page - 1.2.2]
end

N & O --> I
```

If somebody wants to extend the diagram, [it's here](https://gist.github.com/fhammerschmidt/0bbfabd8cd737fb9eb9e65543f3bc64f).

**Comment by fhammerschmidt** [comment]
This is implemented now so we can close it.
@zth
