### ISSUE TITLE
Tailwind CSS IntelliSense compatibility

### ISSUE THREAD

**Issue by dcalhoun** [rescript-lang/rescript-vscode#39]
After migrating a few Reason files to the ReScript syntax, I noticed that the [Tailwind CSS IntelliSense](https://tailwindcss.com/docs/intellisense) (e.g. autocomplete, linting, hover previews, syntax highlighting) provided via [the Tailwind CSS VS Code extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) does not appear to work for `res` files. I'm not certain as to whether this would be an issue with `rescript-vscode` or `vscode-tailwindcss`, but I figured I'd open an issue here to hopefully identify the issue origin. Thanks!

| Reason Syntax | ReScript Syntax |
| --- | --- |
| <img width="1904" alt="reason-autocomplete-available" src="https://user-images.githubusercontent.com/438664/101284742-2aad5200-37a7-11eb-8ff1-c61dd20cfd49.png"> | <img width="1904" alt="rescript-autocomplete-missing" src="https://user-images.githubusercontent.com/438664/101284748-33058d00-37a7-11eb-8a1b-dd494a51057f.png"> |

**Comment by amiralies** [comment]
Can you report this in tailwind vscode extension repo?
this is not related to rescript-vscode, they need to add support for rescript.

p.s. the change should be trivial maybe somewhere in [this file](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/71c254964b523a184a87b0393c90d57393d24339/packages/tailwindcss-intellisense/src/lib/languages.ts)?

**Comment by dcalhoun** [comment]
@amiralies absolutely. I wasn't sure where the issue may reside. Thank you for the guidance.
