### ISSUE TITLE
Renaming a .res or .resi to another file extension crashes ReScript language server

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#392]
I am running one of the latest master builds of the VS Code extension.

When I rename some A.res or A.resi to another file extension, e.g., A.resx, the ReScript language server crashes. This even occurs when A.res/A.resi is empty.

**Comment by cristianoc** [comment]
@cknitt would you give more details on how to repro the crash?

**Comment by cknitt** [comment]
@cristianoc In the project I am currently working on, just creating an empty A.res and renaming it to A.resx (by selecting it in the VS Code file tree, pressing enter, modifying the name and pressing enter again) reproduces the crash.

Is it not reproducible for you this way? Then maybe it has something to do with my project setup (yarn workspaces or whatever).

**Comment by cknitt** [comment]
It does not seem to be dependent on my project setup. I can even reproduce this as described with a new project created from scratch following https://rescript-lang.org/docs/manual/latest/installation#new-project.

**Comment by cristianoc** [comment]
Turns out vscode calls rescript operations such as `semanticTokens` and `documentSymbol` on non-rescript file `A.resx`, and does not even send `openedFile` on `A.resx`.

**Comment by cristianoc** [comment]
For what it's worth. Another way to crash the extension: open a non-rescript file, force the editor to consider it ReScript, force an autocomplete.

**Comment by cristianoc** [comment]
This resurfaced after merging the actions branch.
