### ISSUE TITLE
weird type variables displayed

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/rescript-vscode#40]
<img width="535" alt="Screenshot 2020-12-07 at 12 33 15 PM" src="https://user-images.githubusercontent.com/747051/101309944-8ef41280-3888-11eb-90fd-4f6aa983f559.png">
see the signature for `fold_left2`

**Comment by cristianoc** [comment]
Fixed in https://github.com/rescript-lang/rescript-editor-support/pull/39.
