### ISSUE TITLE
Feature request: use `rescript` binary from ancestor `node_modules`

### ISSUE THREAD

**Issue by ellbur** [rescript-lang/rescript-vscode#412]
Thanks for creating this tool. I am really enjoying ReScript so far.

I am programming ReScript on my tiny chromebook, and replicating the large `rescript` node package in each package is taking up a lot of space. 

To address this, I installed `rescript` in `~/node_modules`. Building and running works fine! The binaries are detected and the output `.js` files go in the right place.

Only problem is, the language server does not find `node_modules/.bin/rescript`. My suggestion is to change [`findNodeBuildOfProjectRoot`](https://github.com/rescript-lang/rescript-vscode/blob/ce210510d3450b2a80a465947f95f7742d8ad7a3/server/src/utils.ts#L74) to look up the directory stack:

```typescript
export let findNodeBuildOfProjectRoot = (
  projectRootPath: p.DocumentUri
): null | { buildPath: p.DocumentUri; isReScript: boolean } => {
  while (true) {
    let rescriptNodePath = path.join(projectRootPath, c.rescriptNodePartialPath);
    let bsbNodePath = path.join(projectRootPath, c.bsbNodePartialPath);

    if (fs.existsSync(rescriptNodePath)) {
      return { buildPath: rescriptNodePath, isReScript: true };
    } else if (fs.existsSync(bsbNodePath)) {
      return { buildPath: bsbNodePath, isReScript: false };
    } else {
      let parent = path.dirname(projectRootPath);
      if (fs.existsSync(parent) && parent != projectRootPath) {
        projectRootPath = parent;
      }
      else {
        return null;
      }
    }
  }
};
```

I tried making this change and it seems to work fine (with [vim-rescript](https://github.com/rescript-lang/vim-rescript)).

**Comment by ah-yu** [comment]
Same problem when trying to use rescript in `deno` project. I installed `rescript` package globally but the extension can't find it, so I have to install the `rescript` package in the local directory. 

I think it would be better to provide an option to let users customize their path of the `rescript` module. Something like `rescript.path: "~/node_modules/rescript"`

**Comment by zth** [comment]
Thanks for the report! We also think this might be a good candidate for being configurable in the extension. We're going to work on the basic infra needed for configuration (it's slightly complicated because of the language client<->server relationship), but once that's done, this sounds like a good thing to build.

**Comment by zth** [comment]
Update: The foundations needed for this are now ready in the repo. This would be a good first issue for someone interested in contributing (ping @carere).

https://github.com/rescript-lang/rescript-vscode/commit/8d6000dd3caa7cd8cb9df30878582c5e2303606d this commit adds a setting to the extension. As long as the setting is nested under the scope `rescript.settings` it'll be automatically forwarded and synced to the server. You'll just need to update the `extensionConfiguration` interface to include the relevant type for the new setting. 

Should be fairly straight forward, I hope.
