### ISSUE TITLE
Lost auto complete in switch expression with version 1.3.0

### ISSUE THREAD

**Issue by Mng12345** [rescript-lang/rescript-vscode#414]
environment：win10 x64 vscode rescript-vscode1.3.0
![mnggiflab-output-compressed (8)](https://user-images.githubusercontent.com/21278900/167975592-7291b9c1-6a7a-41ab-a528-c2187b789ee4.gif)
As the screen recording gif(recording by [this website](https://www.mnggiflab.com/product/screen-recorder)), auto complete is losting after `|` operator in switch expression.

**Comment by cristianoc** [comment]
@Mng12345 thanks a lot for reporting this. Spot on!

The PR mentioned above solves it, as well as documents, by way of experiment, all the steps from investigating the test cases to coming to a solution.

**Comment by Mng12345** [comment]
Thanks!
