### ISSUE TITLE
Autocomplete insertion doesn't utilise a local open 

### ISSUE THREAD

**Issue by Kingdutch** [rescript-lang/rescript-vscode#420]
When autocompleting in a function that already has a local open, the module name is still prefixed even though it's not required. 

In contrast when the open happens at the top of the file the module name is correctly omitted.

https://user-images.githubusercontent.com/327697/168224860-1924aeed-72b8-4adf-8d25-63d2e78f2918.mov

**Comment by cristianoc** [comment]
Good catch!
