### ISSUE TITLE
Interface generation does not work if @inline is present

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/rescript-vscode#425]
E.g. if I have a file `Example.res`:

```rescript
@inline
let gray = "#f0f0f0"
```

the create-interface command yields me this broken `Example.resi` file:

```rescript
@inline
let gray = "#f0f0f0"
```

expected:

```rescript
@inline
let gray: string
```

**Comment by a-c-sreedhar-reddy** [comment]
This is because of https://github.com/rescript-lang/rescript-vscode/blob/master/analysis/src/CreateInterface.ml#L162-L170 where it copies the lines from source file.

**Comment by cristianoc** [comment]
> This is because of https://github.com/rescript-lang/rescript-vscode/blob/master/analysis/src/CreateInterface.ml#L162-L170 where it copies the lines from source file.
> 
> 
> 
> 

And if it did not copy the source, it would actually look worse. Some garbled string with the marshaled encoding of the internal data used to represent inlined things.

If one wants to support this case, a little more work is required to recognize what's going on and emit the desired thing.

In a nutshell, a compiler ppx transforms these kinds of things, and one needs to un-compile them based on a mix of information: the typed ast and the original source.

**Comment by cristianoc** [comment]
Perhaps this could be a good issue for a new contributor starting from the info already provided in this discussion.
