### ISSUE TITLE
Support Linux ARM

### ISSUE THREAD

**Issue by ellbur** [rescript-lang/rescript-vscode#426]
Everything builds and runs fine on Linux ARM. The only issue is the server does not use the correct analysis binary.

[A possible fix](https://github.com/ellbur/rescript-vscode/commit/737a6a47df317eeca7f5a815507d6936b6415baa).

**Comment by cristianoc** [comment]
@ellbur would you create a PR?
As written the link is problematic with e.g. M1 mac where it would look for `bsc.exe` in a path that does not exist after a normal ReScript installation. Will need a little tweaking.

**Comment by cristianoc** [comment]
Btw are you building the compiler yourself?

**Comment by ellbur** [comment]
@cristianoc Ah you're right, I should not have changed the paths for `bsc`, since that wasn't affected. I'll fix that.

By the compiler, do you mean `bsc.exe`/`rescript.exe`? My understanding was that this was always built when installing the `rescript` NPM package. So yes, I am building that myself.

I also needed to build `rescript-editor-analysis.exe` myself since an ARM build is not provided in the posted CI builds.

**Comment by ellbur** [comment]
@cristianoc OK pull request created: https://github.com/rescript-lang/rescript-vscode/pull/428

**Comment by cristianoc** [comment]
`bsc` is used when formatting. Can you check that formatting works for you? I assume your bsc.exe is inside `linux` and the npm installation puts the executable there, if formatting woks.

**Comment by cristianoc** [comment]
A separate question is how `rescript-editor-analysis.exe` ends up in `linux-arm64`. What is creating that directory?

**Comment by ellbur** [comment]
@cristianoc I suppose to be really useful, the [CI](https://github.com/rescript-lang/rescript-vscode/blob/master/.github/workflows/ci.yml) needs to be modified to include a `linux-arm64` build.

Unfortunately I'm not so familiar with GitHub actions but I'll play around and see if I can add an arm64 build.
