### ISSUE TITLE
Multiline comments get expanded from formatter

### ISSUE THREAD

**Issue by hellos3b** [rescript-lang/rescript-vscode#427]
When writing a Multiline comment with `/* This Syntax */`, each time you hit save the auto formatter doubles the spacing inside the comment block

GIF of me press CTRL+S
![comment-format](https://user-images.githubusercontent.com/4062679/169660688-f41652fa-e93f-48fd-86dc-f902bdc18091.gif)

Windows 11
Vscode `1.67.2`
Rescript extension `1.3.0`

**Comment by cristianoc** [comment]
I vaguely remember this coming up before, perhaps in a forum post.

**Comment by zth** [comment]
@cristianoc I believe you're thinking of this issue: https://github.com/rescript-lang/rescript-vscode/issues/333

@hellos3b can you try the solution described in that issue? If that works, we should add it to the readme.
