### ISSUE TITLE
Very long error messages are cut off

### ISSUE THREAD

**Issue by tom-sherman** [rescript-lang/rescript-vscode#44]
I ran into a very annoying error message with ReasonReact where I had a typo in a prop (`onKeypress` instead of `onKeyPress`). The most valuable part of the error message is at the bottom and I couldn't see it.

Repro: https://rescript-lang.org/try?code=LYewJgrgNgpgBAIQgF2SAdnAvHA3gKDjgAEAnGAQwGNkA6KkYABwxnWULlmTmAoGt4OABQA-BhHYAuOAEt2ASmwA+PJyIAeAEYo0mDAGkYATybkAzuay5hAfSVZVwhQF9VuYOYDmAWmUAlShpac2RSeS8XOA0Aeh1UDGVOF3wUoA

```rescript
module Button = {
  @react.component
  let make = (~count: int) => {
    <button onKeypress={(_) => ()}> {msg->React.string} </button>
  }
}
```

![image](https://user-images.githubusercontent.com/9257001/101414601-49facb00-38de-11eb-9508-021ea64c58f8.png)

This problem has several facets:

1. The extension doesn't show the full message
2. This error message is massive, but I understand why the full tuple might be helpful in some situations
3. The most helpful piece of information is on the last line

I'm primarily a TS dev so I'm used to reading error messages from bottom to top, but I don't think it makes for the best experience - especially when compared to Rust for example.

**Comment by chenglou** [comment]
Thanks. I'll cc @rickyvetter on this just to raise awareness. Seems that we don't really have a way to solve this for now because the error message that handles the type error and the explanation are in two different paths.

**Comment by chenglou** [comment]
Ah wait, the last important message cutting off is a real issue. I'll fix that. However the lengthiness of the message and the order of the report won't be solvable for now I think...
