### ISSUE TITLE
Vscode editor takes a long time to save files.

### ISSUE THREAD

**Issue by Mng12345** [rescript-lang/rescript-vscode#441]
environment: win10 x64 vscode-rescript 1.3.0
![image](https://user-images.githubusercontent.com/21278900/171110468-cc2f3ca4-5e79-4f57-b6db-79d62bac0386.png)
This problem constantly exists recently. Don’t know why.

-------
It becomes to normal after i deleted some target files generated by rust.

**Comment by Mng12345** [comment]
I think it is not very necessary to pay attention to this problem, i add res file to the rust source directory just because wantting to reuse the old project(it is pointless). Putting the pure rescript files in resript source directory is a good choice. This issue may helps others who have done the same things like me.

**Comment by cristianoc** [comment]
Was the time spent formatting rust files?
