### ISSUE TITLE
Explore reporting syntax errors as you type.

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/rescript-vscode#448]
The parser is vendored in the extension and is always available. Does not need to wait for type information.
Explore reporting syntax errors for unsaved code.

This should be fast enough to feel responsive, but not so fast that it gets in the way and produce noise while you type.

**Comment by zth** [comment]
For anyone interested in this, it's a good idea to get a feel for what for example TS and Rust does in this regard. We don't have to copy them, but it'll probably be a good guide for what direction to take.

**Comment by aspeddro** [comment]
Is it possible to also catch type errors with parser?

**Comment by cristianoc** [comment]
No when the parer runs, the type checker has not run yet.

**Comment by zth** [comment]
This is done in https://github.com/rescript-lang/rescript-vscode/pull/457
