### ISSUE TITLE
Deprecation messages don't show in intellisense popup

### ISSUE THREAD

**Issue by tom-sherman** [rescript-lang/rescript-vscode#45]
![image](https://user-images.githubusercontent.com/9257001/101484254-3dfc2100-3951-11eb-806f-763e361e6f43.png)

This function is tagged with

```
[@@deprecated "This function will soon be deprecated. Please, use `List.keepWithIndex` instead."]
```

However this message doesn't show in the popup.

**Comment by chenglou** [comment]
cc @cristianoc @ryyppy might need some collabs for this

**Comment by cristianoc** [comment]
Support for autocomplete and hover here: https://github.com/rescript-lang/rescript-editor-support/pull/76

For the missing message in the problems part, perhaps the warning message should be printed differently.

**Comment by cristianoc** [comment]
CC @chenglou

**Comment by chenglou** [comment]
Oh man I totally forgot it was the indent thing... sorry I'll look into it

**Comment by chenglou** [comment]
K I'm fixing the warning indentation, but then we'd end up with duplicated deprecation message if we merge https://github.com/rescript-lang/rescript-editor-support/pull/76? Yours on hover, mine in diagnostics which also appears on hover

**Comment by cristianoc** [comment]
It could be removed from hover, though the hover already shows its own block with types and doc comments, and can as well show the deprecation message as part of that block for completeness. Either way.

**Comment by chenglou** [comment]
For posteriority, this is what it looks like with duplicated warnings:

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1909539/112856273-7771ad00-9064-11eb-9a5a-4336b089f814.png">
<img width="696" alt="Screen Shot 2021-03-29 at 7 58 02 AM" src="https://user-images.githubusercontent.com/1909539/112856301-7e98bb00-9064-11eb-9f32-95c5a04ebb5f.png">

**Comment by chenglou** [comment]
Fixed
