### ISSUE TITLE
VsCode icons for .res and resi files are not showing the Rescript logo

### ISSUE THREAD

**Issue by vasco3** [rescript-lang/rescript-vscode#46]
Would it be possible to have the rescript logo show as a file icon in VSCode for the rescript files?

Currently it is showing like this

<img width="186" alt="image" src="https://user-images.githubusercontent.com/804301/101668733-32901f00-3a51-11eb-96ab-d9462dce8502.png">

**Comment by Faliszek** [comment]
Do you use any extension for icons?
I use https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme
Really recommend that one. In my editor res files look like this:

![Screenshot 2020-12-10 at 09 38 57](https://user-images.githubusercontent.com/19210348/101747402-f221b700-3acb-11eb-9f44-e806df760e71.png)

**Comment by vasco3** [comment]
@Faliszek nice that works pretty well. Thanks for the recommendation!
