### ISSUE TITLE
[BUG] Incorrect rendering about `to`

### ISSUE THREAD

**Issue by bvanjoi** [rescript-lang/rescript-vscode#461]
The weak keyword `to` should do not rendered after `external`, maybe the expected html code is `<span color="red">to</span>`.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/30187863/174085250-2f3fc0f3-46e1-4ced-b2ab-d3562f9d4d1e.png">

**Comment by zth** [comment]
If we want to fix this, I guess using a semantic token forcing the identifier on the right of `external` to be considered a variable is the least invasive way. What do you think @cristianoc ?

**Comment by cristianoc** [comment]
So it's about: go though semantic highlighting and identify cases where ids are not emitted and they should be.
