### ISSUE TITLE
Do not show "Start a build" when click+hover on a value from another module.

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/rescript-vscode#471]
Especially if this value is from a module in `node_modules`. For `node_modules` it should never show, also when one opens the file explicitly.

**Comment by zth** [comment]
Was this not solved in https://github.com/rescript-lang/rescript-vscode/issues/462 ?

**Comment by cristianoc** [comment]
Completely forgot (and did not test on master).
I guess the remaining bit is to make it show up zero times when inside node_modules.

**Comment by zth** [comment]
Yes, good point, residing in node_modules should block the popup completely.
