### ISSUE TITLE
No type hint for react.component and ReactDOMStyle in the pre-release vscode editor plugin.

### ISSUE THREAD

**Issue by Mng12345** [rescript-lang/rescript-vscode#474]
### Environment
rescript version: 9.1.4
editor plugin version: pre-release after 1.30
system: windows10 x64

![mnggiflab-download (23)](https://user-images.githubusercontent.com/21278900/177282694-e71fc1de-2d95-4bab-b6b9-808ce6ac7485.gif)
![mnggiflab-download (24)](https://user-images.githubusercontent.com/21278900/177283510-7fc54490-3c98-465d-a5c3-27bf9d03417f.gif)
![mnggiflab-download (25)](https://user-images.githubusercontent.com/21278900/177283787-9f14eaf2-7acb-4e81-aaf5-a2fef57ae856.gif)

**Comment by Mng12345** [comment]
The type hint for `make` is wrong.
![mnggiflab-download (27)](https://user-images.githubusercontent.com/21278900/177285326-16220f48-0938-40c8-be2e-8d356f16ad87.gif)
I think the logic of type hint may be not correct.
![mnggiflab-download (29)](https://user-images.githubusercontent.com/21278900/177286574-075f1583-b93e-403a-bcd0-c1b6a23dfad6.gif)

**Comment by zth** [comment]
We've most likely found the cause for this. Will ping you again when there's a fix you can test. Thanks for reporting!

**Comment by zth** [comment]
@Mng12345 this should be fixed if you download the latest `vsix` from CI.
