### ISSUE TITLE
Errors get cleaned from problems tab without being resolved

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/rescript-vscode#477]
In a project which is not a monorepo (no `namespace: true`, just one bsconfig)

1. `rescript build -with-deps -w` 
2. An error appears both on the cli of the compiler and the problems tab (in my case a simple "module X cannot be found")
3. Close the VSCode tab of the File where the error appeared.
4. Open it again
5. The error vanishes from the problems tab.

Tested with current master (4f8d3f9)

**Comment by cristianoc** [comment]
Are the errors still in the compiler log?
The expectation is they are. But just to double check.

**Comment by fhammerschmidt** [comment]
Yes, they are.

**Comment by cristianoc** [comment]
It could be that on file close the diagnostics entry is removed and on open it is not restored.
If that's what's going on, this is mixing up storing data with displaying it. Does not seem necessary. The data should always reflect the current status of the compiler log. Separately, one can mark what files are open, if there is a reason to keep that info.

**Comment by cristianoc** [comment]
This:
```ml
let closedFile = (fileUri: string) => {
  let filePath = fileURLToPath(fileUri);

  stupidFileContentCache.delete(filePath);
```

**Comment by cristianoc** [comment]
> This:
> 
> ```ocaml
> let closedFile = (fileUri: string) => {
>   let filePath = fileURLToPath(fileUri);
> 
>   stupidFileContentCache.delete(filePath);
> ```

Not that, but definitely there's `deleteProjectDiagnostics` which also deletes the `projectFiles` entry.

@zth what do you think the fix should be?

**Comment by zth** [comment]
Will have a look at this later today. I think this needs to be fixed before releasing `1.4.0`.

**Comment by zth** [comment]
The root cause here seems to be the continuous syntax errors diagnostics. I think they accidentally reset diagnostics because they do their own updates. Will experiment with how we can either unify those, or ensure they use separate "namespaces" (if that's possible). Reporting back here a bit later.

**Comment by zth** [comment]
@fhammerschmidt can you verify that https://github.com/rescript-lang/rescript-vscode/pull/484 fixes for you as well? I can't reproduce anymore anyway.
