### ISSUE TITLE
Add logo to ReScript files

### ISSUE THREAD

**Issue by IwanKaramazow** [rescript-lang/rescript-vscode#48]
<img width="165" alt="image" src="https://user-images.githubusercontent.com/10634678/102642921-b5565f80-415e-11eb-8146-5e6d790fbe01.png">

**Comment by amiralies** [comment]
I think icons are added by Icon themes, not language extensions.
![image](https://user-images.githubusercontent.com/13261088/103138432-d8958780-46e7-11eb-9c5e-d6d330c17b4c.png)
I'm using material icon theme

**Comment by chenglou** [comment]
Yeah if we do this, we should do it on https://github.com/jesseweed/seti-ui, which is the default vscode icon theme

**Comment by chenglou** [comment]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/1909539/105161158-ec08f800-5ac5-11eb-87c7-c0a39b887d94.png">
Our plugin doesn't have that many users; so I'll close it for now. We can revisit it in the future.
