### ISSUE TITLE
No autocompletion in string interpolation

### ISSUE THREAD

**Issue by dkirchhof** [rescript-lang/rescript-vscode#480]
Unfortunatelly i don't get autocompletion in string interpolations. It worked in v 1.2.x but since 1.3.x it doesn't work anymore.

Now i have installed the version from this action: https://github.com/rescript-lang/rescript-vscode/actions/runs/2628522856  

While typing, no autocompletion:
![image](https://user-images.githubusercontent.com/2778643/177820336-6a50b964-87b8-4e74-9879-07fada9b45b2.png)

While hovering, there is a type hint:
![image](https://user-images.githubusercontent.com/2778643/177820386-bfa20957-f5c6-4792-91c1-b841d3f5d5a2.png)

**Comment by cristianoc** [comment]
Thank you.
Could you cut it down to the shortest possible self-contained example? That will speed up fixing it.

**Comment by dkirchhof** [comment]
Sure :)
Following code breaks:

```rescript
module hello = {
  world = "hello world"
}

let foo = "foo bar"

let message = `hello ${foo}`
```

While writing this code, I realized, that it works, if i remove the module:
```rescript
let foo = "foo bar"

let message = `hello ${foo}`
```

**Comment by cristianoc** [comment]
> ```rescript
> module hello = {
>   world = "hello world"
> }
> 
> let foo = "foo bar"
> 
> let message = `hello ${foo}`
> ```

Would you give an example in correct syntax and explain what it is that does not work?

Btw have you tried asking for completion explicitly? For me it's ctrl+space.

**Comment by cristianoc** [comment]
Just in case, autocomplete is not going to work for code with syntax errors. It can sometimes, but not always.

**Comment by dkirchhof** [comment]
Sorry, was to quick. There are several errors :facepalm: 

With correct code, the autocompletion works.

```rescript
module Hello = {
    let world = "hello world"
}

let foo = "foo bar"

let message = `hello ${foo}`
```

I will try to find an example where it breaks (with correct syntax :D).

**Comment by dkirchhof** [comment]
Well another try:

no autocompletion (the red variable):
```rescript
let red = "#ff0000"

let header = `
    color: ${red};
    background-color: ${red};
`
```

autocompletion (without the second line which also includes a variable):
```rescript
let red = "#ff0000"

let header = `
    color: ${red};
`
```

**Comment by cristianoc** [comment]
Thanks I can see it too.

**Comment by cristianoc** [comment]
For now: tests with a repro: https://github.com/rescript-lang/rescript-vscode/pull/483
