### ISSUE TITLE
Reanalyzer crashing after new install

### ISSUE THREAD

**Issue by youngkidwarrior** [rescript-lang/rescript-vscode#481]
I installed the master vsix [from the most recent action](https://github.com/rescript-lang/rescript-vscode/actions/runs/2628522856)

Here is the error when starting the code analyzer:

`Something went wrong parsing the json output of reanalyze: 'SyntaxError: Unexpected token , in JSON at position 381'`

I've tried uninstalling and reinstalling the extension but the issue remains. Where can I find the reanalyze json output?

**Comment by cristianoc** [comment]
There's a temporary file saved somewhere.
@zth  how about exposing the location of that file in the error message?

@youngkidwarrior  For now would you have a small, self-contained example, that reproduces the issue?

**Comment by zth** [comment]
Yeah I think exposing a bit more debug info makes sense. This looks like a trailing comma issue.

**Comment by youngkidwarrior** [comment]
@cristianoc I couldnt create a self contained example but I managed to reproduce the error.

Here are the steps:
1. Fresh install of VSCode
2. Install Rescript VSCode 1.3.0 from extension panel
3. Open a rescript project and start code analysis
4. Upgrade Rescript VSCode using the newest vsix (while code analysis is running)
5. Try to run code analysis again

This should produce the trailing comma error

**Comment by cristianoc** [comment]
I can repro thank you.

**Comment by zth** [comment]
I managed to reproduce it too. Here's the JSON reanalyze spits out that trips up `JSON.parse`:
```json


{
  "name": "Warning Dead Type",
  "kind": "warning",
  "file": "/Users/zth/git/rescript-intro/src/App.res",
  "range": [0,10,0,19],
  "message": "x.some is a record label never used to read a value",
  "annotate": { "line": 0, "character": 10, "text": "@dead ", "action": "Suppress dead code warning"}
},
{
  "name": "Warning Dead Type",
  "kind": "warning",
  "file": "/Users/zth/git/rescript-intro/src/App.res",
  "range": [0,21,0,34],
  "message": "x.thing is a record label never used to read a value",
  "annotate": { "line": 0, "character": 21, "text": "@dead ", "action": "Suppress dead code warning"}
},
{
  "name": "Warning Dead Type",
  "kind": "warning",
  "file": "/Users/zth/git/rescript-intro/src/App.res",
  "range": [2,15,2,18],
  "message": "z.Two is a variant case which is never constructed",
  "annotate": { "line": 2, "character": 15, "text": "@dead ", "action": "Suppress dead code warning"}
},
{
  "name": "Warning Dead Type",
  "kind": "warning",
  "file": "/Users/zth/git/rescript-intro/src/App.res",
  "range": [2,21,2,29],
  "message": "z.Three is a variant case which is never constructed",
  "annotate": { "line": 2, "character": 21, "text": "@dead ", "action": "Suppress dead code warning"}
},
{
  "name": "Warning Dead Type",
  "kind": "warning",
  "file": "/Users/zth/git/rescript-intro/src/App.res",
  "range": [2,32,2,41],
  "message": "z.Four is a variant case which is never constructed",
  "annotate": { "line": 2, "character": 32, "text": "@dead ", "action": "Suppress dead code warning"}
},
{
  "name": "Warning Dead Type",
  "kind": "warning",
  "file": "/Users/zth/git/rescript-intro/src/App.res",
  "range": [2,44,2,53],
  "message": "z.Five is a variant case which is never constructed",
  "annotate": { "line": 2, "character": 44, "text": "@dead ", "action": "Suppress dead code warning"}
},
{
  "name": "Warning Dead Value",
  "kind": "warning",
  "file": "/Users/zth/git/rescript-intro/src/App.res",
  "range": [4,0,4,17],
  "message": "f is never used",
  "annotate": { "line": 4, "character": 0, "text": "@dead ", "action": "Suppress dead code warning"}
}[
]
```

Full error message: `SyntaxError: Unexpected token , in JSON at position 306"

Here's the source res:
```
type x = {some: int, thing: string}

type z = One | Two | Three(x) | Four(int) | Five(int)

let f = Some(One)
```

The problem seems to be that the error objects aren't actually inside of the array literal, they come separately, producing invalid JSON.

**Comment by cristianoc** [comment]
Some issue in the printing for sure. Taking a look now.

Reminder: add an issue to at least one test runs in json mode.

**Comment by cristianoc** [comment]
It was mixing up normal print and formatter.

**Comment by cristianoc** [comment]
Fixed here:
https://github.com/rescript-lang/rescript-vscode/pull/482

Would you try again with the extension that will show up in CI when finished?
