### ISSUE TITLE
Syntax error as type for JSX

### ISSUE THREAD

**Issue by mattdamon108** [rescript-lang/rescript-vscode#492]
The new feature syntax error as type seems not to work seamlessly with the JSX application. I'm 100% not sure. My best guess is that JSX expression(especially JSX call site) is not transformed as type, or Reanalyze doesn't do analysis for the jsx application. Any future plan for improving checking syntax error as typing for JSX?

**Comment by zth** [comment]
Could you describe a bit more in depth what it is you're seeing now, and what you expect to see instead? Preferably with something minimal and reproducible.

**Comment by cristianoc** [comment]
Syntax errors are produced by the parser, not the editor.
You should have a similar repro using just a file and the command line.

**Comment by mattdamon108** [comment]
I think I am confused about what I've gotten from the OCaml experience. That means OCaml IDE checks the type error and syntax errors without saving. I'm clear now. And I really want that either. 😄
