### ISSUE TITLE
Formatting not working on Windows

### ISSUE THREAD

**Issue by illbexyz** [rescript-lang/rescript-vscode#5]
When formatting on Windows I get this error:
```
[Error - 20:56:35] Request textDocument/formatting failed.
  Message: Cannot find a nearby node_modules\bs-platform\win32\bsc.exe. It's needed for formatting.
  Code: -32600 
```

I found the cause of the error in:

```typescript
// TODO: remove this hack
let filePath = openFile.replace('file://', '');
```

because just removing the `file://` prefix isn't enough in Windows. On my system `filePath` contains  `\c%3A\Users\Alberto\workspace\rescript-vscode\node_modules\bs-platform\win32\bsc.exe` which isn't recognized by NodeJS's APIs.

**Comment by samcf** [comment]
Manually patched this for myself with the following but the work done here https://github.com/rescript-lang/rescript-vscode/pull/6 seems obviously better.

```js
// chenglou92.rescript-vscode-0.0.4\server\out\server.js#374
// TODO: remove this hack
let filePath = params.textDocument.uri.replace('file://', '');
if (process_1.default.platform === "win32") {
    filePath = decodeURIComponent(filePath).substring(1)
}
```
