### ISSUE TITLE
Trouble getting definitions

### ISSUE THREAD

**Issue by remitbri** [rescript-lang/rescript-vscode#506]
I'm using 1.4.2
It used to be fine with 1.3.0, but it seems with 1.4.2 I have troubles with getting the definition of (and jumping to) functions/records/etc, and the references. I'd say it happens when the function/record/etc is within a module which is outside the current module, but within the repo. If I hover the thing and press option I can't jump to its location, etc. 

Fun facts
 - I still get the type! (ex in a lens when I hover the function/record/etc)
 - Dev dependencies are fine. (ex I can jump to the definition of `React` or `useEffect` in `React.useEffect(() => {…}`)

**Comment by zth** [comment]
Can you set up a minimal reproduction somehow?

**Comment by remitbri** [comment]
Yep. Say I've got 
 ```
bsconfig.json
node_modules/
src/
```
(etc)


src/Bar.Res
```
let add = (a, b) => a + b
```

src/Foo.res
```
Bar.sub(4, 5)->ignore
```

in Foo.res, I've got the lens telling me `sub` is `(int, int) => int`, but I can't jump to its definition (in Bar.res)

**Comment by igna92ts** [comment]
Im having this issue as well

**Comment by cristianoc** [comment]
Please use the configuration option to set the path to the binary, and see if that helps.
Depending on the answer, we'l learn something new.

**Comment by cristianoc** [comment]
> Yep. Say I've got
> 
> ```
> bsconfig.json
> node_modules/
> src/
> ```
> 
> (etc)
> 
> src/Bar.Res
> 
> ```
> let sub = (a, b) => a - b
> ```
> 
> src/Foo.res
> 
> ```
> Bar.sub(4, 5)->ignore
> ```
> 
> in Foo.res, I've got the lens telling me `sub` is `(int, int) => int`, but I can't jump to its definition (in Bar.res)

We have an entire set of tests that correspond to that abstract description.
Would you try the project in `analysis/tests` see if you have this issue?

**Comment by remitbri** [comment]
> Please use the configuration option to set the path to the binary, and see if that helps.
I've set the path properly (I know since the previous tries were met with a "can't find…"), but it hasn't improved the situation.

> Would you try the project in analysis/tests see if you have this issue?

**Comment by cristianoc** [comment]
Good so next step is figure out what's different in your project.
Then report back.

**Comment by remitbri** [comment]
On the off chance, I upgraded my hello world test repo to 10.0.0-beta.3, but nope.

**Comment by WhyThat** [comment]
Hello, I found one way to reproduce the bug,
When `namespace` is set to `true` in the bsconfig, not sure if it's the same for you @remitbri

**Comment by remitbri** [comment]
Indeed! Good catch, @WhyThat . The `analysis/tests` project doesn't have the flag, my "hello world" repo has one - if I remove it everything's ok.

**Comment by cristianoc** [comment]
There used to be some namespace tests. So this might be relatively recent.

**Comment by cristianoc** [comment]
I don't think the compiler has changed anything about namespaces. Or at least I don't remember.

**Comment by fhammerschmidt** [comment]
I just used the [workspace-project](https://github.com/rescript-lang/rescript-vscode/tree/master/analysis/examples/workspace-project) and tried to execute the analysis binary on it.

With the current master, I get this:
```
➜  workspace-project git:(master) ✗ ../../_build/install/default/bin/rescript-editor-analysis definition app/src/App.res 0 22          
null
```

With version 1.3.0, I get this: 
➜  workspace-project git:(master) ✗ ../../_build/install/default/bin/rescript-editor-analysis_1.3.0.exe definition app/src/App.res 0 22
{"uri": "file://./node_modules/myplugin/src/Promise.res", "range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}}
```

I also downgraded the project to 9.1.4 and did a fresh build, same outcome.
So the regression has to be in the analysis binary, not in the compiler.

**Comment by zth** [comment]
I'm not at the computer for a while, but maybe someone could do a git bisect and find what commit caused it? Should be fairly fast, it's not that many commits between 1.3.0 and 1.4.0.

**Comment by fhammerschmidt** [comment]
I would never have guessed that one:

```
➜  rescript-vscode git:(026e27d) ✗ git bisect good
4f072736099fa8842f05643b289de005f9193bdb is the first bad commit
commit 4f072736099fa8842f05643b289de005f9193bdb
Author: Cristiano Calcagno <cristianoc@users.noreply.github.com>
Date:   Sat Jun 4 05:26:20 2022 +0200

    Remove more infix.

 analysis/src/FindFiles.ml | 11 +++++------
 analysis/src/Infix.ml     |  4 ----
 2 files changed, 5 insertions(+), 10 deletions(-)
 ```

**Comment by zth** [comment]
> I would never have guessed that one:
> 
> ```
> ➜  rescript-vscode git:(026e27d) ✗ git bisect good
> 4f072736099fa8842f05643b289de005f9193bdb is the first bad commit
> commit 4f072736099fa8842f05643b289de005f9193bdb
> Author: Cristiano Calcagno <cristianoc@users.noreply.github.com>
> Date:   Sat Jun 4 05:26:20 2022 +0200
> 
>     Remove more infix.
> 
>  analysis/src/FindFiles.ml | 11 +++++------
>  analysis/src/Infix.ml     |  4 ----
>  2 files changed, 5 insertions(+), 10 deletions(-)
> ```
> 
> [ Link to commit](https://github.com/rescript-lang/rescript-vscode/commit/4f072736099fa8842f05643b289de005f9193bdb)

Think you can fix it?

**Comment by fhammerschmidt** [comment]
Yes, I fixed it.

Tested it again after my changes, and now it gives me
➜  rescript-vscode git:(master) analysis/_build/install/default/bin/rescript-editor-analysis definition  app/src/App.res 0 22
{"uri": "file://./node_modules/myplugin/src/Promise.res", "range": {"start": {"line": 0, "character": 0}, "end": {"line": 0, "character": 0}}}

**Comment by fhammerschmidt** [comment]
@remitbri @igna92ts @WhyThat
Feel free to check if it works for you with the [VSIX of the PR build](https://github.com/rescript-lang/rescript-vscode/suites/7484997014/artifacts/307085474).

**Comment by WhyThat** [comment]
It works properly for the jump to definition but not for references nor rename (but I think it never work, but thinking about it I can't remember if these features has ever worked for project with namespace)

**Comment by fhammerschmidt** [comment]
Yes, I guess this one has never been fixed: https://github.com/rescript-lang/rescript-vscode/issues/273
