### ISSUE TITLE
Formatting after editting is failed with v1.4.2 but ok with v1.4.1.

### ISSUE THREAD

**Issue by Mng12345** [rescript-lang/rescript-vscode#514]
rescript[v9.1.4]
vscode extension[v.1.4.2]
system [windows x64]
Failed to format the code with vscode extension of version 1.4.2

**Comment by cristianoc** [comment]
More details: what's the behaviour on one example, and what's the expected behaviour?

**Comment by Mng12345** [comment]
![mnggiflab-download - 2022-07-25T094846 648](https://user-images.githubusercontent.com/21278900/180699412-59424668-3b89-4da7-822c-bd6d43dcf1d3.gif)

**Comment by Mng12345** [comment]
This is the example repo
https://github.com/Mng12345/rescript_142_notformatted.git
rescript-vscode 1.4.2
The global settings.json
```json
{
  "[rescript]": {
    "editor.defaultFormatter": "chenglou92.rescript-vscode",
  },
  "rescript": {
      "aliases": [
        "ReScript"
      ],
      "filenames": [],
      "extensions": [
        ".res",
        ".resi"
      ],
      "lineComments": [
        "//"
      ],
      "blockComments": [
        [
          "/*",
          "*/"
        ]
      ],
      "blockStrings": []
    },
}
```

**Comment by fhammerschmidt** [comment]
Your example works fine for me (on macOS).

Please continue only here with your findings and don't spam multiple forum posts.

As you mentioned in https://forum.rescript-lang.org/t/the-html-code-is-not-formatted-in-react-component-with-this-use-case/3585/

Yes, the path seems not to be the issue. I guess it even calls the formatter but fails somewhere.

Can you debug the `formatCode` function in `utils.ts`? Especially log out `bscPath` and the `result` in there.

Also the other null bug is probably because you don't have an `analysis` binary built? If you cannot build it, grab it from https://github.com/rescript-lang/rescript-vscode/releases/download/1.4.2/rescript-vscode-1.4.2.vsix, unzip it and copy the `extension/server/analysis_binaries` to your checked out rescript-vscode repo. Then it should not crash.

**Comment by Mng12345** [comment]
> Your example works fine for me (on macOS).
> 
> Please continue only here with your findings and don't spam multiple forum posts.
> 
> As you mentioned in https://forum.rescript-lang.org/t/the-html-code-is-not-formatted-in-react-component-with-this-use-case/3585/: Yes, the path seems not to be the issue. I guess it even calls the formatter but fails somewhere.
> 
> Can you debug the `formatCode` function in `utils.ts`? Especially log out `bscPath` and the `result` in there.
> 
> Also the other null bug is probably because you don't have an `analysis` binary built? If you cannot build it, grab it from https://github.com/rescript-lang/rescript-vscode/releases/download/1.4.2/rescript-vscode-1.4.2.vsix, unzip it and copy the `extension/server/analysis_binaries` to your checked out rescript-vscode repo. Then it should not crash.

Thanks! i will try it now!

**Comment by Mng12345** [comment]
[mnggiflab-download (26).webm](https://user-images.githubusercontent.com/21278900/180958521-0f0a75ac-a878-445b-9316-5bb4af75f5b9.webm)
The call `childProcess.execFileSync` just fall into nothing.

**Comment by Mng12345** [comment]
Sorry for ignored the catch block, this is the error stack:
![image](https://user-images.githubusercontent.com/21278900/180960877-4085fa50-5436-4606-b92a-f1d84859e1b7.png)

**Comment by Mng12345** [comment]
@fhammerschmidt I also execute the command in my project root path.
![image](https://user-images.githubusercontent.com/21278900/180963478-370cf711-72d2-43c7-a053-9bb4f69d3aab.png)

**Comment by Mng12345** [comment]
@fhammerschmidt, i tried bsc.cmd, the command worked well.
![image](https://user-images.githubusercontent.com/21278900/180966415-498f8035-64a8-4755-b596-109b8638751f.png)
![image](https://user-images.githubusercontent.com/21278900/180966639-3dc4a97f-420b-4253-afbe-8dc49bee8af5.png)
Probably something is wrong in the `bsc`

**Comment by fhammerschmidt** [comment]
Dumb question: What if you call `bsc.cmd`directly in the execFileSync call?

**Comment by Mng12345** [comment]
After changing the bscBinName from `bsc` into `bsc.cmd`, the formatting function worked normally!
I wish someday i can build and run this project on windows, so i can make some PR directly. 😘

**Comment by fhammerschmidt** [comment]
I could make a fix soon, but I just wonder how this could ever work before on Windows. There is some special logic to handle the call of the watcher directly, but not the other executables. In my opinion, this logic should be reused for all executables in the `node_modules/.bin` folder. But we have to discuss it internally first.

**Comment by Mng12345** [comment]
Thanks, i will clone the project with the version of v1.4.1, and find why in tonight later.

**Comment by TheSpyder** [comment]
I just saw the forum post and was going to comment - but I'll do it here instead - when making "symlinks" on windows for the `.bin` folder, npm creates `.cmd` files. These operate the same from the command line, because on windows trying to run `rescript` will also look for `rescript.exe` and `rescript.cmd`, but that automatic searching doesn't work when spawning a new process. At that point the `.cmd` is required.

> I just wonder how this could ever work before on Windows
I have no idea 🤷‍♂️ maybe an accident of how it was spawned before.

**Comment by fhammerschmidt** [comment]
@Mng12345 I may have fixed it already. Please try the VSIX from https://github.com/rescript-lang/rescript-vscode/actions/runs/2738948024 when the build finishes.

**Comment by Mng12345** [comment]
Thanks, i will try it when i am in home.

**Comment by Mng12345** [comment]
@fhammerschmidt Hi, i installed the latest extension from .vsix, the formatter behaves so weird... I guess you missed convertting the formatting result into string.
![mnggiflab-download - 2022-07-26T223530 386](https://user-images.githubusercontent.com/21278900/181035408-923e8d56-de77-49e0-8e4d-a1c1e7bddbbd.gif)

**Comment by fhammerschmidt** [comment]
Sorry, I am dumb. I thought I can reuse the existing function, but it's asynchronous. Updated the PR to use `execSync` and `execFileSync` respectively.

Try this build next: https://github.com/rescript-lang/rescript-vscode/actions/runs/2740758406

**Comment by Mng12345** [comment]
It works when set the `binaryPath` in the local `settings.json`, but failed again when i remove it.
![mnggiflab-download - 2022-07-27T092443 310](https://user-images.githubusercontent.com/21278900/181140345-8e07671d-de53-4616-94c8-05dd5e0df063.gif)

**Comment by fhammerschmidt** [comment]
That's not the latest VSIX, is it? See comment above.

**Comment by Mng12345** [comment]
Yes, it is the latest vsix extension.

**Comment by fhammerschmidt** [comment]
Just to be sure, remove all rescript things from `%USERPROFILE%\.vscode\extensions` before installing it.

**Comment by fhammerschmidt** [comment]
Tried a different approach, please try: https://github.com/rescript-lang/rescript-vscode/suites/7541241871/artifacts/311024881

**Comment by Mng12345** [comment]
> Tried a different approach, please try: https://github.com/rescript-lang/rescript-vscode/suites/7541241871/artifacts/311024881

I'm so sorry for too busy to check it today, will do it later!

**Comment by Mng12345** [comment]
@fhammerschmidt It works well now! Thanks!

**Comment by fhammerschmidt** [comment]
@Mng12345 can you please check if https://github.com/rescript-lang/rescript-vscode/suites/7598533435/artifacts/314961066 still works for you? Many thanks!

**Comment by Mng12345** [comment]
@fhammerschmidt Yes, the formatter part is worked normally.
