### ISSUE TITLE
Suggest installing a supported ReScript version when the binary is not found

### ISSUE THREAD

**Issue by Minnozz** [rescript-lang/rescript-vscode#530]
When depending on `bs-platform@8.4.2`:
<img width="469" alt="Screenshot 2022-07-27 at 21 23 44" src="https://user-images.githubusercontent.com/701386/181355169-593d63a8-0ed9-49db-9a62-9ade8d06c294.png">

- I'm not sure where "the directory null" comes from
- Maybe we could look for `bs-platform` in `node_modules` if `rescript` can't be found and suggest updating?

**Comment by cristianoc** [comment]
I think this is being done already.
CC @fhammerschmidt

**Comment by Minnozz** [comment]
If you mean #529, that fixes the "null" in the error message but still only looks inside `node_modules/rescript` and does nothing with `node_modules/bs-platform`.

Now that I think of it, maybe we could also detect when `npm install` is not run yet and suggest doing that?

**Comment by fhammerschmidt** [comment]
How about just rephrasing the message? Not sure If we really should check for `bs-platform` recursively just for the error message.

Something like:
```
Can't find ReScript binary in <working-directory>/node_modules/.bin or parent directories. Did you install it? It's required to use "rescript" > 9.1
```

**Comment by Minnozz** [comment]
Good idea 👍

**Comment by fhammerschmidt** [comment]
@cristianoc fine for you?

**Comment by cristianoc** [comment]
Note `bs-platform` is not supported.
That's also specified in the release notes.
So the title of this seems confusing.

**Comment by Minnozz** [comment]
@cristianoc How about this?

**Comment by cristianoc** [comment]
Sounds good. The only thing to check is that the message is compatible with the search strategy (which does not look into a single directory).
