### ISSUE TITLE
Inlay hint incorrectly shows type of first binding of destructured record for entire record

### ISSUE THREAD

**Issue by Minnozz** [rescript-lang/rescript-vscode#536]
Pre-release version `1.5.11`.

```res
type foo = {
  a: int,
  b: bool,
}

let bar = () => ({a: 0, b: true}, "123")

let ({a, b}, _) = bar()
```

![inlay-hint-bug](https://user-images.githubusercontent.com/701386/182165591-c42de406-8280-4c8d-bc4b-250b1e6ff55a.png)

To me, this incorrectly suggests `{a, b}` has type `int`.

**Comment by cristianoc** [comment]
CC @aspeddro
