### ISSUE TITLE
Something went wrong parsing the json output of reanalyze: 'SyntaxError: Unexpected token W in JSON at position 4'

### ISSUE THREAD

**Issue by Minnozz** [rescript-lang/rescript-vscode#537]
```
Something went wrong parsing the json output of reanalyze: 'SyntaxError: Unexpected token W in JSON at position 4'
```
I can't find the output that causes this error in the logs.

**Comment by cristianoc** [comment]
Two repros:
1) repro the issue
2) repro of the insufficient error message (should show the command being run)

It's the same repro needed but 2 aspects to it.

**Comment by zth** [comment]
We've talked about this before - we should log to the extension console what the json that broke is. Should be easy enough.

**Comment by cristianoc** [comment]
Can you try again from the latest beta extension from the marketplace? E.g. 1.5.17
It should give a better error helping reproducing the issue.

**Comment by Minnozz** [comment]
I have updated to 1.5.17 and will see if it happens again.

**Comment by zth** [comment]
Closing this meanwhile, feel free to reopen.
