### ISSUE TITLE
Formatting the document (manual or on save) is broken in pre-release v1.5.17

### ISSUE THREAD

**Issue by remitbri** [rescript-lang/rescript-vscode#552]
I'm on macOS, rescript v9.1.4, extension pre-release v1.5.17
Formatting doesn't seem to work anymore (even after reloading the window, etc)
Reverting to v1.4.2 (+ reload) brings back the functionality.

**Comment by fhammerschmidt** [comment]
Do you have a repro? I am on macOS with the same ReScript and extension versions as well. Both in a yarn workspace repo as well a simple `rescript init`ed one. Formatting works.

**Comment by remitbri** [comment]
I've duplicated my repo and reduced it to just bsconfig.json
```json
{
  "name": "barbaz",
  "reason": { "react-jsx": 3 },
  "sources": [{ "dir": "src", "subdirs": true }],
  "bs-dependencies": ["@rescript/react"]
}
```
and src/Foo.res
```rescript
let a = <div style={ReactDOM.Style.make(
              (),
            )}><hr/></div>
let b=
5
```
and still no formatting with 1.5.17 :-/

**Comment by remitbri** [comment]
_(hmm, let me check)_

Yep. This is using "rescript": "^9.1.4" in my package.json.
If I use "rescript": "^10.0.0-rc.1", formatting works

**Comment by fhammerschmidt** [comment]
Your setup formats perfectly fine for me. ☹️ 
Are there any logs on the `OUTPUT` > `ReScript Language Server` tab?

**Comment by remitbri** [comment]
- output tab: no output
- package manager: yarn (v1.22.9)
- extension settings: "ask to start build" set to `true`, others to `false`, no binary path, and just to be extensive: inlay hints max length set to 25

**Comment by fhammerschmidt** [comment]
Still works for me. Can you check out https://github.com/fhammerschmidt/rescript-vscide-no-formatting and see if that works for you or if there is anything missing compared to your setup?

**Comment by remitbri** [comment]
I've just tried with your repo and it still doesn't work :(   
(Btw, I'm using VS Code 1.70.1, just in case)

**Comment by fhammerschmidt** [comment]
Some more possibilities (i know they sound desperate):
* Do you suspect there is any other extension interfering? Try disabling all of them.
* Try deleting the extension from ~/.vscode/extensions/ and reinstall it.
* check if there is actually a path to `node_modules/.bin/bsc`
* Are you on X86 or ARM architecture? Because I have x86, but I feel we would have far more reports if it was the architecture.

**Comment by remitbri** [comment]
> Do you suspect there is any other extension interfering? 

I don't see why. Specially as if I revert to v1.4.2, formatting comes back (after reloading the page, of course). And goes away if I revert to pre-release (after reloading, etc)

---

> Try deleting the extension from ~/.vscode/extensions/ and reinstall it.

I tried : nope :(

---
> check if there is actually a path to node_modules/.bin/bsc
in the local repo; ./.vscode/settings.json
```json
{
  "rescript.settings.askToStartBuild": true,
  "rescript.settings.autoRunCodeAnalysis": false,
  "rescript.settings.binaryPath": null,
  "rescript.settings.codeLens": false,
  "rescript.settings.inlayHints.enable": false,
  "rescript.settings.inlayHints.maxLength": 25
}
```

---
> Are you on X86 or ARM architecture?

ARM. M2.

**Comment by fhammerschmidt** [comment]
Uuuuh, I think I know what's the problem. 9.1.4 only works on ARM with Rosetta, by using the X86 binary. 

We now call the `bsc.exe` directly instead of relying on `node_modules/.bin./bsc`, because it gave us issues on Windows. But therefore we check the platform + arch in the extension which yields probably `node_modules/rescript/darwinarm64/bsc.exe` when it should be `node_modules/rescript/darwin/bsc.exe`.

Previously it only worked, because we let the bsc wrapper do the work, which is tailored to the respective rescript version.

@cristianoc @zth any ideas what we can do about this (preferably without reverting to how we did things in 1.4.2).

**Comment by fhammerschmidt** [comment]
@remitbri Just to check, can you change the folder name and see if it works:

`node_modules/rescript/darwinarm64` -> `node_modules/rescript/darwin`?

**Comment by remitbri** [comment]
That did the trick, yep.

**Comment by fhammerschmidt** [comment]
Proposed solutions (or workarounds)
* Check for the existence of `darwinarm64` and try `darwin` if not found. Not sure if a `existsSync` before every format is too expensive or if it can be kept in state.
* Check for the installed compiler version (requires parsing package.json), and use `darwin` if <10 
* Have another path setting for `bsc.exe`. This is not feasible for repositories where multiple users work.
* Release a 9.1.5 with a darwinarm64 folder.

What do you think, @cristianoc @zth

**Comment by zth** [comment]
It has been nice to be able to disregard what version of ReScript is installed so far. But I'd still prefer that (figure out what ReScript version is running and adapt accordingly) of those alternatives. We will end up there (needing to adapt things according to version) sometime anyway, might as well bite the bullet and support it.

My 5c. @cristianoc ?

**Comment by cristianoc** [comment]
We can move the extension into the compiler.

**Comment by fhammerschmidt** [comment]
You mean only having the client code being part of the extension and move the server code to the compiler?

AFAIK [grain-lang](https://github.com/grain-lang/grain) does it that way. The LSP is shipped with the compiler CLI, while the client is still installed via VSCode.

Though that seems to be infeasible short-term. Shouldn't we create some hot fix for this issue?

**Comment by cristianoc** [comment]
We can hit fix this issue for sure.
The extension repo can be moved to the compiler soonish -- same as syntax repo.
