### ISSUE TITLE
Bug: "Open compiled" assumes "in-source": true.

### ISSUE THREAD

**Issue by cdaringe** [rescript-lang/rescript-vscode#555]
# problem

The extension only looks for source as siblings to .res files, but they may be in `lib/*`.

See https://rescript-lang.org/docs/manual/latest/build-configuration#package-specs

# discussion

I propose that a recursive search for `bsconfig.json` should occur, parse, sniff for package-specs, and ascertain the source file location based on configuration.

**Comment by fhammerschmidt** [comment]
So generally, I accounted for the files in the lib folder when I wrote this feature. But I may have missed something. Can you provide a bsconfig or even example repo where it fails?

**Comment by cdaringe** [comment]
hey @fhammerschmidt , sure thing. I may be off the mark about resolution, but nonetheless, it doesn't work in my project.

### repro

1. clone it: clone https://github.com/cdaringe/wit-ml
1. use the git SHA from this moment in time: `cd wit-ml && git checkout 51bde658e161cf145a06eb9a214c8c97a5ef8870`
1. `pnpm install && pnpm run build`
1. pop open `src/App.res`
1. click the "Open compiled JS" button
1. Observe "No compiled file found" notification

**Comment by fhammerschmidt** [comment]
We are in the process of making bsconfig JSON-compliant. This means no support for comments unfortunately. While I agree the error message could tell you about this, I think it should work for you if you remove the commented line, or just set `in-source: false`.

Also see the [breaking change in the compiler changelog](https://github.com/rescript-lang/rescript-compiler/blob/master/CHANGELOG.md#boom-breaking-change-1).
