### ISSUE TITLE
Problem with formatting with built-in compiler.

### ISSUE THREAD

**Issue by vdanchenkov** [rescript-lang/rescript-vscode#556]
We use this extension to format files automatically on save. For some reason rescript-vscode was unable to find rescript executable files in the project on my machine. I saw message about it, but everything seemed to work. 

Today I found out that extension uses different version of compiler. We use latest 9.* in the project. Extension seems to use 10.* 

As a result, I've been committing incorrectly formatted files for some time until I got code formatted to incompatible syntax and spotted the issue.

**Comment by vdanchenkov** [comment]
Incompatible syntax is:

```
module A = {
  type t = {x: string, y: string}
}

let x = "test1"

let a = {A.x, y: "y"}
```

**Comment by fhammerschmidt** [comment]
The extension falls back to the vendored printer if no bsc is found. Which platform & architecture are you on? Maybe it was fixed in #552?

Also please tell me your package manager.

**Comment by vdanchenkov** [comment]
@fhammerschmidt Thank you for response. I was not clear enough. "no bsc found issue" is resolved for me currently. I'm not sure why it happened and how to reproduce it. Now it works correctly. 

My point is that vendored printer was harmful for me situation. I would prefer to have no formatting at all instead of formatting for "next" version.

**Comment by fhammerschmidt** [comment]
It's nice to have formatting in a quick prototype file without a project setup. But I also agree it is pretty easy to have the extension not find the compiler, for instance if you just checked out a project and forgot to `npm install`.

@zth do you think it's feasible to prompt the user to format with the vendored parser and remember that until the file is closed again?

**Comment by cristianoc** [comment]
I think we should expose, loudly in the UI, when the built-in formatter is used. Perhaps ask for confirmation or something.

CC @zth

**Comment by zth** [comment]
One idea is to gate using the vendored parser for formatting behind an option, and then prompt the user to enable that option if they want to format, whenever they try to format something where we don't find the compiler itself. What do you think?

**Comment by cristianoc** [comment]
That sounds great.

**Comment by zth** [comment]
I'm going to tackle this soonish.
