### ISSUE TITLE
Expand type aliases one level when hovering

### ISSUE THREAD

**Issue by zth** [rescript-lang/rescript-vscode#557]
Currently, when hovering something where the type is a reference to some other type, that other type is not expanded. Example:
```rescript
SomeModule.Types.searchInput
type searchInput = AnotherModule.searchInput
```

We should expand that type reference one level (?), so that the resulting hover instead would be something along the lines of:
```rescript
AnotherModule.searchInput
type searchInput = {
  someField: int
}

type searchInput = AnotherModule.searchInput
```

Not 100% of how the representation should be, but we should include the full aliased type at least.

**Comment by cristianoc** [comment]
Can we have a complete example (there are some details I have doubts about)? Also, is this only about references across different files?

**Comment by cristianoc** [comment]
```
  type peps  = {x:int, y:string}

  let foo = () => {x:3, y:""}
// Hover: unit => peps
```

When hovering on `foo` instead of showing just `unit => peps` it could additionally print the type definition of `peps` as in the module hover:
```
  type peps = {x: int, y: string}
```

In general, when showing a type `t`, it could collect all the type names mentioned in `t`, and for each, if it is a type definition, expand it below.
