### ISSUE TITLE
Formatting document fails in monorepo

### ISSUE THREAD

**Issue by Minnozz** [rescript-lang/rescript-vscode#572]
Extension version: 1.7.6 (latest master)

The `Format document` feature uses the `bsc.exe` binary:
https://github.com/rescript-lang/rescript-vscode/blob/877f874c52ab51e88dacc73524ca4e5c16912eef/server/src/server.ts#L740-L742

The location of the `bsc.exe` binary is determined as follows:
https://github.com/rescript-lang/rescript-vscode/blob/877f874c52ab51e88dacc73524ca4e5c16912eef/server/src/server.ts#L112-L121

It is "reverse engineered" from the location of the `rescript` binary:
https://github.com/rescript-lang/rescript-vscode/blob/877f874c52ab51e88dacc73524ca4e5c16912eef/server/src/server.ts#L107-L110
https://github.com/rescript-lang/rescript-vscode/blob/877f874c52ab51e88dacc73524ca4e5c16912eef/server/src/utils.ts#L56-L60

The `node_modules/.bin/rescript` symlink exists both at the monorepo top level `node_modules` and the subdir `node_modules`, which makes `findRescriptBinary` return `src/monorepo/subdir/node_modules/.bin/rescript`.

However, the `node_modules/rescript` directory usually exists only at the monorepo top level, so when the path of the `rescript` binary is used to derive the location of `bsc.exe`, this results in the non-existent path `src/monorepo/subdir/node_modules/rescript/linux/bsc.exe`. It should actually return `src/monorepo/node_modules/rescript/linux/bsc.exe` (without `subdir`).

To make things more complicated, if `node_modules/rescript` *does* exist in the subdir, that directory should be used. This may be the case when multiple `rescript` versions are used in the same monorepo.

**Comment by Minnozz** [comment]
I will create a PR that uses the correct algorithm for finding `bsc.exe`.

**Comment by Minnozz** [comment]
Note that a lot of the complexity comes from this guideline:
https://github.com/rescript-lang/rescript-vscode/blob/master/CONTRIBUTING.md?plain=1#L159

We want to use `bsc.exe` (ocaml binary) instead of `bsc` (nodejs wrapper). ``bsc` lives in `node_modules/.bin`, while `bsc.exe` does not, so a different algorithm is needed.

**Comment by cristianoc** [comment]
See the forum discussion first.
Some agreement should be reached first.
Then documenting the agreement and implement it.
Turns out there are many opinions in what is a monorepo.

**Comment by Minnozz** [comment]
@cristianoc I think #573 may be a good candidate to merge even before consensus is reached about monorepos, because:
- Formatting worked in my monorepo in a previous version, and was broken recently
- This syncs the mechanism for finding `bsc.exe` to the mechanism for finding `rescript`, which is more logical
- It adds `rescript.settings.platformPath`, which can be used to fix formatting if you have a non-standard setup which is not automatically supported, while currently there is no easy way to fix formatting

**Comment by Freddy03h** [comment]
Hi, I'm on macos and I also got an issue about formatting on a monorepo (yarn v1 workspaces).

"format on save" or command "document format" don't format at all on a monorepo project (no issue on a normal project, with the exact same vs code config) with `1.6.0` version, I downgraded to `1.4.2` and it work.

**Comment by tsnobip** [comment]
We also have the same issue at work on our monorepo, it used to work fine before.
