### ISSUE TITLE
Enable the same hover content for hovers on unsaved content as on compiled content

### ISSUE THREAD

**Issue by zth** [rescript-lang/rescript-vscode#588]
Hovers can currently be produced in 2 ways - either 1) the location we're hovering has a type already (the content has compiled successfully), or 2) we use the same mechanism as autocomplete on unsaved content to trace back something being hovered to something that has compiled.

Hovering in case 1 vs case 2 is different, and we should unify the hovers so case 2 produces the same hover as case 1, if possible.

**Comment by cristianoc** [comment]
Can you enumerate ways in which the hover is different? So we can partition into cases that are intrinsically different because of the lack of type info, and those that just happen to be so and can be changed.
