### ISSUE TITLE
async not highlighted as keyword

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#603]
I know it is not actually implemented as a keyword, but it should be highlighted like one.

Currently it looks like this:

![Bildschirmfoto 2022-10-15 um 18 57 14](https://user-images.githubusercontent.com/591384/195998693-663e2a17-fdc6-44b3-af4d-69ab199b5e16.png)

**Comment by cristianoc** [comment]
Yes it should. In the grammar.
Then used as an id, semantic highlighting should change the highlighting automatically.
