### ISSUE TITLE
Search and replace broken if ReScript plugin + format on save are active

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#606]
In our projects, I often observe the following behavior:

When
* the ReScript plugin is active
* I have format on save activated in my settings (`"editor.formatOnSave": true`)
* and I perform a search and replace across files in the search tab (SHIFT-CMD-F)

then the replacement is only performed in a subset of the matching files (e.g. 3 out of 14).

I do not know if a certain project size is required to reproduce this. When I just tested, the search & replace did work fine the very first time after opening VS Code, but after resetting the changed files and repeating the search & replace operation, the problem was observed.

**Comment by zth** [comment]
Hmmm... That sounds weird. So the rest of the files aren't affected at all?

And this is isolated to ReScript, have you tried reproducing in some other language? Provided you have access to such a repository.

**Comment by cknitt** [comment]
When searching and replacing in other files in the same repo, e.g., in the generated JS files, the problem does not occur.

**Comment by zth** [comment]
I've experienced this too now in the wild. Will see if I can do some digging at some point. I have a hunch it has to do with the file contents cache we have, but a bit unclear _why_.

**Comment by fhammerschmidt** [comment]
Turns out the ReScript extension is innocent, a simple upgrade fixes it.

**Comment by cristianoc** [comment]
That explains why events were observed out of order.
