### ISSUE TITLE
Understand paths in `-open` in `bsc-flags`

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/rescript-vscode#607]
E.g. `"-open ReScriptJs.Js"` is not recognised
while `"-open ReScriptJs", "-open Js"` is

**Comment by cristianoc** [comment]
CC @zth

**Comment by cristianoc** [comment]
The semantics of `"-open ReScriptJs", "-open Js"` is not the same as `"-open ReScriptJs.Js"`. To be accurate, this should be taken into account.

So this issue is not completely fixed yet.

**Comment by zth** [comment]
This is now fixed.
