### ISSUE TITLE
Change artifact name on `latest-master` release

### ISSUE THREAD

**Issue by aspeddro** [rescript-lang/rescript-vscode#612]
It is possible to change the name of the `.vsix` artifact in the `latest-master` release from `rescript-vscode-<version>.vsix` to `rescript-vscode-latest-master.vsix`?

The reason is that I would like to test the pre-release channel on Neovim and the plugins use the tag name to download the artifact.

**Comment by zth** [comment]
cc @fhammerschmidt

**Comment by fhammerschmidt** [comment]
Yes, that should work. I made a PR.
