### ISSUE TITLE
No completion after typing `.`

### ISSUE THREAD

**Issue by Mng12345** [rescript-lang/rescript-vscode#614]
rescript version: 10.0.1
rescript-vscode version: lastest master v1.9.13
No completion after typing `TypedBase.`, I have debugged the extension, and get this completion output: `[]`, i don't know why there is no completion here.
Here is my use case:
`
e:\vscode_proj\rescript-vscode\server\analysis_binaries\win32\rescript-editor-analysis.exe completion e:\vscode_proj\mng-gif-maker-v5\res\gif\MngGif.res 174 17 C:\Users\Lenovo\AppData\Local\Temp\rescript_format_file_33580_295
`
### source files here: [MngGif.res](https://github.com/Mng12345/rescript-extension-debug-files/blob/main/MngGif.res) [rescript_format_file_33580_295](https://github.com/Mng12345/rescript-extension-debug-files/blob/main/rescript_format_file_33580_295)
The cursor is in line 175.
I also called the analysis.exe in command line, and get the same result.
`
PS E:\vscode_proj\rescript-vscode> e:\vscode_proj\rescript-vscode\server\analysis_binaries\win32\rescript-editor-analysis.exe completion e:\vscode_proj\mng-gif-maker-v5\res\gif\MngGif.res 174 17 C:\Users\Lenovo\AppData\Local\Temp\rescript_format_file_33580_295
[]
`

**Comment by Mng12345** [comment]
Don't know why, it seems happened randomly, i just switch to the latest release version of v1.8.2, and the completion works normally. For pre-release version v1.9.13, it also works normally.

**Comment by Mng12345** [comment]
When using wsl on windows with system ubuntn, it works.

**Comment by zth** [comment]
Closing this, feel free to open with a minimal reproduction.
