### ISSUE TITLE
Create interface file with JSX 4 component

### ISSUE THREAD

**Issue by cknitt** [rescript-lang/rescript-vscode#617]
Given a JSX 4 component defined in `Test.res`:

```rescript
@react.component
let make = (~a: string) => React.string(a)
```

I get the following `Test.resi` when using the "ReScript: Create interface file..." action:

```rescript
type props<'a> = {a: 'a}
let make: props<string> => React.element
```

I would have expected to get

```rescript
@react.component
let make: (~a: string) => React.element
```

(same as for JSX 3).

**Comment by cristianoc** [comment]
This, and genType check, are finishing touches for the release. There are dependencies on the actual representation of things so only make sense to do when we know nothing else changes.
Basically, we need a final rc candidate first, then these.

**Comment by fhammerschmidt** [comment]
The latest master extension still does not generate a `@react.component` for me when I use JSXV4. Regardless of mode, both `automatic` and `classic` give me the same result that Christoph mentions above.

@cristianoc something is still missing

**Comment by cristianoc** [comment]
> The latest master extension still does not generate a `@react.component` for me when I use JSXV4. Regardless of mode, both `automatic` and `classic` give me the same result that Christoph mentions above.
> 
> @cristianoc something is still missing

What compiler version? Try `10.1.0-rc.4`.

**Comment by fhammerschmidt** [comment]
I tried with both `10.1.0-rc.4`  and `10.1.0-rc.5`.

**Comment by cristianoc** [comment]
@fhammerschmidt can you start from the project in this? https://github.com/rescript-lang/rescript-vscode/pull/636
I've switched to V4 and the interface file is create in CI. Should work from the editor directly too.

**Comment by cristianoc** [comment]
OK I have some examples that don't work.

**Comment by cristianoc** [comment]
@fhammerschmidt should be fixed now.

**Comment by fhammerschmidt** [comment]
Thank you very much!
