### ISSUE TITLE
No hover on labelled arguments

### ISSUE THREAD

**Issue by zth** [rescript-lang/rescript-vscode#62]
Using `1.0.4` on macOS.

Hovering on labelled arguments does not produce any results. Here's an example in code:
```rescript
type cfg = {content: string}

let someFunction = (
  ~process: string => string,
  ~anotherSubFunction: cfg => string,
  content: string,
) => {
  anotherSubFunction({content: content->process})
}

// Hovering `process` or `anotherSubFunction` here gives no results. I'd expect `string => string` and `cfg => string` (ideally with `cfg` expanded in the hover too).
let x = someFunction(~process=s => s, ~anotherSubFunction=({content}) => content, "hello")

```

A repro is available in code here: https://github.com/zth/rescript-editor-tooling-playground/blob/master/src/FunctionHoverIssues.res

**Comment by cristianoc** [comment]
The ast does not store the location of labels in function calls, so it's not completely clear how to recover the position.
The information is available on the function name, and on the right-hand-side of `=`, but yes it would be nice to have it on the labels.

**Comment by zth** [comment]
That's too bad, it would be really valuable. But it does seem like `ocaml-lsp` can't figure it out either, it just shows `string` for the example above. 

Getting some form of guidance here (whether its through hover, autocomplete, or both) would be nice. One very nice thing about TS is that you can do exploratory autocompletion to figure out what you can pass into something like a function. Having something in ReScript that achieves the same thing would be very valuable imo, even if it doesn't work in the exact same way.

**Comment by chenglou** [comment]
Ugh the AST =/ maybe one day we'll finally have our own.

cc @IwanKaramazow can we do anything here?

**Comment by zth** [comment]
This works as per the latest release, after the work by @cristianoc on picking up the location of labelled arguments (and JSX props). 🎉
