### ISSUE TITLE
Parsing JSON from reanalyze failed: [Fatal error: exception End_of_file

### ISSUE THREAD

**Issue by benadamstyles** [rescript-lang/rescript-vscode#625]
I ran the command explained in the VS Code extension output and the result was:

```
[Fatal error: exception End_of_file
```

Is there a way for me to get something more useful to help debug this? It keeps happening even after reloading VS Code.

**Comment by zth** [comment]
Can you try cleaning and rebuilding your ReScript project, and then try again?

**Comment by benadamstyles** [comment]
Ah man why did I not think of that 🤦 thanks for the quick reply!

**Comment by zth** [comment]
We used to have a prompt that told you to do that. Curious if that showed or not.

**Comment by MinsangKim-GreenLabs** [comment]
I just faced the same issue mentioned here, and there was no such prompt to clean up.
So here's a screenshot of what I've got.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/105708964/203259833-6555f558-a628-4b0c-9087-9a6a83ab44a3.png">

It would be better to have one!
