### ISSUE TITLE
unwanted Newlines

### ISSUE THREAD

**Issue by lavabyte** [rescript-lang/rescript-vscode#630]
when I save the *.res file in vSCode like this:
```
let s = `line1
line2`
```

then suddenly it becomes:
```
let s = `line1

line2`

```

If I save it again, more newlines are coming:
```
let s = `line1


line2`

```

And again:
```
let s = `line1



line2`

```

It's really strange for me...I'm not sure which setting might be wrong.

**Comment by zth** [comment]
https://github.com/rescript-lang/rescript-vscode/issues/427 does that help?
