### ISSUE TITLE
VSCode extension compatibility 

### ISSUE THREAD

**Issue by dangdennis** [rescript-lang/rescript-vscode#638]
Re: [forum thread](https://forum.rescript-lang.org/t/you-can-easily-build-rescript-files-with-deno-now/3938)

I demonstrated that deno can the rescript&friends binary from npm and build locally. But the vscode extension doesn't work because deno caches the files in a deno-specific directory. However, if you run `deno run --node-modules-dir entrypointfile.ts`, we get a `node_modules` folder for the extension.

However, I'd like to make it even easier to use without the `--node-modules-dir` option. 

It looks like [`constants.ts`](https://github.com/rescript-lang/rescript-vscode/blob/master/server/src/constants.ts) evaluates a path to the binary depending on env. 

On arm64 m1 apple, `deno info` returns our cache locations
```
DENO_DIR location: /Users/dennisdang/Library/Caches/deno
Remote modules cache: /Users/dennisdang/Library/Caches/deno/deps
npm modules cache: /Users/dennisdang/Library/Caches/deno/npm
Emitted modules cache: /Users/dennisdang/Library/Caches/deno/gen
Language server registries cache: /Users/dennisdang/Library/Caches/deno/registries
Origin storage: /Users/dennisdang/Library/Caches/deno/location_data
```

The rescript binary lives within `~/Library/Caches/deno/npm/registry.npmjs.org/rescript/`. 

Despite the available workaround, is there any interesting in supporting a Deno "natively"?

**Comment by zth** [comment]
There are a bunch of configuration options already for pointing out where the binary is located. Could you check if either of those work for your use case?

**Comment by dangdennis** [comment]
I see it.

` "rescript.settings.binaryPath": "~/Library/Caches/deno/npm/registry.npmjs.org/rescript/10.0.1/darwinarm64/rescript.exe",` works well enough. I think we're fine then. It does seem a bit extra to have to handle Deno in the extension.
