### ISSUE TITLE
Autocomplete stops working after `evt->ReactEvent.Synthetic.preventDefault`

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/rescript-vscode#643]
Very curious:

```res
let onClick = evt => {
  // Autocomplete works here, e.g.:
  // ReactEvent.
  evt->ReactEvent.Synthetic.preventDefault
  // Autocomplete does not work here, e.g.:
  // ReactEvent.

  Js.log("Hello")
}
```
<img width="581" alt="image" src="https://user-images.githubusercontent.com/18074327/205032851-0ee41653-5779-4bf9-a54e-3f27ccac6619.png">

<img width="473" alt="image" src="https://user-images.githubusercontent.com/18074327/205032761-d6642575-66dd-45e8-bb90-ea478603b0d8.png">

**Comment by zth** [comment]
Can you create a reproducible example? Better yet a failing test in the analysis folder.

**Comment by fhammerschmidt** [comment]
Done, and it got even weirder...
