### ISSUE TITLE
All references are not being found for module component

### ISSUE THREAD

**Issue by aspeddro** [rescript-lang/rescript-vscode#645]
[ApiLayout.res](https://github.com/rescript-association/rescript-lang.org/blob/8a69d19322d0b512a915eca0c38ea9844b50df12/src/layouts/ApiLayout.res#L131) on ReScript lang website.

The analysis return two locations:

`dune exec rescript-editor-analysis references ~/Desktop/projects/rescript-lang.org/src/layouts/ApiLayout.res 130 9`

```
[ 
{"uri": "file:///home/pedro/Desktop/projects/rescript-lang.org/src/layouts/SidebarLayout.res", "range": {"start": {"line": 209, "character": 4}, "end": {"line": 209, "character": 8}}},
{"uri": "file:///home/pedro/Desktop/projects/rescript-lang.org/src/layouts/SidebarLayout.resi", "range": {"start": {"line": 64, "character": 4}, "end": {"line": 64, "character": 8}}}
]
```

The locations above are of `make` function, i.e, definition.

The real references occur in other files:

- [DocsLayout.res](https://github.com/rescript-association/rescript-lang.org/blob/05e34c3dcaf65104f81822ae061acafa2a78de3d/src/layouts/DocsLayout.res#L145)
- [ApiLayout.res](https://github.com/rescript-association/rescript-lang.org/blob/569caaf572597d3eb1887ec6ea8f6a6b3ed78ee7/src/layouts/ApiLayout.res#L131) (__the current file__)

**Comment by cristianoc** [comment]
As a simpler example:
```res
module M1 = {
  let x1 = 10

  @react.component
  let make = () => React.null
}

module M2 = {
  let x2 = 10
}
```

No references are found for `x1` (not even its own definition) while they are found for `x2`.
So it seems that by just being in the same module as a component breaks references.

**Comment by cristianoc** [comment]
Even simpler example:
```res
module M1 = {
  let x = 10

  let a = 3
  let a = a
}

module M2 = {
  let x = 10
}
```

**Comment by cristianoc** [comment]
This could be relevant: https://github.com/rescript-lang/rescript-vscode/pull/622
At least, same scenario of shadowing triggering the observed issue.

**Comment by cristianoc** [comment]
So shadowing creates a module constraint (i.e. a module type generated by the compiler), but also an example with an explicit module type has the same problem:

```res
module M3: {
  let aa: int
} = {
  let aa = 13
}

let dd = M3.aa
//           ^ref
```

**Comment by aspeddro** [comment]
I just tested #646 and the references still point to definition.

![image](https://user-images.githubusercontent.com/16160544/206275550-5d7c8443-c7fa-42aa-856d-11f025752c1e.png)

**Comment by cristianoc** [comment]
Seems to work on the project used to test the extension. Might need a separate small repro.
