### ISSUE TITLE
Go to definition returns wrong location

### ISSUE THREAD

**Issue by aspeddro** [rescript-lang/rescript-vscode#652]
Go to definition in [`<Sidebar`](https://github.com/rescript-association/rescript-lang.org/blob/bee26444624e77e81a0b9e32984977a71fcf56e7/src/layouts/ApiLayout.res#L124) return wrong location.

`dune exec rescript-editor-analysis definition ~/Desktop/projects/rescript-lang.org/src/layouts/ApiLayout.res 123 9`

```
{"uri": "file:///home/pedro/Desktop/projects/rescript-lang.org/src/layouts/SidebarLayout.res", "range": {"start": {"line": 212, "character": 4}, "end": {"line": 212, "character": 8}}}
```

The correct location is [`ApiLayout.res`](https://github.com/rescript-association/rescript-lang.org/blob/bee26444624e77e81a0b9e32984977a71fcf56e7/src/layouts/ApiLayout.res#L4)

**Comment by cristianoc** [comment]
I think this refers to [`<Sidebar`](https://github.com/rescript-association/rescript-lang.org/blob/bee26444624e77e81a0b9e32984977a71fcf56e7/src/layouts/ApiLayout.res#L124) a few lines above.

**Comment by cristianoc** [comment]
Fixed in https://github.com/rescript-lang/rescript-vscode/pull/653
