### ISSUE TITLE
Document symbols broken (flat) from v1.9.25

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/rescript-vscode#654]
From version `1.9.25` the symbols in the document appear as a flat list and not nested.

**Comment by cristianoc** [comment]
In `1.9.24`:

![Screenshot 2022-12-15 at 17 48 03](https://user-images.githubusercontent.com/7965335/207919449-1339f50b-6969-49d4-b990-3cc3b62dbab8.png)

In `1.9.25`:

![Screenshot 2022-12-15 at 17 47 14](https://user-images.githubusercontent.com/7965335/207919477-f2d654a0-20dc-4fed-a141-e3a9146b6785.png)

**Comment by cristianoc** [comment]
@aspeddro would you take a look?
I think it's after thing change: https://github.com/rescript-lang/rescript-vscode/pull/629
Not sure how things are expected to be represented in order do communicate the nesting of elements.

**Comment by aspeddro** [comment]
I'm looking at this.

**Comment by cristianoc** [comment]
Turns out a bunch of extra work is required now: https://github.com/rescript-lang/rescript-vscode/pull/655
