### ISSUE TITLE
Language server stdout support

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/rescript-vscode#66]
I think it makes sense to support stdout and/or tcp since many language servers do not support node ipc.

related: https://github.com/rescript-lang/vim-rescript/issues/20

**Comment by chenglou** [comment]
Thanks. We're gonna de-prioritize it (but we'll keep this in mind) because the only use-case of this plugin is inside VSCode and as an implementation detail helper library for our vim plugin. We don't intent do expose this LSP for broader consumption for now.
