### ISSUE TITLE
`catch` is not highlighted in try/catch

### ISSUE THREAD

**Issue by mxthevs** [rescript-lang/rescript-vscode#671]
`try` is highlighted, `catch` isn't.

I know `catch` is not a reserved keyword, but i think it should be highlighted when using it in a `try/catch` block.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/46231311/210270200-7342ae41-7364-42cf-891a-ea4b333b24e6.png">

In JavaScript, `catch` is highlighted.

<img width="172" alt="image" src="https://user-images.githubusercontent.com/46231311/210270609-d4881ba1-544e-41fc-86ec-1da2cb514873.png">

Can semantic highlighting take care of this?

**Comment by cristianoc** [comment]
Can be handled the same way `async` is handled in https://github.com/rescript-lang/rescript-vscode/issues/603: set to highlighting in the grammar, and semantic highlighting can take care of it when it's used as a variable.
