### ISSUE TITLE
Support auto completion with Belt open in global

### ISSUE THREAD

**Issue by LeoLeBras** [rescript-lang/rescript-vscode#676]
Hello 👋  and congratulations for all these improvements. It’s really great 🎉 
I’m having some troubles with the auto-completion :

![rescript-vscode](https://user-images.githubusercontent.com/856188/210731991-bc3e45ec-c5d1-4d79-b907-6fc32da9cddb.gif)

I have `Belt` open in global and I use `rescript-vscode` in version 1.11.4.

When I use an `array`, it autocompletes with `Js.Array2` instead of `Array` (from `Belt`).
When I use a `Result.t<'a>`, it autocompletes with `Pervasives.x`
When I use a `Future.t<'a>` (from `rescript-future`), it works great.

Do you know how to improve this and use `Belt` open in global for auto-completion?

[See also original post.](https://forum.rescript-lang.org/t/ann-vscode-extension-1-10-0-is-out/4048)

**Comment by zth** [comment]
@LeoLeBras these should both be fixed in the pre-release of the extension. Can you try that and report back?

**Comment by zth** [comment]
Please reopen if the fixes in the pre-release version is not enough.

**Comment by LeoLeBras** [comment]
It now works much better! The DX has improved drastically in the last few months thanks to your work. 🎉
There are still cases where auto-completion can be improved.
I will send you more examples if you are interested. You decide whether you want to correct them or not 😀.

**Comment by zth** [comment]
Thank you! Yes, please do detail those cases in new issues and we'll see what we can do.
