### ISSUE TITLE
Feature request: Syntax highlight improvement

### ISSUE THREAD

**Issue by BlueHotDog** [rescript-lang/rescript-vscode#70]
Hi, seems like moving to this extension from Reasonml introduces much worse experience in syntax highlighting. (less things are highlighted, and in general it looks "less")
Before i go ahead and try to improve it, is someone working on this?
(last time i tried to improve something my work got turned down since someone already worked on it, dont want to waste my time again)

**Comment by chenglou** [comment]
Hey. See this: https://github.com/rescript-lang/rescript-vscode#recommendation
And my comment here: https://github.com/rescript-lang/rescript-vscode/pull/8#issuecomment-764469070
