### ISSUE TITLE
JSX v4 auto completion

### ISSUE THREAD

**Issue by dkirchhof** [rescript-lang/rescript-vscode#707]
Hello,

I replaced the language server of my rescript-vim plugin to the latest one from this vs code plugin.
Unfortunatelly I have problems with the auto completion for props of a custom component.

In your "screenshot" (https://forum.rescript-lang.org/t/call-for-testing-more-autocomplete/4078#completion-for-jsx-prop-values-2) everything looks fine. 

In my editor it doesn't work:
![image](https://user-images.githubusercontent.com/2778643/213866104-ee5cb3e5-7213-442a-b982-8a3546c9aaff.png)

In normal html tags the auto completion works as expected:
![image](https://user-images.githubusercontent.com/2778643/213866333-a0820fae-0cf7-48bc-9bfa-796412835402.png)

Setup:
editor: neovim
rescript version: 10.1.0
server version: 1.10.0
jsx version: 4
jsx mode: automatic

**Comment by zth** [comment]
I guess this is because you're not using the `@react.component` annotation. What happens when you try using?

We should probably support this pattern too now with JSX v4.

**Comment by dkirchhof** [comment]
You're right. With `@react.component` and labeled arguments the auto completion shows all props (`text` and `key`).

**Comment by zth** [comment]
Thanks. We'll look into supporting this case as well.

**Comment by zth** [comment]
To be clear - this isn't actually about JSX v4, just that this pattern is now more expected than before. `@react.component` is still the recommended way with JSX v4, so this is about supporting this "alternate" pattern.

**Comment by dkirchhof** [comment]
Oh, didn't know that it was possible before. Thanks for clarification.
