### ISSUE TITLE
Module doc is not displayed

### ISSUE THREAD

**Issue by gaku-sei** [rescript-lang/rescript-vscode#73]
When adding some doc to a module:

```rescript
module ArrayExtra = {
  @@ocaml.doc("Module doc!")

  // ...
}
```

The doc doesn't show up in the suggestion modal:

<img width="1081" alt="Capture d’écran 2021-01-29 à 14 07 22" src="https://user-images.githubusercontent.com/3982371/106234064-509d2300-623b-11eb-9319-759bee25672a.png">

Maybe the new syntax for doc will solve this?

**Comment by gaku-sei** [comment]
Thank you for the update @amiralies

**Comment by chenglou** [comment]
Yep!
