### ISSUE TITLE
rescript-vscode non working after a fresh install 

### ISSUE THREAD

**Issue by zedryas** [rescript-lang/rescript-vscode#75]
New to rescript, i've done all steps specified in the getting started page and furthermore installed the visual studio code plugin but as I try to edit neither completion nor error highlighting works.

I've tried all steps on the plugin gif but if i can populate the first line for the rest nothing is working the same.

I don't know which file to pass you for exploring the configuration but it's exactly the same as in the getting started template repo.

I've asked the question on [stackoverflow](https://stackoverflow.com/questions/66019382/rescript-plugin-rescript-vscode-non-working-after-a-fresh-install) but can't get an answer they're so I'm putting it here as well.

**Comment by chenglou** [comment]
Hi. What OS? And did you start a bsb build?

**Comment by zedryas** [comment]
I fill dumb - did forgot to install the node modules
Closing this and sorry to make you loose your time

**Comment by chenglou** [comment]
No worries =)
