### ISSUE TITLE
Error E5248 in Neovim 0.9

### ISSUE THREAD

**Issue by fdaciuk** [rescript-lang/rescript-vscode#758]
Hi! Don't know if here is the right place to report this, but I've installed this extension using Mason on Neovim 0.9, and every time I open a `.res` file or try to type something in a `.res` file, I see this error message:

```
E5248: Invalid character in group name
```

![Screenshot from 2023-04-14 14-16-01](https://user-images.githubusercontent.com/487669/232113153-a6d0636b-36fd-40f0-8086-4103dec9e0a1.png)

The extension works fine in Neovim 0.8.

**Comment by aspeddro** [comment]
This has been fixed in https://github.com/rescript-lang/rescript-vscode/pull/757

You can install through pre release tag `latest-master` https://github.com/rescript-lang/rescript-vscode/releases/tag/latest-master

If you are using mason.nvim `:MasonInstall rescript-lsp@latest-master`

**Comment by fdaciuk** [comment]
Great, it works! Thansk @aspeddro ❤️
