### ISSUE TITLE
Broken autocompletion for polymorphic variants that use quotes

### ISSUE THREAD

**Issue by DZakh** [rescript-lang/rescript-vscode#760]
<img width="1284" alt="Screenshot 2023-04-21 at 19 06 30" src="https://user-images.githubusercontent.com/49292466/233671424-2ce75384-3c39-44c2-845d-238a57ad1c2e.png">
<img width="1050" alt="Screenshot 2023-04-21 at 19 06 43" src="https://user-images.githubusercontent.com/49292466/233671434-10b5ed13-9c4f-4154-92f5-0cb92aff273b.png">

It loses quotes during the autocomplete.

**Comment by zth** [comment]
Related: https://github.com/rescript-lang/rescript-vscode/pull/710
