### ISSUE TITLE
Create-Interface command in uncurried mode does not preserve `@react.component`

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-lang/rescript-vscode#772]
Consider the following example:

```rescript
@react.component
let make = (~name="") => <div />
```

In ReScript 11.0.0-alpha.6 with `"uncurried": false` when using the create-interface command, this is the resulting `.resi`:

```rescript
@react.component
let make: (~name: string=?) => Jsx.element
```

but when I set `"uncurried": true`, this is the result:

```rescript
type props<'name> = {name?: 'name}
let make: (. props<string>) => Jsx.element
```

I expected it to be the same as before.

**Comment by cristianoc** [comment]
Indeed it will need to support uncurried types.
