### ISSUE TITLE
Does auto-completion on pipe operator only worked for type t in Module?

### ISSUE THREAD

**Issue by Mng12345** [rescript-lang/rescript-vscode#792]
See the gif screen-shot below:
![mnggiflab-compressed-from-screen-recorder-2023_07_0417_44_03](https://github.com/rescript-lang/rescript-vscode/assets/21278900/3649a779-7ed1-4ac7-97ad-cfcb0f3e3654)
The example code is here: 
``` ReScript
type m = {
  name: string,
  age: int,
}

module M1 = {
  type t = m

  let getName = (m: t): string => {
    m.name
  }
}

module M2 = {
  type t = m

  type m = m
  let getAge = (m: t): int => {
    m.age
  }

  let getAge2 = (m: m): int => {
    m.age
  }
}

type m2 = M2.m

type m3 = M2.t

let m1: m = {
  age: 1,
  name: "m",
}

let m2: m2 = {
  age: 1,
  name: "m",
}

let m3: m3 = {
  age: 1,
  name: "m",
}
```
envrionment info: rescript v10.1.2 rescript-vscode v1.18.0
I have debugged the analysis, the auto completion for `m->`  walked into this switch, the variable pathRev is an empty list, is auto completion for normal type (not type t of a module) not considered for now?
![image](https://github.com/rescript-lang/rescript-vscode/assets/21278900/56ad419a-cbd1-4db9-8a48-f2fa9d7929e9)

**Comment by zth** [comment]
This is about resolving type aliases. When resolving type aliases, we stop at `t` specifically because we interpret that as an intention that `t` is the main type of a module.

For types that aren't aliases, you'll get completions from the full module.

**Comment by Mng12345** [comment]
So, if a type `t` alias some type `m`, then the auto-completion of a variable `a`(assume it's type is annotated with `m`) should be considered the same as type `t`. This form of auto-completion is usable in other languages like Scala, and it's very useful!

**Comment by fhammerschmidt** [comment]
I think aliased record types should expand as well, except if they are private. Currently, I copy a lot of type definitions over to have autocomplete. This does not feel right.

**Comment by zth** [comment]
Can you write a few examples of what that means and what the trade offs would be?

**Comment by fhammerschmidt** [comment]
I created a failing test here: https://github.com/rescript-lang/rescript-vscode/pull/834

**Comment by zth** [comment]
Sorry but I still don't understand the problem. That failing test is for a hover, but here you're talking about autocomplete. And this issue is about pipe autocompletion specifically. Could you clarify exactly what the problem(s) are and how they relate to this issue (pipe completion)?

**Comment by Mng12345** [comment]
@zth Hi, i think @fhammerschmidt means that when we define a type `a` which is aliased to a type t, t is defined in a module, the pipe completion of variables with type t are worked, but not worked with type a.

**Comment by fhammerschmidt** [comment]
Sorry for hijacking this issue, and for using hover and autocomplete synonymous. I tested autocomplete and it works for aliased records (I thought it does not), but not hover.

**Comment by Mng12345** [comment]
Wow! This is worked now!!!
![image](https://github.com/rescript-lang/rescript-vscode/assets/21278900/f2f971dd-0dd4-49b3-9174-07334d18eb61)
