### ISSUE TITLE
Type hints of aliased modules is wrong.

### ISSUE THREAD

**Issue by Mng12345** [rescript-lang/rescript-vscode#793]
![image](https://github.com/rescript-lang/rescript-vscode/assets/21278900/4a6d8b91-ef98-4299-af5e-892a417d2da0)
The completion is ok.
![image](https://github.com/rescript-lang/rescript-vscode/assets/21278900/a750efa6-eddf-467f-9403-a212d1aec5ac)

**Comment by aspeddro** [comment]
Same issue when install from template `npx create-rescript-app`

```rescript
module B = Belt.Array
```

Hover: `Unable to resolve module reference Belt_Array`

version: latest-master
