### ISSUE TITLE
Unify various `exec` calls

### ISSUE THREAD

**Issue by chenglou** [rescript-lang/rescript-vscode#81]
I'll cc @cristianoc, @mewhhaha and @john-pangalos (sorry for the ping) on this one.

Currently in the codebase there are 3 ways to call a binary:

- Async `exec`, with path and argument escaping: https://github.com/rescript-lang/rescript-vscode/blob/d1e5411e0f82cc0078e3d4a07900d521b085c9b1/server/src/RescriptEditorSupport.ts#L48
- Async `exec`, that doesn't escape path but does use the right windows bsb binary: https://github.com/rescript-lang/rescript-vscode/blob/d1e5411e0f82cc0078e3d4a07900d521b085c9b1/server/src/utils.ts#L107-L114
- Sync `execFileSync`, that might not call the right windows bsc binary: https://github.com/rescript-lang/rescript-vscode/blob/d1e5411e0f82cc0078e3d4a07900d521b085c9b1/server/src/utils.ts#L83

We should really revisit those and streamline them:
- First one:
  - [x] should be `execFile`, which avoids needing to escape the command path.
  - [x] should also be sync.
  - [x] should work on windows, if it isn't.
- Second one:
  - [ ] ~~should use `execFile` in the `win32` branch too, to avoid needing to escape path.~~ Can't use that for a batch script
- Third one
  - [x] should use the right windows bsc binary, if it isn't (where's the needed `.cmd` part? https://github.com/rescript-lang/rescript-vscode/pull/71#issuecomment-768200507).

**Comment by mewhhaha** [comment]
For the second case we followed the [documentation](https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows) on NodeJS. Is it possible to get around that if the file is a script? 

What's the condition for getting the popup for starting this process? Is it by having a single .res file open in the project?

**Comment by chenglou** [comment]
Oh right, yeah thanks for the reminder. I've finally understood the little complexities here. (Thanks also to @bsansouci for debugging on windows with me). d1dc096acf7ee1f013fe389f22d51b172adb16e8 fixes everything.

Thanks again!
