### ISSUE TITLE
1.26 + doom emacs = no go?

### ISSUE THREAD

**Issue by philiparvidsson** [rescript-lang/rescript-vscode#854]
I just upgraded to 1.26 right now, from having a few months old master vsix file. I installed it like I normally would, but it no longer runs. as soon as I open a .res file, it starts up and then exits immediately saying "check corresponoding stderr buffer for dteails, restart?"

the only thing it says is `Process rescript-vscode stderr finished`

**Comment by zth** [comment]
Maybe @aspeddro has some ideas.

**Comment by philiparvidsson** [comment]
maybe this is indeed an issue with rescript-mode and I may have made a mistake in assuming something's off with rescript-vscode - were breaking changes introduced in the cli or lsp interfaces recently?

**Comment by zth** [comment]
I'm not sure honestly, but I don't think so. The one thing I can think of is what mode you start the LSP in: https://github.com/rescript-lang/rescript-vscode/blob/master/server/src/cli.ts#L11-L14

**Comment by philiparvidsson** [comment]
yeah I'm using --stdio and have been all along

**Comment by philiparvidsson** [comment]
interestingly, both of these just exit silently:

`node /home/.../.config/rescript/server/out/server.js --stdio`

`node /home/.../.config/rescript/server/out/server.js --help`

no matter what, $status (running fish) is 0 afterwards.

**Comment by philiparvidsson** [comment]
ok, I figured it out. you used to be able to start the server with server.js, but now you're supposed to run cli.js

```
;; https://github.com/jjlee/rescript-mode
(after! rescript-mode
  (setq lsp-rescript-server-command
        '("node" "/home/.../.config/rescript/server/out/cli.js" "--stdio"))

```

Changed server.js to cli.js and it's working. thanks|
