### ISSUE TITLE
Errors in Problems window are cut, weirdly formatted and super hard to decipher in comparison to compiler output

### ISSUE THREAD

**Issue by mbergal** [rescript-lang/rescript-vscode#86]
Compiler output in terminal window:

![image](https://user-images.githubusercontent.com/167835/108912198-ed11d580-75ed-11eb-9b68-775845783ceb.png)

Problems window:

![image](https://user-images.githubusercontent.com/167835/108912238-fbf88800-75ed-11eb-82e3-25c327d18065.png)

Hover is a bit better:

![image](https://user-images.githubusercontent.com/167835/108912287-0dda2b00-75ee-11eb-8409-fe2ea9c79647.png)

**Comment by mbergal** [comment]
Here is another example of incomplete error message:

![image](https://user-images.githubusercontent.com/167835/109213836-b3b8a180-7776-11eb-9dc1-c0d26b75712f.png)

Compiler log:

```
#Start(1614285167013)

  Warning number 33
  /home/misha/projects/productionmason/web/auth/src/ErrorHandlingMiddleware.res:1:1-15
  
  1 │ open CommonBase
  2 │ 
  3 │ external jsExnToExpressError: Js.Exn.t => Express.Error.t = "%identity"
  
  unused open CommonBase.
  

  Warning number 27
  /home/misha/projects/productionmason/web/auth/src/config/Config.res:10:22-27
  
   8 │ external stringifyAnyWithSpace: ('a, @bs.as(json`null`) _, int) => str
       ing = "stringify"
   9 │ 
  10 │ let validateConfig = config => {
  11 │   let googleApplicationCredentialsPath =
  12 │     NodeJs.Process.env(NodeJs.Process.process)->Js.Dict.get("GOOGLE_AP
       PLICATION_CREDENTIALS")
  
  unused variable config.
  

  Warning number 34
  /home/misha/projects/productionmason/web/auth/src/express-handler/ExpressHandler.re:48:5-26
  
  46 ┆ module Input = {
  47 ┆   [@decco]
  48 ┆   type t = Request.input;
  49 ┆ };
  50 ┆ 
  
  unused type t.
  

  Warning number 32
  /home/misha/projects/productionmason/web/auth/src/express-handler/ExpressHandler.re
  
  unused value t_encode.
  

  We've found a bug for you!
  /home/misha/projects/productionmason/web/auth/tests/Auth_Test.res:224:45
  
  222 ┆ ->AsyncResult.mapOk(x => {
  223 ┆   expect(x.data.users->Array.length)->toBeGreaterThan(0)
  224 ┆   expect(x.data.users->Array.getExn(0).last_name)->toBe(Some("Glenliv
        et"))
  225 ┆   Ok()
  226 ┆ })
  
  This has type: int
  Somewhere wanted: array<'a>
  
#Done(1614285167075)

```

**Comment by chenglou** [comment]
Thanks, this is a known bug from the little editor error parser. We'll fix it. The line's too long and breaks onto the next line. In the meantime, you can manually put that line onto multiple lines.

**Comment by mbergal** [comment]
Looks as it is described as fixed in 1.0.7, but I am still having problems:

![image](https://user-images.githubusercontent.com/167835/113496960-82916680-94c4-11eb-8679-e0680e3f0681.png)

```
#Start(1617503102013)

  We've found a bug for you!
  /home/misha/projects/voltron/frontend/src/clients/shared/external/Commands/appointments/Commands_Appointments.res:51:17-23
  
  49 ┆ ~exceptions=ids->Array.map(id =>
  50 ┆   RemoveAppointments.makeInputObjectrecurring_appointment_exceptions_i
       nsert_input(
  51 ┆     ~date=id.date,
  52 ┆     ~production_id=id.productionId,
  53 ┆     ~user_id=id.userId,
  
  This has type: MomentTz.Moment.t
  Somewhere wanted: Js.Json.t (defined as Js_json.t)
  

  Warning number 27
  /home/misha/projects/voltron/frontend/src/clients/supervisor/view/zones/Supervisor_Zones.res:271:59-66
  
  269 ┆ 
  270 ┆ @react.component
  271 ┆ let make = (~selectable, ~table: ZonesTableState.table, ~refetch) => 
        {
  272 ┆   <>
  273 ┆     <Ui_Material_Table stickyHeader=true>
  
  unused variable refetch.
  
#Done(1617503102167)

```

**Comment by chenglou** [comment]
Ah sorry, I should have added an extra note. The fix requires master bs-platform, which will be making a release this weekend or so.

**Comment by chenglou** [comment]
Your diagnostics formatting issue is a different problem. Unfortunately that vscode panel swallows whitespace, and I think intentionally... Not sure what to do there yet

**Comment by mbergal** [comment]
> Your diagnostics formatting issue is a different problem. Unfortunately that vscode panel swallows whitespace, and I think intentionally... Not sure what to do there yet

Well, after using it for some time I think F8 (Go to Next Problem) through errors works ok, although it is in a single color, at least the indentation works ok there.
