### ISSUE TITLE
doc extracted signature of variant with inline-record incomplete?

### ISSUE THREAD

**Issue by woeps** [rescript-lang/rescript-vscode#887]
Given the following rescript [code](https://github.com/rescript-lang/rescript-vscode/blob/d0c842a3042a3904b1f9b45907008d46bc839d20/analysis/tests/src/DocExtractionRes.res#L28):

```rescript
type status =
    | /** If this is started or not */ Started(t) | /** Stopped? */ Stopped | /** Now idle.*/ Idle
```
is supposed to be extracted as the following [(partial) json](https://github.com/rescript-lang/rescript-vscode/blob/d0c842a3042a3904b1f9b45907008d46bc839d20/analysis/tests/src/expected/DocExtractionRes.res.txt#L49C4-L75C8):

```json
 {
      "id": "DocExtractionRes.SomeInnerModule.status",
      "kind": "type",
      "name": "status",
      "signature": "type status = Started(t) | Stopped | Idle",
      "docstrings": [],
      "detail": 
      {
        "kind": "variant",
        "items": [
        {
          "name": "Started",
          "docstrings": ["If this is started or not"],
          "signature": "Started(t)"        <-- HERE
        }, 
        {
          "name": "Stopped",
          "docstrings": ["Stopped?"],
          "signature": "Stopped"
        }, 
        {
          "name": "Idle",
          "docstrings": ["Now idle."],
          "signature": "Idle"
        }]
      }
    }, 
```

Especially mind the `Started` constructor having it's payload present in the json details' `signature` field!

Whereas it seems that the payload is not exported into it's json `signature` field, if it is an inline-record:
e.g. the following [code](https://github.com/rescript-lang/rescript-vscode/blob/d0c842a3042a3904b1f9b45907008d46bc839d20/analysis/tests/src/DocExtractionRes.res#L49):

```rescript
type someVariantWithInlineRecords = | /** This has inline records...*/ SomeStuff({offline: bool})
```

is currently tested to result in the following [(partial) json](https://github.com/rescript-lang/rescript-vscode/blob/d0c842a3042a3904b1f9b45907008d46bc839d20/analysis/tests/src/expected/DocExtractionRes.res.txt#L117-L133):

```json
  {
      "id": "DocExtractionRes.AnotherModule.someVariantWithInlineRecords",
      "kind": "type",
      "name": "someVariantWithInlineRecords",
      "signature": "type someVariantWithInlineRecords =\\n  | SomeStuff({offline: bool})",
      "docstrings": ["Trying how it looks with an inline record in a variant."],
      "detail": 
      {
        "kind": "variant",
        "items": [
        {
          "name": "SomeStuff",
          "docstrings": ["This has inline records..."],
          "signature": "SomeStuff"        <-- HERE
        }]
      }
    }, 
```

Even though the `SomeStuff` Variant Constructor has a payload, it is not reflected in the extracted details contents.

I woult at least expect the detail item json to be:

```json
{
  "name": "SomeStuff",
  "docstrings": ["This has inline records..."],
  "signature": "SomeStuff({offline: bool})"        <-- HERE
}
```

Is this a bug or a technical limitation?

_edit_:
Ideally, the docs of the inline-record would get extracted as well, by the same rules a "normal record" would be.

**Comment by zth** [comment]
Bug most likely, not a technical limitation.

**Comment by zth** [comment]
@woeps https://github.com/rescript-lang/rescript-vscode/pull/889 this should fix it.
