### ISSUE TITLE
completions not working for module opened by default

### ISSUE THREAD

**Issue by kswope** [rescript-lang/rescript-vscode#899]
referring to this feature

https://rescript-lang.org/blog/release-11-0-0#opening-files-from-current-project-globally

not seeing any completions, not sure if plugin even knows about this new feature.

ironic since opening globally is supposed to make it easier to use a module, but without completions its a wash ☺

**Comment by kswope** [comment]
NVM, FWI, had to totally restart VSCode for it to work

**Comment by zth** [comment]
A good tip is to always restart if a new feature isn't working. New versions are automatically downloaded by Vscode but applying them can take a while.
