### ISSUE TITLE
Support for OCaml/ReasonML syntax?

### ISSUE THREAD

**Issue by johnhaley81** [rescript-lang/rescript-vscode#9]
👋 

Thanks for making this project! With all of the tooling surrounding ReScript/ReasonML/OCaml being very hard to use, it would be nice if this package could work on all of the supported syntaxes. That would make the IDE/tooling experience much nicer.

**Comment by chenglou** [comment]
Hello!

> With all of the tooling surrounding ReScript/ReasonML/OCaml being very hard to use, it would be nice if this package could work on all of the supported syntaxes

No, at least for this plugin, the old syntax support isn't planned for now.

> That would make the IDE/tooling experience much nicer.

The reason why the tooling experience was bad was in big part because of the previous attempts to try to support every use-case. Those codebases became unmanageable and started falling apart.

Closing for now.
