### ISSUE TITLE
uncurried types get leaked

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/rescript-vscode#93]
<img width="355" alt="Screenshot 2021-03-12 at 3 36 18 PM" src="https://user-images.githubusercontent.com/747051/110907840-f4084a00-8348-11eb-99d8-de84289c72c5.png">

Unfortunately we can not make it an abstract type, I wonder if we can do some adhoc things to avoid expanding types in Js module.
cc @cristianoc

**Comment by cristianoc** [comment]
Already done in master.
