### ISSUE TITLE
Do we have deprecation message displayed why it is deprecated?

### ISSUE THREAD

**Issue by bobzhang** [rescript-lang/rescript-vscode#95]
<img width="362" alt="Screenshot 2021-03-16 at 4 14 08 PM" src="https://user-images.githubusercontent.com/747051/111276971-e584a000-8672-11eb-92d4-63134ccf1231.png">
Seems the deprecation message itself is not displayed

**Comment by chenglou** [comment]
Thanks. Imma merge this into #45
