### ISSUE TITLE
Incorrect autocomplete for jsx props after a variant

### ISSUE THREAD

**Issue by DZakh** [rescript-lang/rescript-vscode#962]
<img width="1041" alt="image" src="https://github.com/rescript-lang/rescript-vscode/assets/49292466/ba35ceb0-6b37-43f8-bbaf-c01fb4a1d55a">

I expect to get an autocomplete for the rest `Info` props here.

**Comment by zth** [comment]
Could you investigate if the type of the prop matters here, or if it's the same regardless of type?

**Comment by zth** [comment]
Also if you could PR a failing test then that'd be great.
