### ISSUE TITLE
Semantic token: let keyword

### ISSUE THREAD

**Issue by nojaf** [rescript-lang/rescript-vscode#978]
Hello, 

I noticed that I'm not getting any special semantic token for the `let` keyword:
![image](https://github.com/rescript-lang/rescript-vscode/assets/2621499/0408aae4-ee14-47a7-b6af-0180d47adefb)

Is this to be expected?

I do have it for `open` for example:

![image](https://github.com/rescript-lang/rescript-vscode/assets/2621499/e56494b1-ec35-4f07-81fa-b8d59b4d99db)

If this is a bug, I'm interested in sending a PR. But I could use some pointers on where to look for in the code.

**Comment by DZakh** [comment]
It uses `storage.type` grammar which is correct usage according to the document https://macromates.com/manual/en/language_grammars#naming_conventions.

Probably the issue with the theme not supporting `storage.type`.

**Comment by nojaf** [comment]
Oh, right. Spot on, thanks for clearing that up!
