### ISSUE TITLE
Attributes not included in reanalyze locations

### ISSUE THREAD

**Issue by zth** [rescript-lang/rescript-vscode#991]
cc @cristianoc 

Example: 
1. Create a `@react.component` that's unused
2. Start the code analyzer
3. Run the new code action for removing the unused code (available in the pre-release extension)
4. Everything but `@react.component` is removed

**Comment by cristianoc** [comment]
This happens to be due to an issue in the parser: https://github.com/rescript-lang/rescript-compiler/pull/6791

**Comment by cristianoc** [comment]
Fixed in compiler master.
